import type { SlotDef } from './types'

// Editable copy for /care-policies. Defaults are the current live copy; editing a
// slot in the platform (Main site pages → /care-policies) overrides it without
// touching the design.
export const CARE_POLICIES_SLOTS: SlotDef[] = [
  // Hero
  { key: 'hero.label', group: 'Hero', label: 'Eyebrow', default: 'Features' },
  { key: 'hero.h1', group: 'Hero', label: 'Headline', default: 'Everything your care team needs. Nothing they do not.' },
  { key: 'hero.intro', group: 'Hero', label: 'Intro paragraph', rich: true, default: 'CareStream is purpose-built for UK care settings. Every feature addresses a real challenge that registered managers, HR leads, and frontline staff face every day.' },
  { key: 'hero.cta1', group: 'Hero', label: 'Primary button', default: 'Start Free Trial' },
  { key: 'hero.cta2', group: 'Hero', label: 'Secondary button', default: 'Book a Demo' },

  // Channels
  { key: 'channels.label', group: 'Channels', label: 'Eyebrow', default: 'Access Channels' },
  { key: 'channels.h2', group: 'Channels', label: 'Heading', default: 'Ask in the hub, or by email. One consistent answer.' },
  { key: 'channels.intro', group: 'Channels', label: 'Intro paragraph', rich: true, default: 'Both draw from the same policy library and give the same quality of answer. Staff use whichever fits their situation, and every interaction lands in the same audit trail.' },
  { key: 'channels.hub.title', group: 'Channels', label: 'Hub card title', default: 'The Hub' },
  { key: 'channels.hub.subtitle', group: 'Channels', label: 'Hub card subtitle', default: 'Web and installable app' },
  { key: 'channels.hub.body', group: 'Channels', label: 'Hub card body', rich: true, default: 'A full conversational interface in any browser, and installable as an app on staff phones. Staff sign in once with a one-tap link, then ask questions by typing or speaking, with full context kept for the whole conversation.' },
  { key: 'channels.hub.item1', group: 'Channels', label: 'Hub bullet 1', default: 'Type or speak your question, and hear the answer read back' },
  { key: 'channels.hub.item2', group: 'Channels', label: 'Hub bullet 2', default: 'Full session context maintained across multiple questions' },
  { key: 'channels.hub.item3', group: 'Channels', label: 'Hub bullet 3', default: 'Suggested follow-up questions after every response' },
  { key: 'channels.hub.item4', group: 'Channels', label: 'Hub bullet 4', default: 'Installs like an app on any phone, with a passwordless sign-in link' },
  { key: 'channels.hub.item5', group: 'Channels', label: 'Hub bullet 5', default: 'Answers in over 60 languages, in the language you ask' },
  { key: 'channels.email.title', group: 'Channels', label: 'Email card title', default: 'Email' },
  { key: 'channels.email.subtitle', group: 'Channels', label: 'Email card subtitle', default: 'Any email client, any device' },
  { key: 'channels.email.body', group: 'Channels', label: 'Email card body', rich: true, default: 'Staff email your dedicated CareStream address from any device. The reply arrives in the same thread, and replying to it continues the conversation with full context kept across every exchange.' },
  { key: 'channels.email.item1', group: 'Channels', label: 'Email bullet 1', default: 'No app and no sign-in required to use' },
  { key: 'channels.email.item2', group: 'Channels', label: 'Email bullet 2', default: 'Response delivered into the same email thread' },
  { key: 'channels.email.item3', group: 'Channels', label: 'Email bullet 3', default: 'Reply to ask a follow-up question at any time' },
  { key: 'channels.email.item4', group: 'Channels', label: 'Email bullet 4', default: 'Works from any email app on any device' },
  { key: 'channels.email.item5', group: 'Channels', label: 'Email bullet 5', default: 'Ideal during shift handover or when away from the home' },

  // Multilingual
  { key: 'multilingual.label', group: 'Multilingual', label: 'Eyebrow', default: 'Multilingual Engine' },
  { key: 'multilingual.h2', group: 'Multilingual', label: 'Heading', default: '60+ languages. Zero configuration.' },
  { key: 'multilingual.p1', group: 'Multilingual', label: 'Paragraph 1', rich: true, default: 'Language detection is automatic on every query. Staff do not select a language, toggle a setting, or use any special command. They ask their question in the language they think in, and the answer arrives in the same language.' },
  { key: 'multilingual.p2', group: 'Multilingual', label: 'Paragraph 2', rich: true, default: 'Your policies remain in English. Translation happens at the point of response, not at the point of upload. One authoritative English policy library, consistently available in every language your workforce uses.' },
  { key: 'multilingual.stat1.value', group: 'Multilingual', label: 'Stat 1 value', default: '60+' },
  { key: 'multilingual.stat1.label', group: 'Multilingual', label: 'Stat 1 label', default: 'Languages detected' },
  { key: 'multilingual.stat2.value', group: 'Multilingual', label: 'Stat 2 value', default: 'English' },
  { key: 'multilingual.stat2.label', group: 'Multilingual', label: 'Stat 2 label', default: 'Source policy language' },
  { key: 'multilingual.stat3.value', group: 'Multilingual', label: 'Stat 3 value', default: 'None' },
  { key: 'multilingual.stat3.label', group: 'Multilingual', label: 'Stat 3 label', default: 'Setup required' },
  { key: 'multilingual.stat4.value', group: 'Multilingual', label: 'Stat 4 value', default: '£0' },
  { key: 'multilingual.stat4.label', group: 'Multilingual', label: 'Stat 4 label', default: 'Extra cost per language' },
  { key: 'multilingual.demoTitle', group: 'Multilingual', label: 'Demo heading', default: 'The same question, six languages, one policy' },
  { key: 'multilingual.demoCaption', group: 'Multilingual', label: 'Demo caption', default: 'All answered from the same Falls Policy, each in the language asked' },

  // Policy management
  { key: 'policyMgmt.label', group: 'Policy Management', label: 'Eyebrow', default: 'Policy Management' },
  { key: 'policyMgmt.h2', group: 'Policy Management', label: 'Heading', default: 'A policy library that works as hard as you do.' },
  { key: 'policyMgmt.intro', group: 'Policy Management', label: 'Intro paragraph', rich: true, default: 'Upload once and CareStream handles the rest. Documents are automatically processed, indexed, and made searchable within minutes of upload with no manual work required.' },
  { key: 'policyMgmt.card1.title', group: 'Policy Management', label: 'Card 1 title', default: 'PDF, Word and plain text' },
  { key: 'policyMgmt.card1.body', group: 'Policy Management', label: 'Card 1 body', multiline: true, default: 'Upload any combination of file formats. CareStream reads and indexes all common document types with no conversion or reformatting needed from you.' },
  { key: 'policyMgmt.card2.title', group: 'Policy Management', label: 'Card 2 title', default: 'Live within minutes of upload' },
  { key: 'policyMgmt.card2.body', group: 'Policy Management', label: 'Card 2 body', multiline: true, default: 'Documents are processed and indexed automatically. Staff can query a newly uploaded policy within minutes of it being added to the library.' },
  { key: 'policyMgmt.card3.title', group: 'Policy Management', label: 'Card 3 title', default: 'Header and footer stripping' },
  { key: 'policyMgmt.card3.body', group: 'Policy Management', label: 'Card 3 body', multiline: true, default: 'Page numbers, version stamps, document headers and footers are removed automatically. The AI reads only the substantive policy content.' },
  { key: 'policyMgmt.card4.title', group: 'Policy Management', label: 'Card 4 title', default: 'Semantic chunking and indexing' },
  { key: 'policyMgmt.card4.body', group: 'Policy Management', label: 'Card 4 body', multiline: true, default: 'Each document is broken into meaningful sections and indexed for semantic search. Answers are retrieved even when the wording of the question differs from the policy.' },
  { key: 'policyMgmt.card5.title', group: 'Policy Management', label: 'Card 5 title', default: 'Version control and history' },
  { key: 'policyMgmt.card5.body', group: 'Policy Management', label: 'Card 5 body', multiline: true, default: 'Upload a revised policy and the old version is retired from the retrieval system automatically. The full version history is retained for post-incident review.' },
  { key: 'policyMgmt.card6.title', group: 'Policy Management', label: 'Card 6 title', default: 'Review date reminders' },
  { key: 'policyMgmt.card6.body', group: 'Policy Management', label: 'Card 6 body', multiline: true, default: 'Set a review interval for each policy and CareStream will remind you when it is due. Your library stays current without any manual tracking.' },
  { key: 'policyMgmt.card7.title', group: 'Policy Management', label: 'Card 7 title', default: 'Staff handbook support' },
  { key: 'policyMgmt.card7.body', group: 'Policy Management', label: 'Card 7 body', multiline: true, default: 'Upload your staff handbook alongside your clinical policies. Large handbooks are indexed chapter by chapter, so staff get accurate answers about annual leave, disciplinary procedures, pay and onboarding from the right part of the document.' },
  { key: 'policyMgmt.card8.title', group: 'Policy Management', label: 'Card 8 title', default: 'Policy categories and tagging' },
  { key: 'policyMgmt.card8.body', group: 'Policy Management', label: 'Card 8 body', multiline: true, default: 'Organise your library by category, department, or regulatory framework. Makes browsing and reporting easier for managers and auditors.' },
  { key: 'policyMgmt.card9.title', group: 'Policy Management', label: 'Card 9 title', default: 'Answers cite the source' },
  { key: 'policyMgmt.card9.body', group: 'Policy Management', label: 'Card 9 body', multiline: true, default: 'Every answer names the policy and the version it came from, so staff can check the exact source and you can trust what was said.' },

  // Regulatory intelligence
  { key: 'regulatory.label', group: 'Regulatory Intelligence', label: 'Eyebrow', default: 'Regulatory Intelligence' },
  { key: 'regulatory.h2', group: 'Regulatory Intelligence', label: 'Heading', default: 'UK regulation, alongside your own policies.' },
  { key: 'regulatory.intro', group: 'Regulatory Intelligence', label: 'Intro paragraph', rich: true, default: 'Your internal policies are built on UK law and regulation. CareStream keeps the UK regulations that matter to care services loaded and up to date, so when a staff member asks something that touches both your policy and an external requirement, the response explains how the two interact.' },
  { key: 'regulatory.howLabel', group: 'Regulatory Intelligence', label: 'How it works label', default: 'How it works' },
  { key: 'regulatory.step1.title', group: 'Regulatory Intelligence', label: 'Step 1 title', default: 'Your internal policy is retrieved' },
  { key: 'regulatory.step1.body', group: 'Regulatory Intelligence', label: 'Step 1 body', multiline: true, default: 'The most relevant section of your own policy is found and used as the primary source for the response.' },
  { key: 'regulatory.step2.title', group: 'Regulatory Intelligence', label: 'Step 2 title', default: 'Relevant regulations are overlaid' },
  { key: 'regulatory.step2.body', group: 'Regulatory Intelligence', label: 'Step 2 body', multiline: true, default: 'CareStream identifies which of the loaded frameworks apply to the question and adds that regulatory context to the response.' },
  { key: 'regulatory.step3.title', group: 'Regulatory Intelligence', label: 'Step 3 title', default: 'The interaction is explained' },
  { key: 'regulatory.step3.body', group: 'Regulatory Intelligence', label: 'Step 3 body', multiline: true, default: 'The response covers what your policy requires and what the law requires, and explains where they align, where they differ, and where your policy goes further.' },
  { key: 'regulatory.frameworksLabel', group: 'Regulatory Intelligence', label: 'Frameworks label', default: 'A selection of included frameworks' },
  { key: 'regulatory.fw1.name', group: 'Regulatory Intelligence', label: 'Framework 1 name', default: 'CQC Fundamental Standards' },
  { key: 'regulatory.fw1.reg', group: 'Regulatory Intelligence', label: 'Framework 1 badge', default: 'Reg 9 to 20' },
  { key: 'regulatory.fw2.name', group: 'Regulatory Intelligence', label: 'Framework 2 name', default: 'Health and Safety at Work Act 1974' },
  { key: 'regulatory.fw2.reg', group: 'Regulatory Intelligence', label: 'Framework 2 badge', default: 'HSWA 1974' },
  { key: 'regulatory.fw3.name', group: 'Regulatory Intelligence', label: 'Framework 3 name', default: 'GDPR and Data Protection Act 2018' },
  { key: 'regulatory.fw3.reg', group: 'Regulatory Intelligence', label: 'Framework 3 badge', default: 'UK GDPR' },
  { key: 'regulatory.fw4.name', group: 'Regulatory Intelligence', label: 'Framework 4 name', default: 'Mental Capacity Act 2005' },
  { key: 'regulatory.fw4.reg', group: 'Regulatory Intelligence', label: 'Framework 4 badge', default: 'MCA 2005' },
  { key: 'regulatory.fw5.name', group: 'Regulatory Intelligence', label: 'Framework 5 name', default: 'Care Act 2014 Safeguarding' },
  { key: 'regulatory.fw5.reg', group: 'Regulatory Intelligence', label: 'Framework 5 badge', default: 'Care Act 2014' },
  { key: 'regulatory.fw6.name', group: 'Regulatory Intelligence', label: 'Framework 6 name', default: 'RIDDOR 2013' },
  { key: 'regulatory.fw6.reg', group: 'Regulatory Intelligence', label: 'Framework 6 badge', default: 'RIDDOR 2013' },
  { key: 'regulatory.fw7.name', group: 'Regulatory Intelligence', label: 'Framework 7 name', default: 'Equality Act 2010' },
  { key: 'regulatory.fw7.reg', group: 'Regulatory Intelligence', label: 'Framework 7 badge', default: 'EA 2010' },
  { key: 'regulatory.fw8.name', group: 'Regulatory Intelligence', label: 'Framework 8 name', default: 'Control of Substances Hazardous to Health' },
  { key: 'regulatory.fw8.reg', group: 'Regulatory Intelligence', label: 'Framework 8 badge', default: 'COSHH 2002' },
  { key: 'regulatory.frameworksMore', group: 'Regulatory Intelligence', label: 'Frameworks footer', default: 'Plus more, kept up to date as regulations change' },

  // Knowledge base
  { key: 'knowledge.label', group: 'Knowledge Base', label: 'Eyebrow', default: 'The Knowledge Base' },
  { key: 'knowledge.h2', group: 'Knowledge Base', label: 'Heading', rich: true, default: 'Not generic answers. <span style="color: #E8850A;">Your home&rsquo;s answers.</span>' },
  { key: 'knowledge.p1', group: 'Knowledge Base', label: 'Paragraph 1', rich: true, default: 'CareStream answers from the actual content of your own policies. When a policy names a person, a schedule, or an exact local procedure, that is what staff get back, not a generic restatement.' },
  { key: 'knowledge.p2', group: 'Knowledge Base', label: 'Paragraph 2', rich: true, default: 'Managers can also add knowledge entries directly, capturing the operational detail that lives in practice, named leads, local procedures, and out-of-hours contacts, and approving it so it is available to everyone in the same answers.' },
  { key: 'knowledge.col1', group: 'Knowledge Base', label: 'Table column 1', default: 'Staff asks' },
  { key: 'knowledge.col2', group: 'Knowledge Base', label: 'Table column 2', default: 'Generic policy answer' },
  { key: 'knowledge.col3', group: 'Knowledge Base', label: 'Table column 3', default: 'CareStream answer' },
  { key: 'knowledge.row1.q', group: 'Knowledge Base', label: 'Row 1 question', default: 'Who is responsible for infection control?' },
  { key: 'knowledge.row1.generic', group: 'Knowledge Base', label: 'Row 1 generic answer', multiline: true, default: '"The designated infection control lead as named in the policy."' },
  { key: 'knowledge.row1.specific', group: 'Knowledge Base', label: 'Row 1 CareStream answer', multiline: true, default: '"Maria Chen is the Infection Control Lead. On nights and weekends, cover is provided by the senior carer on shift."' },
  { key: 'knowledge.row2.q', group: 'Knowledge Base', label: 'Row 2 question', default: 'How often is the sluice room deep-cleaned?' },
  { key: 'knowledge.row2.generic', group: 'Knowledge Base', label: 'Row 2 generic answer', multiline: true, default: '"According to the cleaning schedule in the Infection Control Policy."' },
  { key: 'knowledge.row2.specific', group: 'Knowledge Base', label: 'Row 2 CareStream answer', multiline: true, default: '"The sluice room is deep-cleaned every Monday and Thursday morning. The daily clean is recorded on the log inside the door."' },
  { key: 'knowledge.row3.q', group: 'Knowledge Base', label: 'Row 3 question', default: 'What colour mop for the bathrooms?' },
  { key: 'knowledge.row3.generic', group: 'Knowledge Base', label: 'Row 3 generic answer', multiline: true, default: '"Follow the colour-coding scheme set out in the Infection Control Policy."' },
  { key: 'knowledge.row3.specific', group: 'Knowledge Base', label: 'Row 3 CareStream answer', multiline: true, default: '"Blue mops for bathrooms and toilets. Yellow for kitchen areas. Red for high-risk areas only."' },
  { key: 'knowledge.row4.q', group: 'Knowledge Base', label: 'Row 4 question', default: 'Who do I call for a medication issue overnight?' },
  { key: 'knowledge.row4.generic', group: 'Knowledge Base', label: 'Row 4 generic answer', multiline: true, default: '"Contact the on-call manager per the Medication Policy."' },
  { key: 'knowledge.row4.specific', group: 'Knowledge Base', label: 'Row 4 CareStream answer', multiline: true, default: '"Call Sarah Ambridge on the duty manager number. The out-of-hours number is posted inside the medication room door."' },

  // Policy gap detection
  { key: 'gap.label', group: 'Policy Gap Detection', label: 'Eyebrow', default: 'Policy Gap Detection' },
  { key: 'gap.h2', group: 'Policy Gap Detection', label: 'Heading', default: 'Find your gaps before CQC does.' },
  { key: 'gap.p1', group: 'Policy Gap Detection', label: 'Paragraph 1', rich: true, default: 'Every time CareStream cannot find an answer in your documents, it flags the query as a gap. Over time, patterns emerge: the same questions appearing repeatedly without any policy coverage.' },
  { key: 'gap.p2', group: 'Policy Gap Detection', label: 'Paragraph 2', rich: true, default: 'Your Policy Gap Report shows exactly which questions your staff are asking that your current policies do not address, ranked by frequency. This is actionable evidence of where your library needs strengthening, surfaced before an inspection identifies it first.' },
  { key: 'gap.item1.title', group: 'Policy Gap Detection', label: 'Item 1 title', default: 'Real-time flagging' },
  { key: 'gap.item1.body', group: 'Policy Gap Detection', label: 'Item 1 body', multiline: true, default: 'Every unanswered query is flagged immediately rather than batched for a monthly report.' },
  { key: 'gap.item2.title', group: 'Policy Gap Detection', label: 'Item 2 title', default: 'Ranked by frequency' },
  { key: 'gap.item2.body', group: 'Policy Gap Detection', label: 'Item 2 body', multiline: true, default: 'The most commonly asked unanswered questions appear first, so you address the most impactful gaps first.' },
  { key: 'gap.item3.title', group: 'Policy Gap Detection', label: 'Item 3 title', default: 'Always up to date' },
  { key: 'gap.item3.body', group: 'Policy Gap Detection', label: 'Item 3 body', multiline: true, default: 'The gap report is kept current and ready for your manager review cycle, with nothing to compile by hand.' },
  { key: 'gap.item4.title', group: 'Policy Gap Detection', label: 'Item 4 title', default: 'Evidence for CQC' },
  { key: 'gap.item4.body', group: 'Policy Gap Detection', label: 'Item 4 body', multiline: true, default: 'Gap identification and resolution is included in your CQC Readiness Report as proof of continuous improvement.' },

  // Analytics and compliance
  { key: 'analytics.label', group: 'Analytics', label: 'Eyebrow', default: 'Analytics and Compliance' },
  { key: 'analytics.h2', group: 'Analytics', label: 'Heading', default: 'Your compliance evidence builds automatically.' },
  { key: 'analytics.intro', group: 'Analytics', label: 'Intro paragraph', rich: true, default: 'Every interaction with CareStream is logged and structured. Your analytics dashboard and CQC Readiness Report are generated from this data continuously, with nothing to compile manually.' },
  { key: 'analytics.colFeature', group: 'Analytics', label: 'Table column: feature', default: 'Analytics feature' },
  { key: 'analytics.colStarter', group: 'Analytics', label: 'Table column: Starter', default: 'Starter' },
  { key: 'analytics.colPro', group: 'Analytics', label: 'Table column: Professional', default: 'Professional' },
  { key: 'analytics.notIncluded', group: 'Analytics', label: 'Not-included cell text', default: 'Not included' },
  { key: 'analytics.feat1', group: 'Analytics', label: 'Feature 1', default: 'Total queries and trend over time' },
  { key: 'analytics.feat2', group: 'Analytics', label: 'Feature 2', default: 'Queries by channel (hub, email, voice)' },
  { key: 'analytics.feat3', group: 'Analytics', label: 'Feature 3', default: 'Most requested policies this month' },
  { key: 'analytics.feat4', group: 'Analytics', label: 'Feature 4', default: 'Active staff members this month' },
  { key: 'analytics.feat5', group: 'Analytics', label: 'Feature 5', default: 'Plan usage vs allowance' },
  { key: 'analytics.feat6', group: 'Analytics', label: 'Feature 6', default: 'Policy not found rate' },
  { key: 'analytics.feat7', group: 'Analytics', label: 'Feature 7', default: 'Policy last updated date' },
  { key: 'analytics.feat8', group: 'Analytics', label: 'Feature 8', default: 'Language breakdown across all queries' },
  { key: 'analytics.feat9', group: 'Analytics', label: 'Feature 9', default: 'Knowledge gap detection report' },
  { key: 'analytics.feat10', group: 'Analytics', label: 'Feature 10', default: 'Query trend analysis over 12 months' },
  { key: 'analytics.feat11', group: 'Analytics', label: 'Feature 11', default: 'Staff engagement by individual' },
  { key: 'analytics.feat12', group: 'Analytics', label: 'Feature 12', default: 'CQC Readiness Report PDF' },

  // Data and security
  { key: 'security.label', group: 'Data and Security', label: 'Eyebrow', default: 'Data and Security' },
  { key: 'security.h2', group: 'Data and Security', label: 'Heading', default: 'Your data stays yours.' },
  { key: 'security.body', group: 'Data and Security', label: 'Paragraph', rich: true, default: 'Every tenant&rsquo;s policy library is stored in a completely isolated environment. Your policies are never used to train any model, never shared with other organisations, and never accessible to anyone outside your account. Data is encrypted at rest and in transit. UK data residency is available on Professional and Enterprise plans.' },
  { key: 'security.item1.label', group: 'Data and Security', label: 'Item 1 label', default: 'Tenant isolation' },
  { key: 'security.item1.detail', group: 'Data and Security', label: 'Item 1 detail', multiline: true, default: 'Complete data separation between all organisations' },
  { key: 'security.item2.label', group: 'Data and Security', label: 'Item 2 label', default: 'Approved knowledge only' },
  { key: 'security.item2.detail', group: 'Data and Security', label: 'Item 2 detail', multiline: true, default: 'Only vetted, approved content is ever served to staff' },
  { key: 'security.item3.label', group: 'Data and Security', label: 'Item 3 label', default: 'Never used for training' },
  { key: 'security.item3.detail', group: 'Data and Security', label: 'Item 3 detail', multiline: true, default: 'Your documents are never used to train AI models' },
  { key: 'security.item4.label', group: 'Data and Security', label: 'Item 4 label', default: 'UK data residency' },
  { key: 'security.item4.detail', group: 'Data and Security', label: 'Item 4 detail', multiline: true, default: 'Available on Professional and Enterprise plans' },
]
