import type { SlotDef } from './types'

// Editable copy for the homepage ("/"). Defaults are the current live copy; editing
// a slot in the platform (Main site pages → /) overrides it without touching design.
// Illustrative mockup content (fake chat bubbles, sample dashboards, device chrome,
// decorative image-overlay badges) and shared data arrays (language pills, logo
// marquee, imported settings/blog/FAQ) are intentionally NOT slotted.
export const HOME_SLOTS: SlotDef[] = [
  // Hero
  { key: 'hero.h1.lead', group: 'Hero', label: 'Headline — before animated word', default: 'Your policies, turned into' },
  { key: 'hero.h1.emphasis', group: 'Hero', label: 'Headline — emphasis', default: 'In any language.' },
  { key: 'hero.sub', group: 'Hero', label: 'Sub-paragraph', multiline: true, default: 'Upload your policies once. CareStream turns them into answers your staff can use at 3am, training modules, audits and inspection evidence. Grounded in your documents. Never the internet.' },
  { key: 'hero.cta.primary', group: 'Hero', label: 'Primary CTA', default: 'Book a Free Demo' },
  { key: 'hero.cta.secondary', group: 'Hero', label: 'Secondary CTA', default: 'See how it works' },
  { key: 'hero.trust1', group: 'Hero', label: 'Trust chip 1', default: '14-day free trial' },
  { key: 'hero.trust2', group: 'Hero', label: 'Trust chip 2', default: 'No charge until day 14' },
  { key: 'hero.trust3', group: 'Hero', label: 'Trust chip 3', default: 'Set up in under an hour' },
  { key: 'hero.trust4', group: 'Hero', label: 'Trust chip 4', default: 'GDPR Compliant' },

  // Stats strip
  { key: 'stats.s1.num', group: 'Stats strip', label: 'Stat 1 figure', default: '30%+' },
  { key: 'stats.s1.label', group: 'Stats strip', label: 'Stat 1 label', default: 'UK care workers born outside the UK' },
  { key: 'stats.s2.num', group: 'Stats strip', label: 'Stat 2 figure', default: '150+' },
  { key: 'stats.s2.label', group: 'Stats strip', label: 'Stat 2 label', default: 'Languages spoken in UK care settings' },
  { key: 'stats.s3.num', group: 'Stats strip', label: 'Stat 3 figure', default: '1 in 3' },
  { key: 'stats.s3.label', group: 'Stats strip', label: 'Stat 3 label', default: 'Night-shift policy questions go unanswered' },
  { key: 'stats.s4.num', group: 'Stats strip', label: 'Stat 4 figure', default: '£85' },
  { key: 'stats.s4.label', group: 'Stats strip', label: 'Stat 4 label', default: 'per month, less than one agency shift hour' },

  // The Problem
  { key: 'problem.label', group: 'The Problem', label: 'Eyebrow', default: 'The Challenge in Care' },
  { key: 'problem.h2.pre', group: 'The Problem', label: 'Heading — lead', default: 'The language gap in care is a' },
  { key: 'problem.h2.emphasis', group: 'The Problem', label: 'Heading — emphasis', default: 'safety gap.' },
  { key: 'problem.p1', group: 'The Problem', label: 'Paragraph 1', rich: true, default: 'Over 30% of the UK care workforce was born outside the United Kingdom. In many homes, the majority of the care team speaks English as a second language.' },
  { key: 'problem.p2', group: 'The Problem', label: 'Paragraph 2', rich: true, default: 'Yet every policy system operates entirely in English, creating a persistent gap between what the policy says and what staff can confidently act on.' },
  { key: 'problem.p3', group: 'The Problem', label: 'Paragraph 3', rich: true, default: 'At 3am, during an incident, in the first weeks of a new job, that gap leads to hesitation, misinterpretation, and decisions made without the guidance that should have been available.' },
  { key: 'problem.card1.title', group: 'The Problem', label: 'Card 1 title', default: 'Policies in English only' },
  { key: 'problem.card1.body', group: 'The Problem', label: 'Card 1 body', multiline: true, default: 'Your carefully written procedures are inaccessible to a large portion of the people they are designed to protect.' },
  { key: 'problem.card2.title', group: 'The Problem', label: 'Card 2 title', default: 'No support at 3am' },
  { key: 'problem.card2.body', group: 'The Problem', label: 'Card 2 body', multiline: true, default: 'Night staff face clinical uncertainty without a manager present, and no reliable way to find the right answer fast.' },
  { key: 'problem.card3.title', group: 'The Problem', label: 'Card 3 title', default: 'Compliance gaps at inspection' },
  { key: 'problem.card3.body', group: 'The Problem', label: 'Card 3 body', multiline: true, default: "CQC expects evidence that staff actively use and understand your policies. A folder on a shelf isn't evidence." },

  // Policy engine (the centrepiece: policies in, everything out)
  { key: 'engine.label', group: 'Policy engine', label: 'Eyebrow', default: 'How CareStream Works' },
  { key: 'engine.h2.pre', group: 'Policy engine', label: 'Heading — lead', default: 'Upload your policies once.' },
  { key: 'engine.h2.emphasis', group: 'Policy engine', label: 'Heading — emphasis', default: 'Everything else runs off them.' },
  { key: 'engine.intro', group: 'Policy engine', label: 'Intro', multiline: true, default: 'Your policy library is the engine. Upload it once and CareStream turns it into instant answers for your staff, training modules, audits and CQC evidence, all grounded in your own documents. Never the internet.' },
  { key: 'engine.spoke1.title', group: 'Policy engine', label: 'Spoke 1 title', default: 'Instant policy answers' },
  { key: 'engine.spoke1.body', group: 'Policy engine', label: 'Spoke 1 body', multiline: true, default: 'Staff ask in the hub, by email or by voice, in 60+ languages, and get cited answers from your policies in under 30 seconds.' },
  { key: 'engine.spoke2.title', group: 'Policy engine', label: 'Spoke 2 title', default: 'Staff training' },
  { key: 'engine.spoke2.body', group: 'Policy engine', label: 'Spoke 2 body', multiline: true, default: 'Training modules built from your own policies, completed in the hub, with renewal reminders and completion tracking.' },
  { key: 'engine.spoke3.title', group: 'Policy engine', label: 'Spoke 3 title', default: 'Care audits' },
  { key: 'engine.spoke3.body', group: 'Policy engine', label: 'Spoke 3 body', multiline: true, default: 'Structured audits scored section by section, producing inspection-ready reports and action plans.' },
  { key: 'engine.spoke4.title', group: 'Policy engine', label: 'Spoke 4 title', default: 'CQC preparation' },
  { key: 'engine.spoke4.body', group: 'Policy engine', label: 'Spoke 4 body', multiline: true, default: 'Readiness Reports, inspector-style staff questions and an audit trail of evidence that builds itself.' },

  // How it works (steps reused inside the Policy engine section)
  { key: 'howitworks.step1.title', group: 'How it works', label: 'Step 1 title', default: 'Upload your policies' },
  { key: 'howitworks.step1.body', group: 'How it works', label: 'Step 1 body', multiline: true, default: 'Upload your policy library and staff handbook via the admin dashboard. PDF, Word, or plain text. CareStreamAI processes them and builds your private, searchable library.' },
  { key: 'howitworks.step2.title', group: 'How it works', label: 'Step 2 title', default: 'Staff start asking' },
  { key: 'howitworks.step2.body', group: 'How it works', label: 'Step 2 body', multiline: true, default: 'Your team sends questions via email or the web chat portal, in any language. CareStreamAI identifies the language automatically and retrieves the most relevant policy content.' },
  { key: 'howitworks.step3.title', group: 'How it works', label: 'Step 3 title', default: 'Instant, grounded answers' },
  { key: 'howitworks.step3.body', group: 'How it works', label: 'Step 3 body', multiline: true, default: 'Responses arrive in under 30 seconds, in the language the question was asked, drawn only from your approved documents. Never the internet.' },
  { key: 'howitworks.step4.title', group: 'How it works', label: 'Step 4 title', default: 'Your compliance evidence builds' },
  { key: 'howitworks.step4.body', group: 'How it works', label: 'Step 4 body', multiline: true, default: 'Every query is logged. Your CQC Readiness Report builds automatically, policy access, language activity, staff engagement, version history.' },
  { key: 'howitworks.cta', group: 'How it works', label: 'CTA', default: 'See the full walkthrough' },

  // Regulation layer
  { key: 'reg.label', group: 'Regulation layer', label: 'Eyebrow', default: 'Regulatory Intelligence' },
  { key: 'reg.h2.pre', group: 'Regulation layer', label: 'Heading — lead', default: 'Your policies and the law,' },
  { key: 'reg.h2.emphasis', group: 'Regulation layer', label: 'Heading — emphasis', default: 'answered together.' },
  { key: 'reg.intro', group: 'Regulation layer', label: 'Intro', rich: true, default: 'The UK care regulations and statutory frameworks that matter to a care service are loaded into CareStream and kept up to date. When a staff member asks something that touches both your internal policy and an external framework, the response explains how the two interact, not just what your policy says in isolation.' },
  { key: 'reg.pill', group: 'Regulation layer', label: 'Pill text', default: 'UK regulations, loaded and kept up to date' },
  { key: 'reg.frameworks.label', group: 'Regulation layer', label: 'Frameworks label', default: 'A selection of frameworks included' },
  { key: 'reg.frameworks.badge', group: 'Regulation layer', label: 'Frameworks badge', default: 'and more' },
  { key: 'reg.f1.name', group: 'Regulation layer', label: 'Framework 1 name', default: 'CQC Fundamental Standards' },
  { key: 'reg.f1.reg', group: 'Regulation layer', label: 'Framework 1 tag', default: 'Reg 12, 17 & 19' },
  { key: 'reg.f1.desc', group: 'Regulation layer', label: 'Framework 1 desc', multiline: true, default: 'The baseline requirements every registered service must meet: safe care, governance, and fit and proper persons.' },
  { key: 'reg.f2.name', group: 'Regulation layer', label: 'Framework 2 name', default: 'Health & Safety at Work Act 1974' },
  { key: 'reg.f2.reg', group: 'Regulation layer', label: 'Framework 2 tag', default: 'HSWA 1974' },
  { key: 'reg.f2.desc', group: 'Regulation layer', label: 'Framework 2 desc', multiline: true, default: 'Employer and employee duties around risk assessment, safe systems of work, and incident reporting.' },
  { key: 'reg.f3.name', group: 'Regulation layer', label: 'Framework 3 name', default: 'GDPR & Data Protection Act 2018' },
  { key: 'reg.f3.reg', group: 'Regulation layer', label: 'Framework 3 tag', default: 'UK GDPR' },
  { key: 'reg.f3.desc', group: 'Regulation layer', label: 'Framework 3 desc', multiline: true, default: 'How resident and staff data must be collected, stored, shared, and protected.' },
  { key: 'reg.f4.name', group: 'Regulation layer', label: 'Framework 4 name', default: 'Mental Capacity Act 2005' },
  { key: 'reg.f4.reg', group: 'Regulation layer', label: 'Framework 4 tag', default: 'MCA 2005' },
  { key: 'reg.f4.desc', group: 'Regulation layer', label: 'Framework 4 desc', multiline: true, default: 'Supporting residents who may lack capacity to make decisions, including best-interest processes.' },
  { key: 'reg.f5.name', group: 'Regulation layer', label: 'Framework 5 name', default: 'Safeguarding Adults' },
  { key: 'reg.f5.reg', group: 'Regulation layer', label: 'Framework 5 tag', default: 'Care Act 2014' },
  { key: 'reg.f5.desc', group: 'Regulation layer', label: 'Framework 5 desc', multiline: true, default: 'Legal duties to protect adults at risk from abuse, neglect, and exploitation.' },
  { key: 'reg.f6.name', group: 'Regulation layer', label: 'Framework 6 name', default: 'RIDDOR' },
  { key: 'reg.f6.reg', group: 'Regulation layer', label: 'Framework 6 tag', default: 'RIDDOR 2013' },
  { key: 'reg.f6.desc', group: 'Regulation layer', label: 'Framework 6 desc', multiline: true, default: 'When and how to report workplace injuries, diseases, and dangerous occurrences to the HSE.' },

  // Our services
  { key: 'services.label', group: 'Our services', label: 'Eyebrow', default: 'Our Services' },
  { key: 'services.h2', group: 'Our services', label: 'Heading', default: 'One platform for your whole care operation.' },
  { key: 'services.intro', group: 'Our services', label: 'Intro', multiline: true, default: 'CareStream is far more than policy access. Training, audits, CQC preparation and your staff handbook all run on the same engine, grounded in your own documents, and all in one hub your team signs into once.' },
  { key: 'services.s1.title', group: 'Our services', label: 'Service 1 title', default: 'Care Policies' },
  { key: 'services.s1.desc', group: 'Our services', label: 'Service 1 desc', multiline: true, default: 'Every policy answerable in seconds, in 60+ languages, with the source policy and version cited.' },
  { key: 'services.s2.title', group: 'Our services', label: 'Service 2 title', default: 'HR Policies' },
  { key: 'services.s2.desc', group: 'Our services', label: 'Service 2 desc', multiline: true, default: 'Your staff handbook on demand. Leave, pay and disciplinary questions answered in any language.' },
  { key: 'services.s3.title', group: 'Our services', label: 'Service 3 title', default: 'Staff Training' },
  { key: 'services.s3.desc', group: 'Our services', label: 'Service 3 desc', multiline: true, default: 'Modules built from your own policies, delivered in the hub, with renewal reminders and tracking.' },
  { key: 'services.s4.title', group: 'Our services', label: 'Service 4 title', default: 'Care Audits' },
  { key: 'services.s4.desc', group: 'Our services', label: 'Service 4 desc', multiline: true, default: 'Guided, structured audits that score each section and produce an inspection-ready report.' },
  { key: 'services.s5.title', group: 'Our services', label: 'Service 5 title', default: 'CQC & Compliance' },
  { key: 'services.s5.desc', group: 'Our services', label: 'Service 5 desc', multiline: true, default: 'Evidence that builds itself, plus regulation coverage showing exactly where your gaps are.' },
  { key: 'services.s6.title', group: 'Our services', label: 'Service 6 title', default: 'CQC Staff Questions' },
  { key: 'services.s6.desc', group: 'Our services', label: 'Service 6 desc', multiline: true, default: 'Inspector-style questions, answered by staff in their own words and scored by AI, with retry.' },
  { key: 'services.s7.title', group: 'Our services', label: 'Service 7 title', default: 'CQC Report Chat' },
  { key: 'services.s7.desc', group: 'Our services', label: 'Service 7 desc', multiline: true, default: 'Upload your inspection report and chat with it, cross-referenced against your own policies.' },
  { key: 'services.s8.title', group: 'Our services', label: 'Service 8 title', default: 'Business Continuity' },
  { key: 'services.s8.desc', group: 'Our services', label: 'Service 8 desc', multiline: true, default: 'Make your business continuity information instantly queryable by every member of staff, on any shift.' },

  // Care settings (one-line link under Our services)
  { key: 'settings.h2', group: 'Care settings', label: 'Lead-in line', default: 'Built for every care setting' },
  { key: 'settings.cta', group: 'Care settings', label: 'CTA link', default: 'View all settings we serve' },

  // Multilingual (60+ languages grid)
  { key: 'knowledge.ml.label', group: 'Multilingual', label: 'Eyebrow', default: '60+ Languages' },
  { key: 'knowledge.ml.h3.pre', group: 'Multilingual', label: 'Heading — lead', default: 'Ask in any language.' },
  { key: 'knowledge.ml.h3.emphasis', group: 'Multilingual', label: 'Heading — emphasis', default: 'Answered in the same language.' },
  { key: 'knowledge.ml.sub', group: 'Multilingual', label: 'Sub-text', default: 'Language is detected automatically. No selection required.' },

  // Voice callout (inside the multilingual section)
  { key: 'voice.h2.pre', group: 'Voice callout', label: 'Heading — lead', default: 'Speak your question.' },
  { key: 'voice.h2.emphasis', group: 'Voice callout', label: 'Heading — emphasis', default: 'Hear your answer.' },
  { key: 'voice.body', group: 'Voice callout', label: 'Body', multiline: true, default: 'Not everyone types quickly in their second language. In the hub, staff can ask policy questions by speaking instead of typing, hands-free, mid-task, in their own language, and have the answer read back to them.' },

  // Trust
  { key: 'trust.label', group: 'Trust', label: 'Eyebrow', default: 'Why It Can Be Trusted' },
  { key: 'trust.h2.pre', group: 'Trust', label: 'Heading — lead', default: "The AI doesn't make things up." },
  { key: 'trust.h2.emphasis', group: 'Trust', label: 'Heading — emphasis', default: "It can't." },
  { key: 'trust.body', group: 'Trust', label: 'Body', rich: true, default: "CareStreamAI only answers from your uploaded, approved documents. Not the internet. Not general AI knowledge. Not another organisation's policies. If your policy doesn't say it, CareStreamAI won't say it." },
  { key: 'trust.uses.heading', group: 'Trust', label: 'Uses heading', default: 'What it uses' },
  { key: 'trust.uses.i1', group: 'Trust', label: 'Uses item 1', default: 'Your uploaded policies' },
  { key: 'trust.uses.i2', group: 'Trust', label: 'Uses item 2', default: 'Your staff handbook' },
  { key: 'trust.uses.i3', group: 'Trust', label: 'Uses item 3', default: 'Your approved regulatory guidance' },
  { key: 'trust.uses.i4', group: 'Trust', label: 'Uses item 4', default: 'Exact sections relevant to each query' },
  { key: 'trust.never.heading', group: 'Trust', label: 'Never-uses heading', default: 'What it never uses' },
  { key: 'trust.never.i1', group: 'Trust', label: 'Never item 1', default: 'The internet' },
  { key: 'trust.never.i2', group: 'Trust', label: 'Never item 2', default: "Other organisations' policies" },
  { key: 'trust.never.i3', group: 'Trust', label: 'Never item 3', default: 'General AI training data' },
  { key: 'trust.never.i4', group: 'Trust', label: 'Never item 4', default: 'Anything outside your documents' },
  { key: 'trust.cta', group: 'Trust', label: 'CTA link', default: 'How we keep your data private and secure' },

  // Operate at scale
  { key: 'scale.label', group: 'Operate at scale', label: 'Eyebrow', default: 'Enterprise Ready' },
  { key: 'scale.h2', group: 'Operate at scale', label: 'Heading', default: 'Designed to operate at scale' },
  { key: 'scale.intro', group: 'Operate at scale', label: 'Intro', multiline: true, default: 'Everything a group operator needs to run consistent, compliant care across multiple sites, without the complexity of enterprise software.' },
  { key: 'scale.point1', group: 'Operate at scale', label: 'List item 1', default: 'Clear total cost of ownership across your group' },
  { key: 'scale.point2', group: 'Operate at scale', label: 'List item 2', default: 'Lower cost per service user as you grow' },
  { key: 'scale.point3', group: 'Operate at scale', label: 'List item 3', default: 'One policy library, consistently applied across every site' },
  { key: 'scale.point4', group: 'Operate at scale', label: 'List item 4', default: 'Multilingual access as standard, no extra configuration' },
  { key: 'scale.point5', group: 'Operate at scale', label: 'List item 5', default: 'Group-level CQC Readiness Reports, generated automatically' },
  { key: 'scale.point6', group: 'Operate at scale', label: 'List item 6', default: 'A partner that listens and scales with you' },
  { key: 'scale.cta', group: 'Operate at scale', label: 'CTA', default: 'Book a demo with our group team' },

  // Pricing
  { key: 'pricing.label', group: 'Pricing', label: 'Eyebrow', default: 'Pricing' },
  { key: 'pricing.h2', group: 'Pricing', label: 'Heading', default: 'Simple, transparent pricing.' },
  { key: 'pricing.sub', group: 'Pricing', label: 'Sub-text', default: 'No hidden costs. No per-user fees. No surprises.' },
  { key: 'pricing.starter.name', group: 'Pricing', label: 'Starter name', default: 'Starter' },
  { key: 'pricing.starter.price', group: 'Pricing', label: 'Starter price', default: '£85' },
  { key: 'pricing.starter.per', group: 'Pricing', label: 'Starter price suffix', default: '/month' },
  { key: 'pricing.starter.note', group: 'Pricing', label: 'Starter note', default: 'Per home. Unlimited staff users.' },
  { key: 'pricing.starter.f1', group: 'Pricing', label: 'Starter feature 1', default: 'Policy library (up to 25 policies)' },
  { key: 'pricing.starter.f2', group: 'Pricing', label: 'Starter feature 2', default: 'Hub and email access for all staff' },
  { key: 'pricing.starter.f3', group: 'Pricing', label: 'Starter feature 3', default: '60+ language support' },
  { key: 'pricing.starter.f4', group: 'Pricing', label: 'Starter feature 4', default: '500 queries/month' },
  { key: 'pricing.starter.f5', group: 'Pricing', label: 'Starter feature 5', default: 'Full audit trail' },
  { key: 'pricing.starter.f6', group: 'Pricing', label: 'Starter feature 6', default: 'Basic analytics' },
  { key: 'pricing.starter.cta', group: 'Pricing', label: 'Starter CTA', default: 'Start Free Trial' },
  { key: 'pricing.pro.badge', group: 'Pricing', label: 'Professional badge', default: 'Most popular' },
  { key: 'pricing.pro.name', group: 'Pricing', label: 'Professional name', default: 'Professional' },
  { key: 'pricing.pro.price', group: 'Pricing', label: 'Professional price', default: '£230' },
  { key: 'pricing.pro.per', group: 'Pricing', label: 'Professional price suffix', default: '/month' },
  { key: 'pricing.pro.note', group: 'Pricing', label: 'Professional note', default: 'Per home. Everything in Starter, plus:' },
  { key: 'pricing.pro.f1', group: 'Pricing', label: 'Professional feature 1', default: 'Unlimited policies' },
  { key: 'pricing.pro.f2', group: 'Pricing', label: 'Professional feature 2', default: '5,000 queries/month' },
  { key: 'pricing.pro.f3', group: 'Pricing', label: 'Professional feature 3', default: 'CQC Readiness Report PDF' },
  { key: 'pricing.pro.f4', group: 'Pricing', label: 'Professional feature 4', default: 'Policy gap detection' },
  { key: 'pricing.pro.f5', group: 'Pricing', label: 'Professional feature 5', default: 'Language analytics' },
  { key: 'pricing.pro.f6', group: 'Pricing', label: 'Professional feature 6', default: 'Staff engagement by individual' },
  { key: 'pricing.pro.cta', group: 'Pricing', label: 'Professional CTA', default: 'Start Free Trial' },
  { key: 'pricing.ent.badge', group: 'Pricing', label: 'Enterprise badge', default: 'Everything included' },
  { key: 'pricing.ent.name', group: 'Pricing', label: 'Enterprise name', default: 'Enterprise' },
  { key: 'pricing.ent.price', group: 'Pricing', label: 'Enterprise price', default: '£385' },
  { key: 'pricing.ent.per', group: 'Pricing', label: 'Enterprise price suffix', default: '/month' },
  { key: 'pricing.ent.note', group: 'Pricing', label: 'Enterprise note', default: 'Per home. Everything in Professional, plus:' },
  { key: 'pricing.ent.f1', group: 'Pricing', label: 'Enterprise feature 1', default: 'Unlimited annual training allocations' },
  { key: 'pricing.ent.f2', group: 'Pricing', label: 'Enterprise feature 2', default: 'Build your own audits' },
  { key: 'pricing.ent.f3', group: 'Pricing', label: 'Enterprise feature 3', default: 'Training effectiveness analytics' },
  { key: 'pricing.ent.f4', group: 'Pricing', label: 'Enterprise feature 4', default: 'Multi-site group console' },
  { key: 'pricing.ent.f5', group: 'Pricing', label: 'Enterprise feature 5', default: 'Workforce compliance register' },
  { key: 'pricing.ent.f6', group: 'Pricing', label: 'Enterprise feature 6', default: 'Priority support' },
  { key: 'pricing.ent.cta', group: 'Pricing', label: 'Enterprise CTA', default: 'Start Free Trial' },
  { key: 'pricing.cta', group: 'Pricing', label: 'Compare CTA', default: 'Full pricing and feature comparison' },

  // Free trial band
  { key: 'freetrial.eyebrow', group: 'Free trial band', label: 'Eyebrow', default: 'A risk free way to get started' },
  { key: 'freetrial.h2.pre', group: 'Free trial band', label: 'Heading — lead', default: 'CareStream is' },
  { key: 'freetrial.h2.highlight', group: 'Free trial band', label: 'Heading — highlight', default: 'free for 14 days' },
  { key: 'freetrial.h2.post', group: 'Free trial band', label: 'Heading — trailing', default: 'for your whole team.' },
  { key: 'freetrial.cta', group: 'Free trial band', label: 'CTA', default: 'Start Your Free Trial' },
  { key: 'freetrial.sub', group: 'Free trial band', label: 'Sub-text', default: 'Full access for 14 days. No charge until day 14 — cancel anytime.' },

  // Final CTA
  { key: 'finalcta.eyebrow', group: 'Final CTA', label: 'Eyebrow', default: 'Get Started' },
  { key: 'finalcta.h2', group: 'Final CTA', label: 'Heading', default: 'Give your whole team the policy access they deserve.' },
  { key: 'finalcta.sub', group: 'Final CTA', label: 'Sub-text', default: '14-day free trial. No charge until day 14. Set up in under an hour.' },
  { key: 'finalcta.primary', group: 'Final CTA', label: 'Primary CTA', default: 'Book a Free Demo' },
  { key: 'finalcta.secondary', group: 'Final CTA', label: 'Secondary CTA', default: 'Start Free Trial' },
]
