import type { SlotDef } from './types'

// Editable copy for the homepage ("/"). Defaults are the current live copy; editing
// a slot in the platform (Main site pages → /) overrides it without touching design.
// Illustrative mockup content (fake chat bubbles, sample dashboards, device chrome,
// decorative image-overlay badges) and shared data arrays (language pills, logo
// marquee, imported settings/blog/FAQ) are intentionally NOT slotted.
export const HOME_SLOTS: SlotDef[] = [
  // Hero
  { key: 'hero.h1.lead', group: 'Hero', label: 'Headline — lead word', default: 'Your' },
  { key: 'hero.h1.mid', group: 'Hero', label: 'Headline — after animated word', default: 'are written in English.' },
  { key: 'hero.h1.emphasis', group: 'Hero', label: 'Headline — emphasis', default: "Your workforce isn't." },
  { key: 'hero.sub', group: 'Hero', label: 'Sub-paragraph', multiline: true, default: 'CareStream gives every member of your team instant, accurate answers from your own policies, training, audits and CQC tools, in the language they think in. Powered by your documents. Never the internet.' },
  { key: 'hero.cta.primary', group: 'Hero', label: 'Primary CTA', default: 'Book a Free Demo' },
  { key: 'hero.cta.secondary', group: 'Hero', label: 'Secondary CTA', default: 'See how it works' },
  { key: 'hero.trust1', group: 'Hero', label: 'Trust chip 1', default: '14-day free trial' },
  { key: 'hero.trust2', group: 'Hero', label: 'Trust chip 2', default: 'No charge until day 14' },
  { key: 'hero.trust3', group: 'Hero', label: 'Trust chip 3', default: 'Set up in under an hour' },
  { key: 'hero.trust4', group: 'Hero', label: 'Trust chip 4', default: 'GDPR Compliant' },

  // Stats strip
  { key: 'stats.s1.num', group: 'Stats strip', label: 'Stat 1 figure', default: '30%+' },
  { key: 'stats.s1.label', group: 'Stats strip', label: 'Stat 1 label', default: 'UK care workers born outside the UK' },
  { key: 'stats.s2.num', group: 'Stats strip', label: 'Stat 2 figure', default: '150+' },
  { key: 'stats.s2.label', group: 'Stats strip', label: 'Stat 2 label', default: 'Languages spoken in UK care settings' },
  { key: 'stats.s3.num', group: 'Stats strip', label: 'Stat 3 figure', default: '1 in 3' },
  { key: 'stats.s3.label', group: 'Stats strip', label: 'Stat 3 label', default: 'Night-shift policy questions go unanswered' },
  { key: 'stats.s4.num', group: 'Stats strip', label: 'Stat 4 figure', default: '£85' },
  { key: 'stats.s4.label', group: 'Stats strip', label: 'Stat 4 label', default: 'per month, less than one agency shift hour' },

  // The Problem
  { key: 'problem.label', group: 'The Problem', label: 'Eyebrow', default: 'The Challenge in Care' },
  { key: 'problem.h2.pre', group: 'The Problem', label: 'Heading — lead', default: 'The language gap in care is a' },
  { key: 'problem.h2.emphasis', group: 'The Problem', label: 'Heading — emphasis', default: 'safety gap.' },
  { key: 'problem.p1', group: 'The Problem', label: 'Paragraph 1', rich: true, default: 'Over 30% of the UK care workforce was born outside the United Kingdom. In many homes, the majority of the care team speaks English as a second language.' },
  { key: 'problem.p2', group: 'The Problem', label: 'Paragraph 2', rich: true, default: 'Yet every policy system operates entirely in English, creating a persistent gap between what the policy says and what staff can confidently act on.' },
  { key: 'problem.p3', group: 'The Problem', label: 'Paragraph 3', rich: true, default: 'At 3am, during an incident, in the first weeks of a new job, that gap leads to hesitation, misinterpretation, and decisions made without the guidance that should have been available.' },
  { key: 'problem.card1.title', group: 'The Problem', label: 'Card 1 title', default: 'Policies in English only' },
  { key: 'problem.card1.body', group: 'The Problem', label: 'Card 1 body', multiline: true, default: 'Your carefully written procedures are inaccessible to a large portion of the people they are designed to protect.' },
  { key: 'problem.card2.title', group: 'The Problem', label: 'Card 2 title', default: 'No support at 3am' },
  { key: 'problem.card2.body', group: 'The Problem', label: 'Card 2 body', multiline: true, default: 'Night staff face clinical uncertainty without a manager present, and no reliable way to find the right answer fast.' },
  { key: 'problem.card3.title', group: 'The Problem', label: 'Card 3 title', default: 'Compliance gaps at inspection' },
  { key: 'problem.card3.body', group: 'The Problem', label: 'Card 3 body', multiline: true, default: "CQC expects evidence that staff actively use and understand your policies. A folder on a shelf isn't evidence." },

  // Diverse workforce
  { key: 'diverse.label', group: 'Diverse workforce', label: 'Eyebrow', default: 'A diverse workforce' },
  { key: 'diverse.h2.pre', group: 'Diverse workforce', label: 'Heading — lead', default: 'Everything you need to manage a' },
  { key: 'diverse.h2.emphasis', group: 'Diverse workforce', label: 'Heading — emphasis', default: 'diverse workforce' },
  { key: 'diverse.p1', group: 'Diverse workforce', label: 'Paragraph 1', rich: true, default: 'Care teams are more diverse than ever. Overseas recruits, bank staff and night-shift workers all need to understand your policies, training and procedures, and many of them think in a language other than English.' },
  { key: 'diverse.p2', group: 'Diverse workforce', label: 'Paragraph 2', rich: true, default: 'CareStream gives every member of your team instant, cited answers from your own documents, in over 60 languages, on any device. Policies, training, audits and CQC preparation all run on one hub your team signs into once, so everyone stays confident, capable and compliant.' },

  // Care settings
  { key: 'settings.label', group: 'Care settings', label: 'Eyebrow', default: 'Who We Serve' },
  { key: 'settings.h2', group: 'Care settings', label: 'Heading', default: 'Built for every care setting' },
  { key: 'settings.cta', group: 'Care settings', label: 'CTA link', default: 'View all settings we serve' },

  // Hub and training
  { key: 'hubtrain.label', group: 'Hub and training', label: 'Eyebrow', default: 'Explore CareStream' },
  { key: 'hubtrain.h2', group: 'Hub and training', label: 'Heading', default: 'Two ways your whole team gets more from your policies' },
  { key: 'hubtrain.intro', group: 'Hub and training', label: 'Intro', multiline: true, default: 'Everything runs on one engine, grounded in your own documents. Turn your policies into training your team completes, and give every member of staff a single hub for policies, audits and CQC preparation.' },
  { key: 'hubtrain.training.eyebrow', group: 'Hub and training', label: 'Training eyebrow', default: 'CareStream Training' },
  { key: 'hubtrain.training.title', group: 'Hub and training', label: 'Training title', default: 'Training modules built from your own policies' },
  { key: 'hubtrain.training.body', group: 'Hub and training', label: 'Training body', multiline: true, default: 'Turn your policies into staff training delivered in the hub, in any language, with renewal reminders and completion tracking that becomes inspection-ready CQC evidence.' },
  { key: 'hubtrain.training.cta', group: 'Hub and training', label: 'Training CTA', default: 'Learn more about training' },
  { key: 'hubtrain.hub.eyebrow', group: 'Hub and training', label: 'Hub eyebrow', default: 'CareStream Hub' },
  { key: 'hubtrain.hub.title', group: 'Hub and training', label: 'Hub title', default: 'Policies, audits and CQC in one hub' },
  { key: 'hubtrain.hub.body', group: 'Hub and training', label: 'Hub body', multiline: true, default: 'Every policy, your staff handbook, training, audits and CQC preparation, answerable in seconds from your own documents. One hub your whole team signs into once, on any device.' },
  { key: 'hubtrain.hub.cta', group: 'Hub and training', label: 'Hub CTA', default: 'Explore the hub' },

  // Policy burden band
  { key: 'burden.eyebrow', group: 'Policy burden band', label: 'Eyebrow', default: 'Hundreds of policies to manage' },
  { key: 'burden.h2.pre', group: 'Policy burden band', label: 'Heading — lead', default: 'The average care setting must keep' },
  { key: 'burden.h2.highlight', group: 'Policy burden band', label: 'Heading — highlight', default: 'over 200 policies' },
  { key: 'burden.h2.post', group: 'Policy burden band', label: 'Heading — trailing', default: 'current. Your team can find any of them in seconds.' },
  { key: 'burden.cta', group: 'Policy burden band', label: 'CTA', default: 'See how CareStream helps' },
  { key: 'burden.sub', group: 'Policy burden band', label: 'Sub-text', default: 'In any language, on any device, grounded in your own documents.' },

  // Value proposition
  { key: 'value.label', group: 'Value proposition', label: 'Eyebrow', default: 'Why CareStreamAI' },
  { key: 'value.h2.pre', group: 'Value proposition', label: 'Heading — lead', default: 'Built for care providers who want' },
  { key: 'value.h2.highlight', group: 'Value proposition', label: 'Heading — highlight', default: 'confident staff' },
  { key: 'value.h2.post', group: 'Value proposition', label: 'Heading — trailing', default: 'and watertight compliance' },
  { key: 'value.p1.title', group: 'Value proposition', label: 'Point 1 title', default: 'Policies your whole team can actually use' },
  { key: 'value.p1.body', group: 'Value proposition', label: 'Point 1 body', multiline: true, default: 'From clinical procedures to safeguarding, your library is accessible in any language, at any hour, on any device, with no app to download and no training required.' },
  { key: 'value.p2.title', group: 'Value proposition', label: 'Point 2 title', default: 'Compliance evidence that builds itself' },
  { key: 'value.p2.body', group: 'Value proposition', label: 'Point 2 body', multiline: true, default: 'Every query is logged. Your CQC Readiness Report is compiled automatically from the audit trail, policy access, language activity, version history, staff engagement.' },
  { key: 'value.p3.title', group: 'Value proposition', label: 'Point 3 title', default: 'Up and running in under an hour' },
  { key: 'value.p3.body', group: 'Value proposition', label: 'Point 3 body', multiline: true, default: 'Upload your policies, add your staff email addresses, and you are live. No integration project, no IT department, no months-long rollout.' },

  // Why choose CareStream
  { key: 'whychoose.h2', group: 'Why choose CareStream', label: 'Heading', default: 'Why care providers choose CareStreamAI' },
  { key: 'whychoose.intro', group: 'Why choose CareStream', label: 'Intro', multiline: true, default: 'At CareStream, we do not just answer questions. We become a trusted extension of your team, combining your own documents with smart technology to help you manage policies, training and CQC readiness with confidence.' },
  { key: 'whychoose.c1.title', group: 'Why choose CareStream', label: 'Column 1 title', default: 'Trusted expertise' },
  { key: 'whychoose.c1.body', group: 'Why choose CareStream', label: 'Column 1 body', multiline: true, default: 'Policies, training, audits and CQC preparation, brought together with one trusted partner built for the care sector.' },
  { key: 'whychoose.c2.title', group: 'Why choose CareStream', label: 'Column 2 title', default: 'Personal support' },
  { key: 'whychoose.c2.body', group: 'Why choose CareStream', label: 'Column 2 body', multiline: true, default: 'Work with a team that understands your service, your staff and your goals, and is there when you need them.' },
  { key: 'whychoose.c3.title', group: 'Why choose CareStream', label: 'Column 3 title', default: 'Complete confidence' },
  { key: 'whychoose.c3.body', group: 'Why choose CareStream', label: 'Column 3 body', multiline: true, default: 'From day-to-day questions to inspection day, we help you stay compliant, reduce risk and make informed decisions.' },

  // The solution
  { key: 'solution.label', group: 'The solution', label: 'Eyebrow', default: 'How CareStreamAI Helps' },
  { key: 'solution.h2', group: 'The solution', label: 'Heading', default: 'Policy access that works for your whole team.' },
  { key: 'solution.sub', group: 'The solution', label: 'Sub-text', default: 'Not just the ones who speak English.' },
  { key: 'solution.c1.title', group: 'The solution', label: 'Column 1 title', default: 'Ask in any language' },
  { key: 'solution.c1.body', group: 'The solution', label: 'Column 1 body', multiline: true, default: 'Staff ask about your policies in any of 60+ languages in the hub or by email. Language is detected automatically, no setup, no menus, no extra cost.' },
  { key: 'solution.c2.title', group: 'The solution', label: 'Column 2 title', default: 'Answer in any language' },
  { key: 'solution.c2.body', group: 'The solution', label: 'Column 2 body', multiline: true, default: 'Responses are generated in the language the question was asked in, drawn exclusively from your own approved policies. Under 30 seconds. Cited.' },
  { key: 'solution.c3.title', group: 'The solution', label: 'Column 3 title', default: 'Evidence for inspection' },
  { key: 'solution.c3.body', group: 'The solution', label: 'Column 3 body', multiline: true, default: 'Every query is logged. The CQC Readiness Report turns your audit trail into inspection evidence, showing equitable policy access across your multilingual team.' },

  // Our services
  { key: 'services.label', group: 'Our services', label: 'Eyebrow', default: 'Our Services' },
  { key: 'services.h2', group: 'Our services', label: 'Heading', default: 'One platform for your whole care operation.' },
  { key: 'services.intro', group: 'Our services', label: 'Intro', multiline: true, default: 'CareStream is far more than policy access. Training, audits, CQC preparation and your staff handbook all run on the same engine, grounded in your own documents, and all in one hub your team signs into once.' },
  { key: 'services.s1.title', group: 'Our services', label: 'Service 1 title', default: 'Care Policies' },
  { key: 'services.s1.desc', group: 'Our services', label: 'Service 1 desc', multiline: true, default: 'Every policy answerable in seconds, in 60+ languages, with the source policy and version cited.' },
  { key: 'services.s2.title', group: 'Our services', label: 'Service 2 title', default: 'HR Policies' },
  { key: 'services.s2.desc', group: 'Our services', label: 'Service 2 desc', multiline: true, default: 'Your staff handbook on demand. Leave, pay and disciplinary questions answered in any language.' },
  { key: 'services.s3.title', group: 'Our services', label: 'Service 3 title', default: 'Staff Training' },
  { key: 'services.s3.desc', group: 'Our services', label: 'Service 3 desc', multiline: true, default: 'Modules built from your own policies, delivered in the hub, with renewal reminders and tracking.' },
  { key: 'services.s4.title', group: 'Our services', label: 'Service 4 title', default: 'Care Audits' },
  { key: 'services.s4.desc', group: 'Our services', label: 'Service 4 desc', multiline: true, default: 'Guided, structured audits that score each section and produce an inspection-ready report.' },
  { key: 'services.s5.title', group: 'Our services', label: 'Service 5 title', default: 'CQC & Compliance' },
  { key: 'services.s5.desc', group: 'Our services', label: 'Service 5 desc', multiline: true, default: 'Evidence that builds itself, plus regulation coverage showing exactly where your gaps are.' },
  { key: 'services.s6.title', group: 'Our services', label: 'Service 6 title', default: 'CQC Staff Questions' },
  { key: 'services.s6.desc', group: 'Our services', label: 'Service 6 desc', multiline: true, default: 'Inspector-style questions, answered by staff in their own words and scored by AI, with retry.' },
  { key: 'services.s7.title', group: 'Our services', label: 'Service 7 title', default: 'CQC Report Chat' },
  { key: 'services.s7.desc', group: 'Our services', label: 'Service 7 desc', multiline: true, default: 'Upload your inspection report and chat with it, cross-referenced against your own policies.' },
  { key: 'services.s8.title', group: 'Our services', label: 'Service 8 title', default: 'Business Continuity' },
  { key: 'services.s8.desc', group: 'Our services', label: 'Service 8 desc', multiline: true, default: 'Make your business continuity information instantly queryable by every member of staff, on any shift.' },

  // Group level
  { key: 'group.label', group: 'Group level', label: 'Eyebrow', default: 'Group Providers' },
  { key: 'group.h2', group: 'Group level', label: 'Heading', default: 'Built for group-level care delivery' },
  { key: 'group.body', group: 'Group level', label: 'Body', rich: true, default: 'Real-time policy visibility across every service, for multi-site providers. With a single policy library and centralised oversight, group leaders can standardise procedures, spot compliance gaps earlier, and drive consistent outcomes across every location, without adding headcount.' },

  // Free trial band
  { key: 'freetrial.eyebrow', group: 'Free trial band', label: 'Eyebrow', default: 'A risk free way to get started' },
  { key: 'freetrial.h2.pre', group: 'Free trial band', label: 'Heading — lead', default: 'CareStream is' },
  { key: 'freetrial.h2.highlight', group: 'Free trial band', label: 'Heading — highlight', default: 'free for 14 days' },
  { key: 'freetrial.h2.post', group: 'Free trial band', label: 'Heading — trailing', default: 'for your whole team.' },
  { key: 'freetrial.cta', group: 'Free trial band', label: 'CTA', default: 'Start Your Free Trial' },
  { key: 'freetrial.sub', group: 'Free trial band', label: 'Sub-text', default: 'Full access for 14 days. No charge until day 14 — cancel anytime.' },

  // Operate at scale
  { key: 'scale.label', group: 'Operate at scale', label: 'Eyebrow', default: 'Enterprise Ready' },
  { key: 'scale.h2', group: 'Operate at scale', label: 'Heading', default: 'Designed to operate at scale' },
  { key: 'scale.intro', group: 'Operate at scale', label: 'Intro', multiline: true, default: 'Everything a group operator needs to run consistent, compliant care across multiple sites, without the complexity of enterprise software.' },
  { key: 'scale.point1', group: 'Operate at scale', label: 'List item 1', default: 'Clear total cost of ownership across your group' },
  { key: 'scale.point2', group: 'Operate at scale', label: 'List item 2', default: 'Lower cost per service user as you grow' },
  { key: 'scale.point3', group: 'Operate at scale', label: 'List item 3', default: 'One policy library, consistently applied across every site' },
  { key: 'scale.point4', group: 'Operate at scale', label: 'List item 4', default: 'Multilingual access as standard, no extra configuration' },
  { key: 'scale.point5', group: 'Operate at scale', label: 'List item 5', default: 'Group-level CQC Readiness Reports, generated automatically' },
  { key: 'scale.point6', group: 'Operate at scale', label: 'List item 6', default: 'A partner that listens and scales with you' },
  { key: 'scale.cta', group: 'Operate at scale', label: 'CTA', default: 'Book a demo with our group team' },

  // How it works
  { key: 'howitworks.label', group: 'How it works', label: 'Eyebrow', default: 'The Process' },
  { key: 'howitworks.h2.line1', group: 'How it works', label: 'Heading line 1', default: 'Up and running in hours.' },
  { key: 'howitworks.h2.line2', group: 'How it works', label: 'Heading line 2', default: 'Not months.' },
  { key: 'howitworks.step1.title', group: 'How it works', label: 'Step 1 title', default: 'Upload your policies' },
  { key: 'howitworks.step1.body', group: 'How it works', label: 'Step 1 body', multiline: true, default: 'Upload your policy library and staff handbook via the admin dashboard. PDF, Word, or plain text. CareStreamAI processes them and builds your private, searchable library.' },
  { key: 'howitworks.step2.title', group: 'How it works', label: 'Step 2 title', default: 'Staff start asking' },
  { key: 'howitworks.step2.body', group: 'How it works', label: 'Step 2 body', multiline: true, default: 'Your team sends questions via email or the web chat portal, in any language. CareStreamAI identifies the language automatically and retrieves the most relevant policy content.' },
  { key: 'howitworks.step3.title', group: 'How it works', label: 'Step 3 title', default: 'Instant, grounded answers' },
  { key: 'howitworks.step3.body', group: 'How it works', label: 'Step 3 body', multiline: true, default: 'Responses arrive in under 30 seconds, in the language the question was asked, drawn only from your approved documents. Never the internet.' },
  { key: 'howitworks.step4.title', group: 'How it works', label: 'Step 4 title', default: 'Your compliance evidence builds' },
  { key: 'howitworks.step4.body', group: 'How it works', label: 'Step 4 body', multiline: true, default: 'Every query is logged. Your CQC Readiness Report builds automatically, policy access, language activity, staff engagement, version history.' },
  { key: 'howitworks.cta', group: 'How it works', label: 'CTA', default: 'See the full walkthrough' },

  // Trust
  { key: 'trust.label', group: 'Trust', label: 'Eyebrow', default: 'Why It Can Be Trusted' },
  { key: 'trust.h2.pre', group: 'Trust', label: 'Heading — lead', default: "The AI doesn't make things up." },
  { key: 'trust.h2.emphasis', group: 'Trust', label: 'Heading — emphasis', default: "It can't." },
  { key: 'trust.body', group: 'Trust', label: 'Body', rich: true, default: "CareStreamAI only answers from your uploaded, approved documents. Not the internet. Not general AI knowledge. Not another organisation's policies. If your policy doesn't say it, CareStreamAI won't say it." },
  { key: 'trust.uses.heading', group: 'Trust', label: 'Uses heading', default: 'What it uses' },
  { key: 'trust.uses.i1', group: 'Trust', label: 'Uses item 1', default: 'Your uploaded policies' },
  { key: 'trust.uses.i2', group: 'Trust', label: 'Uses item 2', default: 'Your staff handbook' },
  { key: 'trust.uses.i3', group: 'Trust', label: 'Uses item 3', default: 'Your approved regulatory guidance' },
  { key: 'trust.uses.i4', group: 'Trust', label: 'Uses item 4', default: 'Exact sections relevant to each query' },
  { key: 'trust.never.heading', group: 'Trust', label: 'Never-uses heading', default: 'What it never uses' },
  { key: 'trust.never.i1', group: 'Trust', label: 'Never item 1', default: 'The internet' },
  { key: 'trust.never.i2', group: 'Trust', label: 'Never item 2', default: "Other organisations' policies" },
  { key: 'trust.never.i3', group: 'Trust', label: 'Never item 3', default: 'General AI training data' },
  { key: 'trust.never.i4', group: 'Trust', label: 'Never item 4', default: 'Anything outside your documents' },
  { key: 'trust.cta', group: 'Trust', label: 'CTA link', default: 'How we keep your data private and secure' },

  // Care sector AI
  { key: 'caresectorai.badge', group: 'Care sector AI', label: 'Badge', default: 'New' },
  { key: 'caresectorai.h2', group: 'Care sector AI', label: 'Heading', default: 'Finally, AI that works for the Care Sector' },

  // Regulation layer
  { key: 'reg.label', group: 'Regulation layer', label: 'Eyebrow', default: 'Regulatory Intelligence' },
  { key: 'reg.h2.pre', group: 'Regulation layer', label: 'Heading — lead', default: 'Your policies and the law,' },
  { key: 'reg.h2.emphasis', group: 'Regulation layer', label: 'Heading — emphasis', default: 'answered together.' },
  { key: 'reg.intro', group: 'Regulation layer', label: 'Intro', rich: true, default: 'The UK care regulations and statutory frameworks that matter to a care service are loaded into CareStream and kept up to date. When a staff member asks something that touches both your internal policy and an external framework, the response explains how the two interact, not just what your policy says in isolation.' },
  { key: 'reg.pill', group: 'Regulation layer', label: 'Pill text', default: 'UK regulations, loaded and kept up to date' },
  { key: 'reg.frameworks.label', group: 'Regulation layer', label: 'Frameworks label', default: 'A selection of frameworks included' },
  { key: 'reg.frameworks.badge', group: 'Regulation layer', label: 'Frameworks badge', default: 'and more' },
  { key: 'reg.f1.name', group: 'Regulation layer', label: 'Framework 1 name', default: 'CQC Fundamental Standards' },
  { key: 'reg.f1.reg', group: 'Regulation layer', label: 'Framework 1 tag', default: 'Reg 12, 17 & 19' },
  { key: 'reg.f1.desc', group: 'Regulation layer', label: 'Framework 1 desc', multiline: true, default: 'The baseline requirements every registered service must meet: safe care, governance, and fit and proper persons.' },
  { key: 'reg.f2.name', group: 'Regulation layer', label: 'Framework 2 name', default: 'Health & Safety at Work Act 1974' },
  { key: 'reg.f2.reg', group: 'Regulation layer', label: 'Framework 2 tag', default: 'HSWA 1974' },
  { key: 'reg.f2.desc', group: 'Regulation layer', label: 'Framework 2 desc', multiline: true, default: 'Employer and employee duties around risk assessment, safe systems of work, and incident reporting.' },
  { key: 'reg.f3.name', group: 'Regulation layer', label: 'Framework 3 name', default: 'GDPR & Data Protection Act 2018' },
  { key: 'reg.f3.reg', group: 'Regulation layer', label: 'Framework 3 tag', default: 'UK GDPR' },
  { key: 'reg.f3.desc', group: 'Regulation layer', label: 'Framework 3 desc', multiline: true, default: 'How resident and staff data must be collected, stored, shared, and protected.' },
  { key: 'reg.f4.name', group: 'Regulation layer', label: 'Framework 4 name', default: 'Mental Capacity Act 2005' },
  { key: 'reg.f4.reg', group: 'Regulation layer', label: 'Framework 4 tag', default: 'MCA 2005' },
  { key: 'reg.f4.desc', group: 'Regulation layer', label: 'Framework 4 desc', multiline: true, default: 'Supporting residents who may lack capacity to make decisions, including best-interest processes.' },
  { key: 'reg.f5.name', group: 'Regulation layer', label: 'Framework 5 name', default: 'Safeguarding Adults' },
  { key: 'reg.f5.reg', group: 'Regulation layer', label: 'Framework 5 tag', default: 'Care Act 2014' },
  { key: 'reg.f5.desc', group: 'Regulation layer', label: 'Framework 5 desc', multiline: true, default: 'Legal duties to protect adults at risk from abuse, neglect, and exploitation.' },
  { key: 'reg.f6.name', group: 'Regulation layer', label: 'Framework 6 name', default: 'RIDDOR' },
  { key: 'reg.f6.reg', group: 'Regulation layer', label: 'Framework 6 tag', default: 'RIDDOR 2013' },
  { key: 'reg.f6.desc', group: 'Regulation layer', label: 'Framework 6 desc', multiline: true, default: 'When and how to report workplace injuries, diseases, and dangerous occurrences to the HSE.' },

  // Home knowledge callout
  { key: 'knowledge.label', group: 'Home knowledge', label: 'Eyebrow', default: 'Your Home. Not a Generic Care Home.' },
  { key: 'knowledge.h2.pre', group: 'Home knowledge', label: 'Heading — lead', default: 'Not just what policies say.' },
  { key: 'knowledge.h2.emphasis', group: 'Home knowledge', label: 'Heading — emphasis', default: 'How your home works.' },
  { key: 'knowledge.intro', group: 'Home knowledge', label: 'Intro', rich: true, default: 'CareStreamAI extracts the specific facts from your documents, named individuals, schedules, exact local procedures, and makes them instantly answerable.' },
  { key: 'knowledge.col.question', group: 'Home knowledge', label: 'Table column — Question', default: 'Question' },
  { key: 'knowledge.col.generic', group: 'Home knowledge', label: 'Table column — Generic', default: 'Generic answer' },
  { key: 'knowledge.col.specific', group: 'Home knowledge', label: 'Table column — CareStream', default: 'CareStreamAI answer' },
  { key: 'knowledge.ml.label', group: 'Home knowledge', label: 'Multilingual eyebrow', default: '60+ Languages' },
  { key: 'knowledge.ml.h3.pre', group: 'Home knowledge', label: 'Multilingual heading — lead', default: 'Ask in any language.' },
  { key: 'knowledge.ml.h3.emphasis', group: 'Home knowledge', label: 'Multilingual heading — emphasis', default: 'Answered in the same language.' },
  { key: 'knowledge.ml.sub', group: 'Home knowledge', label: 'Multilingual sub-text', default: 'Language is detected automatically. No selection required.' },

  // Features overview
  { key: 'features.label', group: 'Features overview', label: 'Eyebrow', default: 'What You Get' },
  { key: 'features.h2', group: 'Features overview', label: 'Heading', default: 'Nine reasons care teams love it.' },
  { key: 'features.f1.title', group: 'Features overview', label: 'Feature 1 title', default: '60+ language support' },
  { key: 'features.f1.desc', group: 'Features overview', label: 'Feature 1 desc', multiline: true, default: 'Staff ask in any language. Answers come back in the same language, automatically.' },
  { key: 'features.f2.title', group: 'Features overview', label: 'Feature 2 title', default: 'Hub and email' },
  { key: 'features.f2.desc', group: 'Features overview', label: 'Feature 2 desc', multiline: true, default: 'Use the hub in any browser or installed as an app, with a passwordless sign-in link. Email is there for anyone who prefers it.' },
  { key: 'features.f3.title', group: 'Features overview', label: 'Feature 3 title', default: 'Installable hub app' },
  { key: 'features.f3.desc', group: 'Features overview', label: 'Feature 3 desc', multiline: true, default: 'Staff install the hub on their phone and get push notifications for training and reminders. Nothing to learn.' },
  { key: 'features.f4.title', group: 'Features overview', label: 'Feature 4 title', default: 'Voice input' },
  { key: 'features.f4.desc', group: 'Features overview', label: 'Feature 4 desc', multiline: true, default: 'Speak a question in any language, hands-free, and hear the answer read back from your policies.' },
  { key: 'features.f5.title', group: 'Features overview', label: 'Feature 5 title', default: 'Your home, in detail' },
  { key: 'features.f5.desc', group: 'Features overview', label: 'Feature 5 desc', multiline: true, default: 'Knows your specific roles, schedules, and local procedures, not just generic policy text.' },
  { key: 'features.f6.title', group: 'Features overview', label: 'Feature 6 title', default: 'CQC Readiness Report' },
  { key: 'features.f6.desc', group: 'Features overview', label: 'Feature 6 desc', multiline: true, default: 'Inspection evidence generated automatically, covering access logs, language activity and staff engagement.' },
  { key: 'features.f7.title', group: 'Features overview', label: 'Feature 7 title', default: 'Policy gap detection' },
  { key: 'features.f7.desc', group: 'Features overview', label: 'Feature 7 desc', multiline: true, default: "Identify which questions your policies aren't answering, before CQC does." },
  { key: 'features.f8.title', group: 'Features overview', label: 'Feature 8 title', default: 'Staff handbook self-service' },
  { key: 'features.f8.desc', group: 'Features overview', label: 'Feature 8 desc', multiline: true, default: 'Turn your HR handbook into a 24/7 resource for leave, disciplinary, and employment questions.' },
  { key: 'features.f9.title', group: 'Features overview', label: 'Feature 9 title', default: 'Immutable audit trail' },
  { key: 'features.f9.desc', group: 'Features overview', label: 'Feature 9 desc', multiline: true, default: 'Every query logged, timestamped, and auditable. CQC-ready from day one.' },
  { key: 'features.cta', group: 'Features overview', label: 'CTA', default: 'See all features' },

  // Voice section
  { key: 'voice.label', group: 'Voice section', label: 'Eyebrow', default: 'Voice in the Hub' },
  { key: 'voice.h2.pre', group: 'Voice section', label: 'Heading — lead', default: 'Speak your question.' },
  { key: 'voice.h2.emphasis', group: 'Voice section', label: 'Heading — emphasis', default: 'Hear your answer.' },
  { key: 'voice.body', group: 'Voice section', label: 'Body', multiline: true, default: 'Not everyone types quickly in their second language. In the hub, staff can ask policy questions by speaking instead of typing, hands-free, mid-task, in their own language, and have the answer read back to them.' },
  { key: 'voice.i1.title', group: 'Voice section', label: 'Item 1 title', default: 'Speak in your own language' },
  { key: 'voice.i1.body', group: 'Voice section', label: 'Item 1 body', multiline: true, default: 'The hub turns speech into text as staff talk, in over 60 languages, so anyone who finds typing in English hard can simply ask out loud.' },
  { key: 'voice.i2.title', group: 'Voice section', label: 'Item 2 title', default: 'Listen to the answer' },
  { key: 'voice.i2.body', group: 'Voice section', label: 'Item 2 body', multiline: true, default: 'Every answer can be read aloud in the hub, so staff can keep their hands free on the care floor while they listen.' },
  { key: 'voice.i3.title', group: 'Voice section', label: 'Item 3 title', default: 'Same audit trail' },
  { key: 'voice.i3.body', group: 'Voice section', label: 'Item 3 body', multiline: true, default: 'Voice queries are logged identically to typed questions, capturing date, time, user and policy cited, all for your CQC records.' },

  // Policy gaps
  { key: 'gaps.label', group: 'Policy gaps', label: 'Eyebrow', default: 'Policy Gap Detection' },
  { key: 'gaps.h2.pre', group: 'Policy gaps', label: 'Heading — lead', default: 'Find your policy gaps' },
  { key: 'gaps.h2.emphasis', group: 'Policy gaps', label: 'Heading — emphasis', default: 'before CQC does.' },
  { key: 'gaps.body', group: 'Policy gaps', label: 'Body', multiline: true, default: "Every time a query can't be answered from your documents, it's flagged. Over time, patterns emerge. You can see exactly which questions your staff are asking that your policies don't yet address." },
  { key: 'gaps.point1', group: 'Policy gaps', label: 'List item 1', default: "See exactly which questions your policies can't answer." },
  { key: 'gaps.point2', group: 'Policy gaps', label: 'List item 2', default: 'Prioritised by query frequency, so you can fix the most common gaps first.' },
  { key: 'gaps.point3', group: 'Policy gaps', label: 'List item 3', default: "Monthly summary report, ready for your manager's review." },
  { key: 'gaps.point4', group: 'Policy gaps', label: 'List item 4', default: 'Included in your CQC Readiness Report as evidence of continuous improvement.' },
  { key: 'gaps.cta', group: 'Policy gaps', label: 'CTA', default: 'Learn more about Policy Gap Detection' },

  // Pricing
  { key: 'pricing.label', group: 'Pricing', label: 'Eyebrow', default: 'Pricing' },
  { key: 'pricing.h2', group: 'Pricing', label: 'Heading', default: 'Simple, transparent pricing.' },
  { key: 'pricing.sub', group: 'Pricing', label: 'Sub-text', default: 'No hidden costs. No per-user fees. No surprises.' },
  { key: 'pricing.starter.name', group: 'Pricing', label: 'Starter name', default: 'Starter' },
  { key: 'pricing.starter.price', group: 'Pricing', label: 'Starter price', default: '£85' },
  { key: 'pricing.starter.per', group: 'Pricing', label: 'Starter price suffix', default: '/month' },
  { key: 'pricing.starter.note', group: 'Pricing', label: 'Starter note', default: 'Per home. Unlimited staff users.' },
  { key: 'pricing.starter.f1', group: 'Pricing', label: 'Starter feature 1', default: 'Policy library (up to 25 policies)' },
  { key: 'pricing.starter.f2', group: 'Pricing', label: 'Starter feature 2', default: 'Hub and email access for all staff' },
  { key: 'pricing.starter.f3', group: 'Pricing', label: 'Starter feature 3', default: '60+ language support' },
  { key: 'pricing.starter.f4', group: 'Pricing', label: 'Starter feature 4', default: '500 queries/month' },
  { key: 'pricing.starter.f5', group: 'Pricing', label: 'Starter feature 5', default: 'Full audit trail' },
  { key: 'pricing.starter.f6', group: 'Pricing', label: 'Starter feature 6', default: 'Basic analytics' },
  { key: 'pricing.starter.cta', group: 'Pricing', label: 'Starter CTA', default: 'Start Free Trial' },
  { key: 'pricing.pro.badge', group: 'Pricing', label: 'Professional badge', default: 'Most popular' },
  { key: 'pricing.pro.name', group: 'Pricing', label: 'Professional name', default: 'Professional' },
  { key: 'pricing.pro.price', group: 'Pricing', label: 'Professional price', default: '£230' },
  { key: 'pricing.pro.per', group: 'Pricing', label: 'Professional price suffix', default: '/month' },
  { key: 'pricing.pro.note', group: 'Pricing', label: 'Professional note', default: 'Per home. Everything in Starter, plus:' },
  { key: 'pricing.pro.f1', group: 'Pricing', label: 'Professional feature 1', default: 'Unlimited policies' },
  { key: 'pricing.pro.f2', group: 'Pricing', label: 'Professional feature 2', default: '5,000 queries/month' },
  { key: 'pricing.pro.f3', group: 'Pricing', label: 'Professional feature 3', default: 'CQC Readiness Report PDF' },
  { key: 'pricing.pro.f4', group: 'Pricing', label: 'Professional feature 4', default: 'Policy gap detection' },
  { key: 'pricing.pro.f5', group: 'Pricing', label: 'Professional feature 5', default: 'Language analytics' },
  { key: 'pricing.pro.f6', group: 'Pricing', label: 'Professional feature 6', default: 'Staff engagement by individual' },
  { key: 'pricing.pro.cta', group: 'Pricing', label: 'Professional CTA', default: 'Start Free Trial' },
  { key: 'pricing.ent.badge', group: 'Pricing', label: 'Enterprise badge', default: 'Everything included' },
  { key: 'pricing.ent.name', group: 'Pricing', label: 'Enterprise name', default: 'Enterprise' },
  { key: 'pricing.ent.price', group: 'Pricing', label: 'Enterprise price', default: '£385' },
  { key: 'pricing.ent.per', group: 'Pricing', label: 'Enterprise price suffix', default: '/month' },
  { key: 'pricing.ent.note', group: 'Pricing', label: 'Enterprise note', default: 'Per home. Everything in Professional, plus:' },
  { key: 'pricing.ent.f1', group: 'Pricing', label: 'Enterprise feature 1', default: 'Unlimited annual training allocations' },
  { key: 'pricing.ent.f2', group: 'Pricing', label: 'Enterprise feature 2', default: 'Build your own audits' },
  { key: 'pricing.ent.f3', group: 'Pricing', label: 'Enterprise feature 3', default: 'Training effectiveness analytics' },
  { key: 'pricing.ent.f4', group: 'Pricing', label: 'Enterprise feature 4', default: 'Multi-site group console' },
  { key: 'pricing.ent.f5', group: 'Pricing', label: 'Enterprise feature 5', default: 'Workforce compliance register' },
  { key: 'pricing.ent.f6', group: 'Pricing', label: 'Enterprise feature 6', default: 'Priority support' },
  { key: 'pricing.ent.cta', group: 'Pricing', label: 'Enterprise CTA', default: 'Start Free Trial' },
  { key: 'pricing.cta', group: 'Pricing', label: 'Compare CTA', default: 'Full pricing and feature comparison' },

  // Final CTA
  { key: 'finalcta.eyebrow', group: 'Final CTA', label: 'Eyebrow', default: 'Get Started' },
  { key: 'finalcta.h2', group: 'Final CTA', label: 'Heading', default: 'Give your whole team the policy access they deserve.' },
  { key: 'finalcta.sub', group: 'Final CTA', label: 'Sub-text', default: '14-day free trial. No charge until day 14. Set up in under an hour.' },
  { key: 'finalcta.primary', group: 'Final CTA', label: 'Primary CTA', default: 'Book a Free Demo' },
  { key: 'finalcta.secondary', group: 'Final CTA', label: 'Secondary CTA', default: 'Start Free Trial' },
]
