import type { SlotDef } from './types'

// Editable copy for /how-it-works. Defaults are the current live copy; editing a
// slot in the platform (Main site pages → /how-it-works) overrides it without
// touching the design.
export const HOW_IT_WORKS_SLOTS: SlotDef[] = [
  // Hero
  { key: 'hero.label', group: 'Hero', label: 'Eyebrow', default: 'How It Works' },
  { key: 'hero.h1', group: 'Hero', label: 'Headline', default: 'Everything you need to know about how CareStreamAI works.' },
  { key: 'hero.intro', group: 'Hero', label: 'Intro paragraph', multiline: true, default: 'From uploading your first policy to your CQC inspection, a complete walkthrough of every feature, how it works, and why it matters for your care setting.' },

  // Getting started
  { key: 'start.label', group: 'Getting started', label: 'Eyebrow', default: 'Getting Started' },
  { key: 'start.h2', group: 'Getting started', label: 'Heading', default: 'Up and running in under an hour.' },
  { key: 'start.intro', group: 'Getting started', label: 'Intro', multiline: true, default: 'There is no integration project, no IT department involvement, and no lengthy rollout. Three steps and your whole team has access.' },
  { key: 'start.step1.title', group: 'Getting started', label: 'Step 1 title', default: 'Upload your documents' },
  { key: 'start.step1.body', group: 'Getting started', label: 'Step 1 body', multiline: true, default: 'Upload your policy library, staff handbook, and any supporting documents from the admin dashboard. PDF, Word, and plain text are all accepted. There is no limit on file size or number of policies.' },
  { key: 'start.step1.detail', group: 'Getting started', label: 'Step 1 detail', multiline: true, default: 'Most care settings upload between 20 and 80 policy documents. The upload takes minutes.' },
  { key: 'start.step2.title', group: 'Getting started', label: 'Step 2 title', default: 'CareStreamAI processes them' },
  { key: 'start.step2.body', group: 'Getting started', label: 'Step 2 body', multiline: true, default: 'Each document is read, chunked into meaningful sections, and indexed for semantic search. Key facts such as named individuals, contact numbers and local procedures are extracted and made searchable.' },
  { key: 'start.step2.detail', group: 'Getting started', label: 'Step 2 detail', multiline: true, default: 'Processing typically completes in under five minutes per document, automatically.' },
  { key: 'start.step3.title', group: 'Getting started', label: 'Step 3 title', default: 'Your team goes live' },
  { key: 'start.step3.body', group: 'Getting started', label: 'Step 3 body', multiline: true, default: 'Add your staff and they get the hub on their phone, with email as a backup. They can immediately ask questions, read policies and start their training, in the language they think in, with voice input when typing is harder.' },
  { key: 'start.step3.detail', group: 'Getting started', label: 'Step 3 detail', multiline: true, default: 'Most care settings are fully live within 45 minutes of starting the setup process.' },

  // AI engine
  { key: 'ai.label', group: 'AI engine', label: 'Eyebrow', default: 'The AI Engine' },
  { key: 'ai.h2', group: 'AI engine', label: 'Heading', default: 'How the AI generates answers.' },
  { key: 'ai.intro', group: 'AI engine', label: 'Intro', multiline: true, default: 'CareStreamAI uses a technique called Retrieval-Augmented Generation (RAG). In plain English: it finds the right part of your policy, reads it, and writes the answer from that content only.' },
  { key: 'ai.step1.title', group: 'AI engine', label: 'Step 1 title', default: 'Semantic search' },
  { key: 'ai.step1.body', group: 'AI engine', label: 'Step 1 body', multiline: true, default: 'The question is converted into a mathematical representation and matched against your indexed policies. The most relevant sections are retrieved, even when the exact wording of the question differs from the policy.' },
  { key: 'ai.step2.title', group: 'AI engine', label: 'Step 2 title', default: 'Context assembly' },
  { key: 'ai.step2.body', group: 'AI engine', label: 'Step 2 body', multiline: true, default: 'The retrieved policy sections are assembled into a context window, along with any conversation history from the current session and the relevant regulatory framework.' },
  { key: 'ai.step3.title', group: 'AI engine', label: 'Step 3 title', default: 'Answer generation' },
  { key: 'ai.step3.body', group: 'AI engine', label: 'Step 3 body', multiline: true, default: 'The AI is instructed to answer using only the provided context. It cannot draw on general knowledge or training data. If the answer is not in your documents, it says so.' },
  { key: 'ai.step4.title', group: 'AI engine', label: 'Step 4 title', default: 'Citation and logging' },
  { key: 'ai.step4.body', group: 'AI engine', label: 'Step 4 body', multiline: true, default: 'Every response cites the exact policy and section used. The full interaction, including question, answer, policy cited, language, channel and timestamp, is logged to the audit trail.' },
  { key: 'ai.callout.label', group: 'AI engine', label: 'Callout label', default: 'Why it cannot make things up' },
  { key: 'ai.callout.body', group: 'AI engine', label: 'Callout body', rich: true, default: 'The AI is given your policy content and told: answer from this, and only this. It has no access to the internet, no access to other organisations’ policies, and no access to its general training data when answering. If a question cannot be answered from your documents, it tells the staff member and flags the gap for your review.' },

  // Channels
  { key: 'hub.label', group: 'Channels', label: 'Eyebrow', default: 'The Hub' },
  { key: 'hub.h2', group: 'Channels', label: 'Heading', default: 'One hub on their phone. Email and voice when it suits.' },
  { key: 'hub.intro', group: 'Channels', label: 'Intro', multiline: true, default: 'The hub is where your team lives day to day: their policies, their training and instant answers, in one place. Email and voice give the same quality of response, drawn from the same library, with the same audit trail.' },
  { key: 'hub.app.name', group: 'Channels', label: 'Hub app title', default: 'The hub app' },
  { key: 'hub.app.sub', group: 'Channels', label: 'Hub app subtitle', default: 'On any smartphone, plus desktop browser' },
  { key: 'hub.app.body', group: 'Channels', label: 'Hub app body', multiline: true, default: 'The hub is the one place for your whole team. Staff open it to ask a policy question, read a procedure, or complete a piece of training, all in the language they think in. The chat is conversational, so they can ask follow-ups within the same session and the system keeps full context. Reminders and new training arrive as notifications, so nothing gets missed.' },
  { key: 'hub.app.b1', group: 'Channels', label: 'Hub app point 1', default: 'Policies, training and answers in one place' },
  { key: 'hub.app.b2', group: 'Channels', label: 'Hub app point 2', default: 'Push notifications for reminders and new training' },
  { key: 'hub.app.b3', group: 'Channels', label: 'Hub app point 3', default: 'Conversational follow-ups with full session context' },
  { key: 'hub.app.b4', group: 'Channels', label: 'Hub app point 4', default: 'Voice input for hands-free questions mid-task' },
  { key: 'hub.app.b5', group: 'Channels', label: 'Hub app point 5', default: 'Suggested follow-up questions after each response' },
  { key: 'hub.app.b6', group: 'Channels', label: 'Hub app point 6', default: 'Works on any smartphone or desktop browser' },
  { key: 'hub.email.name', group: 'Channels', label: 'Email title', default: 'Email' },
  { key: 'hub.email.sub', group: 'Channels', label: 'Email subtitle', default: 'Any email client, any device' },
  { key: 'hub.email.body', group: 'Channels', label: 'Email body', multiline: true, default: 'Staff email your dedicated CareStreamAI address from any device. The system replies within 30 seconds. Replying to the response continues the conversation. The system reads the full thread and maintains context across multiple exchanges.' },
  { key: 'hub.email.b1', group: 'Channels', label: 'Email point 1', default: 'No login and no app required, works from any email client' },
  { key: 'hub.email.b2', group: 'Channels', label: 'Email point 2', default: 'Response arrives in the same email thread within 30 seconds' },
  { key: 'hub.email.b3', group: 'Channels', label: 'Email point 3', default: 'Thread context maintained, reply to continue the conversation' },
  { key: 'hub.email.b4', group: 'Channels', label: 'Email point 4', default: 'Useful for staff who prefer email or are on shift handover' },
  { key: 'hub.voice.name', group: 'Channels', label: 'Voice title', default: 'Voice input' },
  { key: 'hub.voice.sub', group: 'Channels', label: 'Voice subtitle', default: 'In the hub, hands-free' },
  { key: 'hub.voice.body', group: 'Channels', label: 'Voice body', multiline: true, default: 'Not everyone types quickly in their second language. Voice input lets staff speak their question naturally, mid-task and hands-free, in any language. The audio is transcribed, language-detected, and answered from your policies in the same language it was spoken.' },
  { key: 'hub.voice.b1', group: 'Channels', label: 'Voice point 1', default: '60+ languages supported for voice input' },
  { key: 'hub.voice.b2', group: 'Channels', label: 'Voice point 2', default: 'Transcription shown alongside the answer for transparency' },
  { key: 'hub.voice.b3', group: 'Channels', label: 'Voice point 3', default: 'Same response quality as typed queries' },
  { key: 'hub.voice.b4', group: 'Channels', label: 'Voice point 4', default: 'Logged identically, voice queries appear in the audit trail' },

  // Staff training
  { key: 'training.label', group: 'Staff training', label: 'Eyebrow', default: 'Staff Training' },
  { key: 'training.h2', group: 'Staff training', label: 'Heading', default: 'Training that lives in the same hub.' },
  { key: 'training.intro', group: 'Staff training', label: 'Intro', multiline: true, default: 'CareStream is not only about answering questions. It delivers your mandatory training and modules built from your own policies, in the hub your team already uses, in 60+ languages, with renewals tracked for you.' },
  { key: 'training.card1.title', group: 'Staff training', label: 'Card 1 title', default: 'Mandatory library' },
  { key: 'training.card1.body', group: 'Staff training', label: 'Card 1 body', multiline: true, default: 'Every annual mandatory subject, ready to assign, from safeguarding to moving and handling.' },
  { key: 'training.card2.title', group: 'Staff training', label: 'Card 2 title', default: 'Built from your policies' },
  { key: 'training.card2.body', group: 'Staff training', label: 'Card 2 body', multiline: true, default: 'Generate a module from your own policy documents, so it teaches your procedures, not generic content.' },
  { key: 'training.card3.title', group: 'Staff training', label: 'Card 3 title', default: 'Teach, then assess' },
  { key: 'training.card3.body', group: 'Staff training', label: 'Card 3 body', multiline: true, default: 'Each module teaches in short sections, applies a real care scenario, and finishes with an assessment.' },
  { key: 'training.card4.title', group: 'Staff training', label: 'Card 4 title', default: 'Learn and retry' },
  { key: 'training.card4.body', group: 'Staff training', label: 'Card 4 body', multiline: true, default: 'A wrong answer triggers a short follow-up lesson and a fresh question, so the gap is closed.' },
  { key: 'training.cta', group: 'Staff training', label: 'Link text', default: 'See how training works' },
  { key: 'training.note1', group: 'Staff training', label: 'Note 1', default: 'Renewal reminders at 90, 30 and 7 days' },
  { key: 'training.note2', group: 'Staff training', label: 'Note 2', default: 'New training arrives as a hub notification' },

  // Multilingual
  { key: 'lang.label', group: 'Multilingual', label: 'Eyebrow', default: 'Multilingual Engine' },
  { key: 'lang.h2', group: 'Multilingual', label: 'Heading', default: '60+ languages. Zero configuration.' },
  { key: 'lang.p1', group: 'Multilingual', label: 'Paragraph 1', rich: true, default: 'Language detection is automatic and happens on every query. Staff do not select a language, toggle a setting, or use a special command. They simply ask their question, in the language they think in, and the answer comes back in the same language.' },
  { key: 'lang.p2', group: 'Multilingual', label: 'Paragraph 2', rich: true, default: 'Responses are always generated from your English-language policies. The translation happens at the point of response, not at the point of upload. This means you maintain one authoritative English policy library and every language version is derived from it consistently.' },
  { key: 'lang.stat1.value', group: 'Multilingual', label: 'Stat 1 value', default: '60+' },
  { key: 'lang.stat1.label', group: 'Multilingual', label: 'Stat 1 label', default: 'Languages detected' },
  { key: 'lang.stat2.value', group: 'Multilingual', label: 'Stat 2 value', default: 'English' },
  { key: 'lang.stat2.label', group: 'Multilingual', label: 'Stat 2 label', default: 'Source policy language' },
  { key: 'lang.stat3.value', group: 'Multilingual', label: 'Stat 3 value', default: 'None' },
  { key: 'lang.stat3.label', group: 'Multilingual', label: 'Stat 3 label', default: 'Setup required' },
  { key: 'lang.stat4.value', group: 'Multilingual', label: 'Stat 4 value', default: '£0' },
  { key: 'lang.stat4.label', group: 'Multilingual', label: 'Stat 4 label', default: 'Extra cost per language' },
  { key: 'lang.demo.heading', group: 'Multilingual', label: 'Demo caption heading', default: 'The same question, six languages, one policy' },
  { key: 'lang.demo.footer', group: 'Multilingual', label: 'Demo caption footer', default: 'All answered from the same Falls Policy, each in the language asked' },

  // Regulatory
  { key: 'reg.label', group: 'Regulatory', label: 'Eyebrow', default: 'Regulatory Intelligence' },
  { key: 'reg.h2', group: 'Regulatory', label: 'Heading', default: 'Over 50 UK regulatory frameworks, pre-loaded.' },
  { key: 'reg.intro', group: 'Regulatory', label: 'Intro', multiline: true, default: 'Your internal policies don’t exist in isolation. They’re built on a foundation of UK law and regulation. CareStreamAI has over 50 regulatory frameworks pre-loaded so that when a staff member asks something that touches both your policy and an external requirement, the response explains how the two interact.' },
  { key: 'reg.how.label', group: 'Regulatory', label: 'How-it-works panel label', default: 'How it works' },
  { key: 'reg.how1.title', group: 'Regulatory', label: 'How step 1 title', default: 'Your internal policy is retrieved' },
  { key: 'reg.how1.body', group: 'Regulatory', label: 'How step 1 body', multiline: true, default: 'The most relevant section of your own policy is found and used as the primary source for the response.' },
  { key: 'reg.how2.title', group: 'Regulatory', label: 'How step 2 title', default: 'Relevant regulations are overlaid' },
  { key: 'reg.how2.body', group: 'Regulatory', label: 'How step 2 body', multiline: true, default: 'CareStreamAI identifies which of the 50+ pre-loaded frameworks apply to the question, including CQC, RIDDOR, MCA and GDPR, and adds that context.' },
  { key: 'reg.how3.title', group: 'Regulatory', label: 'How step 3 title', default: 'The interaction is explained' },
  { key: 'reg.how3.body', group: 'Regulatory', label: 'How step 3 body', multiline: true, default: 'The response explains both what your policy requires and what the law requires, including where they align, where they differ, and where your policy goes further.' },
  { key: 'reg.frameworks.label', group: 'Regulatory', label: 'Frameworks list label', default: 'A selection of included frameworks' },
  { key: 'reg.fw1.name', group: 'Regulatory', label: 'Framework 1 name', default: 'CQC Fundamental Standards' },
  { key: 'reg.fw1.reg', group: 'Regulatory', label: 'Framework 1 badge', default: 'Reg 9 to 20' },
  { key: 'reg.fw2.name', group: 'Regulatory', label: 'Framework 2 name', default: 'Health and Safety at Work Act 1974' },
  { key: 'reg.fw2.reg', group: 'Regulatory', label: 'Framework 2 badge', default: 'HSWA 1974' },
  { key: 'reg.fw3.name', group: 'Regulatory', label: 'Framework 3 name', default: 'GDPR and Data Protection Act 2018' },
  { key: 'reg.fw3.reg', group: 'Regulatory', label: 'Framework 3 badge', default: 'UK GDPR' },
  { key: 'reg.fw4.name', group: 'Regulatory', label: 'Framework 4 name', default: 'Mental Capacity Act 2005' },
  { key: 'reg.fw4.reg', group: 'Regulatory', label: 'Framework 4 badge', default: 'MCA 2005' },
  { key: 'reg.fw5.name', group: 'Regulatory', label: 'Framework 5 name', default: 'Care Act 2014 Safeguarding' },
  { key: 'reg.fw5.reg', group: 'Regulatory', label: 'Framework 5 badge', default: 'Care Act 2014' },
  { key: 'reg.fw6.name', group: 'Regulatory', label: 'Framework 6 name', default: 'RIDDOR 2013' },
  { key: 'reg.fw6.reg', group: 'Regulatory', label: 'Framework 6 badge', default: 'RIDDOR 2013' },
  { key: 'reg.fw7.name', group: 'Regulatory', label: 'Framework 7 name', default: 'Equality Act 2010' },
  { key: 'reg.fw7.reg', group: 'Regulatory', label: 'Framework 7 badge', default: 'EA 2010' },
  { key: 'reg.fw8.name', group: 'Regulatory', label: 'Framework 8 name', default: 'Control of Substances Hazardous to Health' },
  { key: 'reg.fw8.reg', group: 'Regulatory', label: 'Framework 8 badge', default: 'COSHH 2002' },
  { key: 'reg.frameworks.more', group: 'Regulatory', label: 'Frameworks footer', default: '+ 42 additional frameworks included' },

  // Knowledge base
  { key: 'kb.label', group: 'Knowledge base', label: 'Eyebrow', default: 'The Knowledge Base' },
  { key: 'kb.h2', group: 'Knowledge base', label: 'Heading', default: 'Not just your policies. Your care setting, in detail.' },
  { key: 'kb.p1', group: 'Knowledge base', label: 'Paragraph 1', rich: true, default: 'CareStreamAI doesn’t just answer generic questions about policies. Because it reads your actual documents, it extracts the specific facts that make your service unique: named individuals, direct-dial numbers, shift arrangements and local procedures.' },
  { key: 'kb.p2', group: 'Knowledge base', label: 'Paragraph 2', rich: true, default: 'Upload your staff handbook, on-call rota, local infection control guidance, or any supporting document and it becomes immediately queryable. Staff get answers that reflect how your service actually operates, not how a generic care setting might.' },
  { key: 'kb.f1', group: 'Knowledge base', label: 'Feature 1', default: 'Named individuals and contact numbers from your rota and handbook' },
  { key: 'kb.f2', group: 'Knowledge base', label: 'Feature 2', default: 'Local procedures and site-specific instructions' },
  { key: 'kb.f3', group: 'Knowledge base', label: 'Feature 3', default: 'Staff handbook: HR policies, leave, disciplinary and onboarding' },
  { key: 'kb.f4', group: 'Knowledge base', label: 'Feature 4', default: "Seeded knowledge never mixed with other tenants' data" },

  // Policy gaps
  { key: 'gap.label', group: 'Policy gaps', label: 'Eyebrow', default: 'Policy Gap Detection' },
  { key: 'gap.h2', group: 'Policy gaps', label: 'Heading', default: 'Find your gaps before CQC does.' },
  { key: 'gap.p1', group: 'Policy gaps', label: 'Paragraph 1', rich: true, default: 'Every time CareStreamAI cannot find an answer in your documents, it flags the query as a gap. Over time, patterns emerge: the same questions appearing repeatedly without policy coverage.' },
  { key: 'gap.p2', group: 'Policy gaps', label: 'Paragraph 2', rich: true, default: 'Your Policy Gap Report shows exactly which questions your staff are asking that your current policies don’t address, ranked by frequency. This is actionable evidence of where your policy library needs strengthening, surfaced before an inspection identifies it first.' },
  { key: 'gap.f1.title', group: 'Policy gaps', label: 'Feature 1 title', default: 'Real-time flagging' },
  { key: 'gap.f1.body', group: 'Policy gaps', label: 'Feature 1 body', multiline: true, default: 'Every unanswered query is flagged immediately, not batched monthly.' },
  { key: 'gap.f2.title', group: 'Policy gaps', label: 'Feature 2 title', default: 'Ranked by frequency' },
  { key: 'gap.f2.body', group: 'Policy gaps', label: 'Feature 2 body', multiline: true, default: 'The most commonly asked unanswered questions are shown first, so you fix the most impactful gaps.' },
  { key: 'gap.f3.title', group: 'Policy gaps', label: 'Feature 3 title', default: 'Monthly summary report' },
  { key: 'gap.f3.body', group: 'Policy gaps', label: 'Feature 3 body', multiline: true, default: 'A summary is compiled automatically and available for your manager review.' },
  { key: 'gap.f4.title', group: 'Policy gaps', label: 'Feature 4 title', default: 'Included in CQC Readiness Report' },
  { key: 'gap.f4.body', group: 'Policy gaps', label: 'Feature 4 body', multiline: true, default: 'Gap resolution evidence is included as proof of continuous improvement.' },

  // Analytics
  { key: 'analytics.label', group: 'Analytics', label: 'Eyebrow', default: 'Analytics & Compliance' },
  { key: 'analytics.h2', group: 'Analytics', label: 'Heading', default: 'Your compliance evidence builds automatically.' },
  { key: 'analytics.intro', group: 'Analytics', label: 'Intro', multiline: true, default: 'Every interaction with CareStreamAI is logged and structured. Your analytics dashboard and CQC Readiness Report are generated from this data continuously. There is nothing to compile manually.' },
  { key: 'analytics.card1.title', group: 'Analytics', label: 'Card 1 title', default: 'Usage analytics dashboard' },
  { key: 'analytics.card1.body', group: 'Analytics', label: 'Card 1 body', multiline: true, default: 'See total queries, active staff, top policies accessed, busiest times, and channel breakdown (hub, email, voice), updated in real time.' },
  { key: 'analytics.card2.title', group: 'Analytics', label: 'Card 2 title', default: 'Language activity report' },
  { key: 'analytics.card2.body', group: 'Analytics', label: 'Card 2 body', multiline: true, default: 'Which languages your staff are asking in, how frequently, and which policies are being accessed across languages. CQC evidence of equitable access.' },
  { key: 'analytics.card3.title', group: 'Analytics', label: 'Card 3 title', default: 'Staff engagement tracking' },
  { key: 'analytics.card3.body', group: 'Analytics', label: 'Card 3 body', multiline: true, default: 'Which individuals are using the system, how often, and whether engagement changes after policy updates or training events.' },
  { key: 'analytics.card4.title', group: 'Analytics', label: 'Card 4 title', default: 'Query history and audit log' },
  { key: 'analytics.card4.body', group: 'Analytics', label: 'Card 4 body', multiline: true, default: 'Every query is stored: who asked, what they asked, which policy was cited, the full response, and the timestamp. Searchable and exportable.' },
  { key: 'analytics.card5.title', group: 'Analytics', label: 'Card 5 title', default: 'CQC Readiness Report' },
  { key: 'analytics.card5.body', group: 'Analytics', label: 'Card 5 body', multiline: true, default: 'A structured PDF covering policy access frequency, multilingual activity, staff engagement, gap identification and resolution, and version history. Ready for inspection.' },
  { key: 'analytics.card6.title', group: 'Analytics', label: 'Card 6 title', default: 'Policy version history' },
  { key: 'analytics.card6.body', group: 'Analytics', label: 'Card 6 body', multiline: true, default: 'Every version of every uploaded policy is retained. You can see which version was in use when any query was answered, which is important for post-incident review.' },

  // Security
  { key: 'security.label', group: 'Security', label: 'Eyebrow', default: 'Data & Security' },
  { key: 'security.h2', group: 'Security', label: 'Heading', default: 'Your data stays yours.' },
  { key: 'security.body', group: 'Security', label: 'Paragraph', rich: true, default: 'Every tenant’s policy library is stored in a completely isolated environment. Your policies are never used to train any model, never shared with other organisations, and never accessible to anyone outside your account. Data is encrypted at rest and in transit. UK data residency is available on Professional and Enterprise plans.' },
  { key: 'security.f1.label', group: 'Security', label: 'Feature 1 label', default: 'Tenant isolation' },
  { key: 'security.f1.detail', group: 'Security', label: 'Feature 1 detail', multiline: true, default: 'Complete data separation between all organisations' },
  { key: 'security.f2.label', group: 'Security', label: 'Feature 2 label', default: 'Encrypted at rest' },
  { key: 'security.f2.detail', group: 'Security', label: 'Feature 2 detail', multiline: true, default: 'AES-256 encryption for all stored documents and logs' },
  { key: 'security.f3.label', group: 'Security', label: 'Feature 3 label', default: 'Never used for training' },
  { key: 'security.f3.detail', group: 'Security', label: 'Feature 3 detail', multiline: true, default: 'Your documents are never used to train AI models' },
  { key: 'security.f4.label', group: 'Security', label: 'Feature 4 label', default: 'UK data residency' },
  { key: 'security.f4.detail', group: 'Security', label: 'Feature 4 detail', multiline: true, default: 'Available on Professional and Enterprise plans' },
]
