import type { SlotDef } from './types'

// GENERATED by carestream-theme-preview/gen_rag_slots.py — re-run it rather than editing.
//
// Editable copy for the rebuilt /rag page: defaults here, overrides saved under
// Main site pages -> /rag.
//
// The six "why it matters" icons are NOT here. They are not copy, and live in
// lib/rag-icons.ts as shapes the template builds real elements from.
export const RAG_V2_SLOTS: SlotDef[] = [

  { key: 'hero.label', group: 'Hero', label: 'Eyebrow', default: 'How our AI works' },
  { key: 'hero.h1', group: 'Hero', label: 'Headline', default: 'Every answer comes from a source. Every question is grounded in knowledge.' },
  { key: 'hero.lede', group: 'Hero', label: 'Paragraph', multiline: true, default: 'CareStreamAI is built on a class of AI architecture called Retrieval Augmented Generation. This page explains what that means, why we chose it, and what it means for the accuracy and trustworthiness of everything the platform tells your staff.' },

  { key: 'principle.label', group: 'The principle', label: 'Eyebrow', default: 'The principle' },
  { key: 'principle.h2', group: 'The principle', label: 'Heading', default: 'AI that is anchored to facts, not free to guess.' },
  { key: 'principle.p1', group: 'The principle', label: 'Paragraph 1', multiline: true, default: 'The most widely reported problem with AI is hallucination, where a system produces a confident, plausible-sounding answer that is simply wrong. In most general-purpose AI tools, the model draws on everything it has ever seen and fills the gaps itself.' },
  { key: 'principle.p2', group: 'The principle', label: 'Paragraph 2', multiline: true, default: 'Retrieval Augmented Generation (RAG) is the architectural answer to that problem. Instead of relying on what a model already knows, RAG requires the system to find the relevant information first, and answer only from what it has found.' },
  { key: 'principle.p3', group: 'The principle', label: 'Paragraph 3', multiline: true, default: 'CareStreamAI uses RAG across the platform: answering policy questions from your uploaded documents, generating training from specialist care knowledge, and grounding the CQC prep and audit tools in real guidance.' },
  { key: 'principle.s1.n', group: 'The principle', label: 'Step 1 number', default: '01' },
  { key: 'principle.s1.title', group: 'The principle', label: 'Step 1 title', default: 'Retrieve first' },
  { key: 'principle.s1.body', group: 'The principle', label: 'Step 1 body', multiline: true, default: 'Before any response is generated, the system searches for the most relevant content in the verified source material. Only the most relevant sections are passed to the AI.' },
  { key: 'principle.s2.n', group: 'The principle', label: 'Step 2 number', default: '02' },
  { key: 'principle.s2.title', group: 'The principle', label: 'Step 2 title', default: 'Ground the response' },
  { key: 'principle.s2.body', group: 'The principle', label: 'Step 2 body', multiline: true, default: 'The AI composes its response using only the retrieved content. It is explicitly instructed not to draw on general knowledge, internet sources, or inference beyond what has been retrieved.' },
  { key: 'principle.s3.n', group: 'The principle', label: 'Step 3 number', default: '03' },
  { key: 'principle.s3.title', group: 'The principle', label: 'Step 3 title', default: 'Cite the source' },
  { key: 'principle.s3.body', group: 'The principle', label: 'Step 3 body', multiline: true, default: 'Every response includes a reference to the source it drew from, whether a specific policy, procedure, or authoritative guidance document. Staff and managers can always trace an answer back to its origin.' },

  { key: 'policy.label', group: 'Policy questions', label: 'Eyebrow', default: 'Policy questions' },
  { key: 'policy.h2', group: 'Policy questions', label: 'Heading', default: 'Your policies are the only source of truth.' },
  { key: 'policy.p1', group: 'Policy questions', label: 'Paragraph 1', multiline: true, default: 'When a staff member asks a question in the hub or by email, CareStreamAI searches your organisation\'s uploaded policy library. Only your documents are searched. Not the internet. Not another organisation\'s policies.' },
  { key: 'policy.p2', group: 'Policy questions', label: 'Paragraph 2', multiline: true, default: 'The most relevant sections of your policies are identified and passed to the AI as the sole basis for its response. The answer your staff member receives reflects your policies exactly as you have written them.' },
  { key: 'policy.p3', group: 'Policy questions', label: 'Paragraph 3', multiline: true, default: 'If no relevant content is found in your library, the system says so, and logs the question as a knowledge gap so you can identify which policies need to be written or updated.' },
  { key: 'policy.f1.n', group: 'Policy questions', label: 'Flow 1 number', default: '1' },
  { key: 'policy.f1.title', group: 'Policy questions', label: 'Flow 1 title', default: 'Staff member asks a question' },
  { key: 'policy.f1.body', group: 'Policy questions', label: 'Flow 1 body', multiline: true, default: 'In the hub or by email, in any language.' },
  { key: 'policy.f2.n', group: 'Policy questions', label: 'Flow 2 number', default: '2' },
  { key: 'policy.f2.title', group: 'Policy questions', label: 'Flow 2 title', default: 'System searches your policy library' },
  { key: 'policy.f2.body', group: 'Policy questions', label: 'Flow 2 body', multiline: true, default: 'Only your uploaded documents are searched. Nothing else.' },
  { key: 'policy.f3.n', group: 'Policy questions', label: 'Flow 3 number', default: '3' },
  { key: 'policy.f3.title', group: 'Policy questions', label: 'Flow 3 title', default: 'Relevant sections are identified' },
  { key: 'policy.f3.body', group: 'Policy questions', label: 'Flow 3 body', multiline: true, default: 'The most applicable content is retrieved from your policies.' },
  { key: 'policy.f4.n', group: 'Policy questions', label: 'Flow 4 number', default: '4' },
  { key: 'policy.f4.title', group: 'Policy questions', label: 'Flow 4 title', default: 'AI composes a response from the source' },
  { key: 'policy.f4.body', group: 'Policy questions', label: 'Flow 4 body', multiline: true, default: 'The answer is drawn directly from the retrieved content.' },
  { key: 'policy.f5.n', group: 'Policy questions', label: 'Flow 5 number', default: '5' },
  { key: 'policy.f5.title', group: 'Policy questions', label: 'Flow 5 title', default: 'Response delivered with citation' },
  { key: 'policy.f5.body', group: 'Policy questions', label: 'Flow 5 body', multiline: true, default: 'Staff receive the answer and a reference to the source policy.' },

  { key: 'training.label', group: 'Training questions', label: 'Eyebrow', default: 'Training questions' },
  { key: 'training.h2', group: 'Training questions', label: 'Heading', default: 'Questions generated from knowledge, not imagination.' },
  { key: 'training.p1', group: 'Training questions', label: 'Paragraph 1', multiline: true, default: 'CareStreamAI\'s training assessment questions are not written by guesswork. Each training topic is supported by a specialist knowledge entry that describes the topic in the context of care delivery and the guidance that governs it.' },
  { key: 'training.p2', group: 'Training questions', label: 'Paragraph 2', multiline: true, default: 'When a training question is generated, the AI retrieves the relevant knowledge for that topic and uses it as the basis for the question and its answer options. The correct answer is grounded in what the guidance actually says.' },
  { key: 'training.p3', group: 'Training questions', label: 'Paragraph 3', multiline: true, default: 'This means your staff are not being assessed against vague generalisations. They are being tested on the real, current requirements that CQC and sector bodies expect care workers to know.' },
  { key: 'training.c1.title', group: 'Training questions', label: 'Card 1 title', default: 'Specialist knowledge base' },
  { key: 'training.c1.body', group: 'Training questions', label: 'Card 1 body', multiline: true, default: 'Each training topic is underpinned by a curated knowledge entry covering its care context, practical requirements, and authoritative source guidance.' },
  { key: 'training.c2.title', group: 'Training questions', label: 'Card 2 title', default: 'Authoritative source links' },
  { key: 'training.c2.body', group: 'Training questions', label: 'Card 2 body', multiline: true, default: 'Training questions draw on published guidance from bodies including CQC, Skills for Care, and NHS England, not general internet content.' },
  { key: 'training.c3.title', group: 'Training questions', label: 'Card 3 title', default: 'Grounded question generation' },
  { key: 'training.c3.body', group: 'Training questions', label: 'Card 3 body', multiline: true, default: 'Questions are generated from the source knowledge, not invented. Every option and correct answer reflects real guidance from the topic area.' },
  { key: 'training.c4.title', group: 'Training questions', label: 'Card 4 title', default: 'Accurate assessments' },
  { key: 'training.c4.body', group: 'Training questions', label: 'Card 4 body', multiline: true, default: 'Because questions are grounded in verified knowledge, staff are tested on what guidance actually says, not on approximations or generalisations.' },

  { key: 'why.label', group: 'Why it matters', label: 'Eyebrow', default: 'Why it matters' },
  { key: 'why.h2', group: 'Why it matters', label: 'Heading', default: 'Accuracy is not a feature. It is a requirement.' },
  { key: 'why.w1.title', group: 'Why it matters', label: 'Point 1 title', default: 'No hallucination risk' },
  { key: 'why.w1.body', group: 'Why it matters', label: 'Point 1 body', multiline: true, default: 'Because responses are bounded by retrieved source material, the system cannot invent procedures, thresholds, or responsibilities that do not exist in your policies.' },
  { key: 'why.w2.title', group: 'Why it matters', label: 'Point 2 title', default: 'Your policies, reflected accurately' },
  { key: 'why.w2.body', group: 'Why it matters', label: 'Point 2 body', multiline: true, default: 'The AI answers based on what your organisation has written. If your policy says 30 minutes, the answer says 30 minutes. If your policy names a specific role, the answer names that role.' },
  { key: 'why.w3.title', group: 'Why it matters', label: 'Point 3 title', default: 'Gaps surface automatically' },
  { key: 'why.w3.body', group: 'Why it matters', label: 'Point 3 body', multiline: true, default: 'When a question cannot be answered from your library, it is logged as a gap, so you can see exactly what your policies are missing.' },
  { key: 'why.w4.title', group: 'Why it matters', label: 'Point 4 title', default: 'Audit trail for every response' },
  { key: 'why.w4.body', group: 'Why it matters', label: 'Point 4 body', multiline: true, default: 'Every answer is logged alongside the source it drew from. You have a complete, traceable record of what information was provided to staff and where it came from.' },
  { key: 'why.w5.title', group: 'Why it matters', label: 'Point 5 title', default: 'Training grounded in guidance' },
  { key: 'why.w5.body', group: 'Why it matters', label: 'Point 5 body', multiline: true, default: 'Assessment questions reflect published sector guidance, not approximations. Staff are tested on what CQC and regulatory bodies actually expect, not a generic interpretation of it.' },
  { key: 'why.w6.title', group: 'Why it matters', label: 'Point 6 title', default: 'Consistent at scale' },
  { key: 'why.w6.body', group: 'Why it matters', label: 'Point 6 body', multiline: true, default: 'Whether ten staff or two hundred are asking questions, every response is subject to the same retrieval process and the same document boundaries. Quality does not degrade with volume.' },

  { key: 'note.label', group: 'Transparency', label: 'Eyebrow', default: 'A note on transparency' },
  { key: 'note.h2', group: 'Transparency', label: 'Heading', default: 'We explain the principle. We protect the craft.' },
  { key: 'note.p1', group: 'Transparency', label: 'Paragraph 1', multiline: true, default: 'This page explains how CareStreamAI\'s AI architecture works at the level that matters for your governance, your compliance teams, and your staff. We believe you deserve to understand what the system is doing with your data and where its answers come from.' },
  { key: 'note.p2', group: 'Transparency', label: 'Paragraph 2', multiline: true, default: 'We do not publish the specific technical implementation that makes CareStreamAI work as well as it does: the retrieval design, the knowledge structures, the prompt engineering, and the quality controls that have been built and refined over time.' },

  { key: 'practice.label', group: 'In practice', label: 'Eyebrow', default: 'In practice' },
  { key: 'practice.h2', group: 'In practice', label: 'Heading', default: 'From your library to a cited answer.' },
  { key: 'practice.lede', group: 'In practice', label: 'Paragraph', multiline: true, default: 'A staff member asks; the system retrieves from your indexed documents; the answer comes back with the policy and section it came from.' },

  { key: 'cta.h2', group: 'Closing', label: 'Heading', default: 'See it working on your own policies.' },
  { key: 'cta.lede', group: 'Closing', label: 'Paragraph', multiline: true, default: 'Book a demo and watch CareStreamAI answer questions from your documents in real time.' },
]
