import type { SlotDef } from './types'

// Editable copy for the rebuilt /training-platform page. Defaults are the approved theme
// copy, generated by carestream-theme-preview/gen_training_platform_slots.py; overrides are
// saved under Main site pages -> /training-platform.
//
// The twelve list icons are NOT here. They are not copy, and they live in
// lib/training-platform-icons.ts as shapes the template builds real elements from.
export const TRAINING_PLATFORM_V2_SLOTS: SlotDef[] = [

  { key: 'hero.label', group: 'Hero', label: 'Eyebrow', default: 'Training platform' },
  { key: 'hero.h1', group: 'Hero', label: 'Headline', default: 'Training built from your own policies' },
  { key: 'hero.lede', group: 'Hero', label: 'Paragraph', multiline: true, default: 'CareStream turns your service\'s own policies into training modules, so your staff learn your agreed ways of working, not generic content. Add face to face session management, reporting and a single training matrix, and every part of training in your service is planned, delivered and evidenced in one place.' },

  { key: 'adhoc.label', group: 'Adhoc training', label: 'Eyebrow', default: 'Adhoc training' },
  { key: 'adhoc.h2', group: 'Adhoc training', label: 'Heading', default: 'Adhoc training from your policies' },
  { key: 'adhoc.intro', group: 'Adhoc training', label: 'Paragraph', multiline: true, default: 'Pick any policy or topic and CareStream generates a lesson and question set grounded in your service\'s own policy documents. When a policy changes, an incident throws up a gap, or an inspection is coming, you can have relevant training in front of your team the same day.' },
  { key: 'adhoc.i1.title', group: 'Adhoc training', label: 'Item 1 title', default: 'Generated from your own policies' },
  { key: 'adhoc.i1.body', group: 'Adhoc training', label: 'Item 1 body', multiline: true, default: 'Choose a policy or topic and get a lesson and question set drawn from your service\'s documents, in your wording.' },
  { key: 'adhoc.i2.title', group: 'Adhoc training', label: 'Item 2 title', default: 'Approved before staff see it' },
  { key: 'adhoc.i2.body', group: 'Adhoc training', label: 'Item 2 body', multiline: true, default: 'Every module sits with your admin for review and approval first, so you stay in control of what your team is taught.' },
  { key: 'adhoc.i3.title', group: 'Adhoc training', label: 'Item 3 title', default: 'Delivered in each learner\'s language' },
  { key: 'adhoc.i3.body', group: 'Adhoc training', label: 'Item 3 body', multiline: true, default: 'Modules are delivered in the staff hub in each learner\'s own language, while your records stay in English.' },

  { key: 'f2f.label', group: 'Face to face', label: 'Eyebrow', default: 'Face to face' },
  { key: 'f2f.h2', group: 'Face to face', label: 'Heading', default: 'Face to face training, organised' },
  { key: 'f2f.intro', group: 'Face to face', label: 'Paragraph', multiline: true, default: 'Some training has to happen in person. CareStream keeps it organised: schedule face to face sessions, invite the right staff, and track attendance and completion without a spreadsheet or a sign-in sheet going missing.' },
  { key: 'f2f.i1.title', group: 'Face to face', label: 'Item 1 title', default: 'Sessions you set up in a minute' },
  { key: 'f2f.i1.body', group: 'Face to face', label: 'Item 1 body', multiline: true, default: 'Set up a session, invite the staff who need it, and see at a glance who is booked on.' },
  { key: 'f2f.i2.title', group: 'Face to face', label: 'Item 2 title', default: 'Reminders that chase for you' },
  { key: 'f2f.i2.body', group: 'Face to face', label: 'Item 2 body', multiline: true, default: 'Staff are reminded automatically before their session, so fewer places go to waste and chasing stops being your job.' },
  { key: 'f2f.i3.title', group: 'Face to face', label: 'Item 3 title', default: 'Attendance, and the hours it owes' },
  { key: 'f2f.i3.body', group: 'Face to face', label: 'Item 3 body', multiline: true, default: 'Attendance and completion are recorded against each session, with a payroll ready report of hours owed for sessions attended off shift.' },

  { key: 'reporting.label', group: 'Reporting', label: 'Eyebrow', default: 'Reporting' },
  { key: 'reporting.h2', group: 'Reporting', label: 'Heading', default: 'Reporting that runs itself' },
  { key: 'reporting.intro', group: 'Reporting', label: 'Paragraph', multiline: true, default: 'Every lesson, answer and session feeds your reporting automatically. You see completion and scores across the whole team, and the record you would want to show an inspector is already assembled, not waiting to be pulled together the night before.' },
  { key: 'reporting.i1.title', group: 'Reporting', label: 'Item 1 title', default: 'Completion and scores across the team' },
  { key: 'reporting.i1.body', group: 'Reporting', label: 'Item 1 body', multiline: true, default: 'See who has completed what and how they scored, across your whole service, without collating anything.' },
  { key: 'reporting.i2.title', group: 'Reporting', label: 'Item 2 title', default: 'Learning time and engagement' },
  { key: 'reporting.i2.body', group: 'Reporting', label: 'Item 2 body', multiline: true, default: 'Evidence of the time your staff spend learning and how engaged they are, gathered as it happens.' },
  { key: 'reporting.i3.title', group: 'Reporting', label: 'Item 3 title', default: 'Per staff member records, inspection ready' },
  { key: 'reporting.i3.body', group: 'Reporting', label: 'Item 3 body', multiline: true, default: 'Each staff member has a complete training record ready to show at inspection, with nothing to assemble on the day.' },

  { key: 'matrix.label', group: 'The matrix', label: 'Eyebrow', default: 'The matrix' },
  { key: 'matrix.h2', group: 'The matrix', label: 'Heading', default: 'One training matrix for everything' },
  { key: 'matrix.intro', group: 'The matrix', label: 'Paragraph', multiline: true, default: 'A single matrix shows every staff member against every module, covering annual training, adhoc policy training and face to face sessions in one view. Statuses are visible at a glance, so you always know where your service stands and what needs attention this week.' },
  { key: 'matrix.i1.title', group: 'The matrix', label: 'Item 1 title', default: 'Every staff member, every module' },
  { key: 'matrix.i1.body', group: 'The matrix', label: 'Item 1 body', multiline: true, default: 'One grid covers your whole team against everything they need to complete, with no separate lists to reconcile.' },
  { key: 'matrix.i2.title', group: 'The matrix', label: 'Item 2 title', default: 'Annual, adhoc and face to face together' },
  { key: 'matrix.i2.body', group: 'The matrix', label: 'Item 2 body', multiline: true, default: 'Annual training, adhoc policy modules and face to face sessions all appear in the same matrix, not three different systems.' },
  { key: 'matrix.i3.title', group: 'The matrix', label: 'Item 3 title', default: 'Renewals before they lapse' },
  { key: 'matrix.i3.body', group: 'The matrix', label: 'Item 3 body', multiline: true, default: 'See what is complete, in progress or outstanding the moment you open it, and what is due for renewal next.' },

  { key: 'steps.label', group: 'When someone gets it wrong', label: 'Eyebrow', default: 'When someone gets it wrong' },
  { key: 'steps.h2', group: 'When someone gets it wrong', label: 'Heading', default: 'Wrong answers become lessons, not failures' },
  { key: 'steps.intro', group: 'When someone gets it wrong', label: 'Paragraph', multiline: true, default: 'Most training marks a wrong answer and moves on, which teaches nobody anything. CareStream treats it as the moment the training is worth something.' },
  { key: 'steps.s1.n', group: 'When someone gets it wrong', label: 'Step 1 number', default: '01' },
  { key: 'steps.s1.title', group: 'When someone gets it wrong', label: 'Step 1 title', default: 'Instant lesson and feedback' },
  { key: 'steps.s1.body', group: 'When someone gets it wrong', label: 'Step 1 body', multiline: true, default: 'The staff member is told what a strong answer covers, straight away, while the question is still fresh.' },
  { key: 'steps.s2.n', group: 'When someone gets it wrong', label: 'Step 2 number', default: '02' },
  { key: 'steps.s2.title', group: 'When someone gets it wrong', label: 'Step 2 title', default: 'Targeted follow up question' },
  { key: 'steps.s2.body', group: 'When someone gets it wrong', label: 'Step 2 body', multiline: true, default: 'A short follow-up lesson and a fresh question on the exact point they missed arrives in their hub.' },
  { key: 'steps.s3.n', group: 'When someone gets it wrong', label: 'Step 3 number', default: '03' },
  { key: 'steps.s3.title', group: 'When someone gets it wrong', label: 'Step 3 title', default: 'Progress only when understood' },
  { key: 'steps.s3.body', group: 'When someone gets it wrong', label: 'Step 3 body', multiline: true, default: 'The gap has to close before the module completes, and the improvement from first attempt to latest is on the record.' },

  { key: 'cta.h2', group: 'Closing', label: 'Heading', default: 'Training your staff will actually recognise as yours.' },
  { key: 'cta.lede', group: 'Closing', label: 'Paragraph', multiline: true, default: 'Built from your policies, delivered in their language, and evidenced without you assembling anything.' },
]
