import type { SlotDef } from './types'

// Editable copy for /who-its-for. Defaults are the current live copy; editing a
// slot in the platform (Main site pages → /who-its-for) overrides it without
// touching the design.
export const WHO_ITS_FOR_SLOTS: SlotDef[] = [
  // Hero
  { key: 'hero.label', group: 'Hero', label: 'Eyebrow', default: "Who It's For" },
  { key: 'hero.h1', group: 'Hero', label: 'Headline', default: 'Built for every registered care provider.' },
  { key: 'hero.intro', group: 'Hero', label: 'Intro paragraph', multiline: true, default: 'If your organisation has internal policies and a team that needs to follow them, CareStreamAI turns those policies into a 24-hour knowledge resource for every member of staff.' },

  // ── Setting: Residential Care Homes ──
  { key: 'residential-care-homes.name', group: 'Residential Care Homes', label: 'Name', default: 'Residential Care Homes' },
  { key: 'residential-care-homes.headline', group: 'Residential Care Homes', label: 'Headline', default: 'Policy support for every shift, not just office hours.' },
  { key: 'residential-care-homes.desc', group: 'Residential Care Homes', label: 'Description', rich: true, default: 'Residential care homes rely on confident, consistent practice around the clock. CareStreamAI gives night staff, international carers, and new starters the same immediate access to your approved policies as your most experienced team member.' },
  { key: 'residential-care-homes.point.1', group: 'Residential Care Homes', label: 'Point 1', multiline: true, default: 'Night staff access the correct care and medication procedures instantly, without calling the manager out of hours.' },
  { key: 'residential-care-homes.point.2', group: 'Residential Care Homes', label: 'Point 2', multiline: true, default: 'International and multilingual carers ask questions in their own language and receive answers drawn directly from your policy library.' },
  { key: 'residential-care-homes.point.3', group: 'Residential Care Homes', label: 'Point 3', multiline: true, default: 'CQC inspection evidence is built automatically from every query, replacing the manual process of assembling compliance records under pressure.' },
  { key: 'residential-care-homes.point.4', group: 'Residential Care Homes', label: 'Point 4', multiline: true, default: 'Policy gap detection highlights what your library is missing before an inspector does.' },
  { key: 'residential-care-homes.topic.1', group: 'Residential Care Homes', label: 'Policy topic 1', default: 'Falls Management' },
  { key: 'residential-care-homes.topic.2', group: 'Residential Care Homes', label: 'Policy topic 2', default: 'Medication Administration' },
  { key: 'residential-care-homes.topic.3', group: 'Residential Care Homes', label: 'Policy topic 3', default: 'Infection Control' },
  { key: 'residential-care-homes.topic.4', group: 'Residential Care Homes', label: 'Policy topic 4', default: 'Safeguarding Adults' },
  { key: 'residential-care-homes.topic.5', group: 'Residential Care Homes', label: 'Policy topic 5', default: 'End of Life Care' },
  { key: 'residential-care-homes.topic.6', group: 'Residential Care Homes', label: 'Policy topic 6', default: 'Moving and Handling' },
  { key: 'residential-care-homes.std.1.label', group: 'Residential Care Homes', label: 'Standard 1 label', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'residential-care-homes.std.1.note', group: 'Residential Care Homes', label: 'Standard 1 note', multiline: true, default: 'Covers medication management, falls prevention, and infection control obligations across all shifts.' },
  { key: 'residential-care-homes.std.2.label', group: 'Residential Care Homes', label: 'Standard 2 label', default: 'CQC Regulation 13, Safeguarding' },
  { key: 'residential-care-homes.std.2.note', group: 'Residential Care Homes', label: 'Standard 2 note', multiline: true, default: 'Requires robust safeguarding procedures that every staff member can access and act on immediately.' },
  { key: 'residential-care-homes.std.3.label', group: 'Residential Care Homes', label: 'Standard 3 label', default: 'CQC Regulation 17, Good Governance' },
  { key: 'residential-care-homes.std.3.note', group: 'Residential Care Homes', label: 'Standard 3 note', multiline: true, default: 'Mandates accurate, complete records and documented evidence of policy engagement.' },
  { key: 'residential-care-homes.channel', group: 'Residential Care Homes', label: 'Example channel', default: 'Voice' },
  { key: 'residential-care-homes.question', group: 'Residential Care Homes', label: 'Example question', multiline: true, default: 'A resident has just had a fall. It is 3am. What observations do I need to carry out and how often?' },
  { key: 'residential-care-homes.src.1', group: 'Residential Care Homes', label: 'Source 1', default: 'Your Falls and Post-Fall Management Policy' },
  { key: 'residential-care-homes.src.2', group: 'Residential Care Homes', label: 'Source 2', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'residential-care-homes.src.3', group: 'Residential Care Homes', label: 'Source 3', default: 'NICE CG161, Falls in Older People' },
  { key: 'residential-care-homes.ans.1', group: 'Residential Care Homes', label: 'Answer point 1', multiline: true, default: "Your home's post-fall observation checklist and exact timing intervals" },
  { key: 'residential-care-homes.ans.2', group: 'Residential Care Homes', label: 'Answer point 2', multiline: true, default: 'When to escalate to the on-call GP or out-of-hours service' },
  { key: 'residential-care-homes.ans.3', group: 'Residential Care Homes', label: 'Answer point 3', multiline: true, default: 'Mandatory incident form requirements before end of shift' },
  { key: 'residential-care-homes.ans.4', group: 'Residential Care Homes', label: 'Answer point 4', multiline: true, default: 'How your policy aligns with CQC Reg 12 and NICE guidance' },

  // ── Setting: Nursing Homes ──
  { key: 'nursing-homes.name', group: 'Nursing Homes', label: 'Name', default: 'Nursing Homes' },
  { key: 'nursing-homes.headline', group: 'Nursing Homes', label: 'Headline', default: 'Clinical procedures at the point of care, not at the end of a corridor.' },
  { key: 'nursing-homes.desc', group: 'Nursing Homes', label: 'Description', rich: true, default: 'Nursing homes carry a higher level of clinical complexity than any other registered care setting. CareStreamAI ensures your clinical and care staff find the right procedure exactly when they need it, regardless of the hour or their first language.' },
  { key: 'nursing-homes.point.1', group: 'Nursing Homes', label: 'Point 1', multiline: true, default: 'Clinical staff access infection control, wound care, medication management, and end of life procedures in seconds.' },
  { key: 'nursing-homes.point.2', group: 'Nursing Homes', label: 'Point 2', multiline: true, default: 'Voice notes mean staff can ask a procedure question hands-free in a clinical situation, without leaving a resident.' },
  { key: 'nursing-homes.point.3', group: 'Nursing Homes', label: 'Point 3', multiline: true, default: 'Every query is logged with the staff member, time, and policy referenced, providing automatic CQC evidence of staff procedure engagement.' },
  { key: 'nursing-homes.point.4', group: 'Nursing Homes', label: 'Point 4', multiline: true, default: 'Policy gap detection identifies missing clinical protocols before a CQC inspection or clinical audit.' },
  { key: 'nursing-homes.topic.1', group: 'Nursing Homes', label: 'Policy topic 1', default: 'Catheter Care' },
  { key: 'nursing-homes.topic.2', group: 'Nursing Homes', label: 'Policy topic 2', default: 'Wound Management' },
  { key: 'nursing-homes.topic.3', group: 'Nursing Homes', label: 'Policy topic 3', default: 'Infection Control' },
  { key: 'nursing-homes.topic.4', group: 'Nursing Homes', label: 'Policy topic 4', default: 'Medication Administration' },
  { key: 'nursing-homes.topic.5', group: 'Nursing Homes', label: 'Policy topic 5', default: 'Pressure Area Care' },
  { key: 'nursing-homes.topic.6', group: 'Nursing Homes', label: 'Policy topic 6', default: 'End of Life Care' },
  { key: 'nursing-homes.std.1.label', group: 'Nursing Homes', label: 'Standard 1 label', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'nursing-homes.std.1.note', group: 'Nursing Homes', label: 'Standard 1 note', multiline: true, default: 'Clinical procedures must be accessible and applied consistently across day and night shifts.' },
  { key: 'nursing-homes.std.2.label', group: 'Nursing Homes', label: 'Standard 2 label', default: 'NICE NG113, Urinary Tract Infection in Adults' },
  { key: 'nursing-homes.std.2.note', group: 'Nursing Homes', label: 'Standard 2 note', multiline: true, default: 'Provides clinical guidance on catheter care and infection prevention in nursing settings.' },
  { key: 'nursing-homes.std.3.label', group: 'Nursing Homes', label: 'Standard 3 label', default: 'CQC Regulation 11, Need for Consent' },
  { key: 'nursing-homes.std.3.note', group: 'Nursing Homes', label: 'Standard 3 note', multiline: true, default: 'Informed consent must be sought and documented before every clinical intervention.' },
  { key: 'nursing-homes.channel', group: 'Nursing Homes', label: 'Example channel', default: 'Voice' },
  { key: 'nursing-homes.question', group: 'Nursing Homes', label: 'Example question', multiline: true, default: 'A resident has a urinary catheter. They have not passed urine in six hours and the catheter bag is empty. What does the catheter care policy say I should do?' },
  { key: 'nursing-homes.src.1', group: 'Nursing Homes', label: 'Source 1', default: 'Catheter Care and Management Policy' },
  { key: 'nursing-homes.src.2', group: 'Nursing Homes', label: 'Source 2', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'nursing-homes.src.3', group: 'Nursing Homes', label: 'Source 3', default: 'NICE NG113, Urinary Tract Infection in Adults' },
  { key: 'nursing-homes.ans.1', group: 'Nursing Homes', label: 'Answer point 1', multiline: true, default: 'Step-by-step catheter patency check, including kinking, positioning, and bladder palpation' },
  { key: 'nursing-homes.ans.2', group: 'Nursing Homes', label: 'Answer point 2', multiline: true, default: 'Your policy threshold for contacting the on-call GP or district nurse' },
  { key: 'nursing-homes.ans.3', group: 'Nursing Homes', label: 'Answer point 3', multiline: true, default: 'Signs of urinary tract infection or catheter-associated complications requiring urgent escalation' },
  { key: 'nursing-homes.ans.4', group: 'Nursing Homes', label: 'Answer point 4', multiline: true, default: 'Mandatory fluid balance and catheter record entries before handing over to the next shift' },

  // ── Setting: Home Care and Domiciliary Care ──
  { key: 'home-care.name', group: 'Home Care and Domiciliary Care', label: 'Name', default: 'Home Care and Domiciliary Care' },
  { key: 'home-care.headline', group: 'Home Care and Domiciliary Care', label: 'Headline', default: 'Policy access for a workforce that is never in one place.' },
  { key: 'home-care.desc', group: 'Home Care and Domiciliary Care', label: 'Description', rich: true, default: 'Domiciliary care staff work alone, often in challenging environments, without a colleague or manager nearby. CareStreamAI gives your dispersed workforce instant access to your procedures via the hub or voice, wherever they are.' },
  { key: 'home-care.point.1', group: 'Home Care and Domiciliary Care', label: 'Point 1', multiline: true, default: 'Field-based carers get immediate policy answers in the hub or by voice note while travelling between visits.' },
  { key: 'home-care.point.2', group: 'Home Care and Domiciliary Care', label: 'Point 2', multiline: true, default: 'Lone workers check safeguarding, consent, and incident procedures without travelling to the office or waiting for a callback.' },
  { key: 'home-care.point.3', group: 'Home Care and Domiciliary Care', label: 'Point 3', multiline: true, default: 'Managers see query patterns across the entire dispersed workforce from one dashboard, revealing where guidance or retraining is needed.' },
  { key: 'home-care.point.4', group: 'Home Care and Domiciliary Care', label: 'Point 4', multiline: true, default: 'All queries are logged by staff member and location, supporting lone working audits and CQC inspection evidence.' },
  { key: 'home-care.topic.1', group: 'Home Care and Domiciliary Care', label: 'Policy topic 1', default: 'Lone Working' },
  { key: 'home-care.topic.2', group: 'Home Care and Domiciliary Care', label: 'Policy topic 2', default: 'Safeguarding Adults' },
  { key: 'home-care.topic.3', group: 'Home Care and Domiciliary Care', label: 'Policy topic 3', default: 'Medication Administration' },
  { key: 'home-care.topic.4', group: 'Home Care and Domiciliary Care', label: 'Policy topic 4', default: 'Missed Visit Procedures' },
  { key: 'home-care.topic.5', group: 'Home Care and Domiciliary Care', label: 'Policy topic 5', default: 'Manual Handling' },
  { key: 'home-care.topic.6', group: 'Home Care and Domiciliary Care', label: 'Policy topic 6', default: 'Infection Control' },
  { key: 'home-care.std.1.label', group: 'Home Care and Domiciliary Care', label: 'Standard 1 label', default: 'CQC Regulation 13, Safeguarding Service Users' },
  { key: 'home-care.std.1.note', group: 'Home Care and Domiciliary Care', label: 'Standard 1 note', multiline: true, default: 'Safeguarding procedures must be accessible to lone workers in any location at any time.' },
  { key: 'home-care.std.2.label', group: 'Home Care and Domiciliary Care', label: 'Standard 2 label', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'home-care.std.2.note', group: 'Home Care and Domiciliary Care', label: 'Standard 2 note', multiline: true, default: 'Safe medication and infection control procedures apply in every home environment visited.' },
  { key: 'home-care.std.3.label', group: 'Home Care and Domiciliary Care', label: 'Standard 3 label', default: 'CQC Regulation 17, Good Governance' },
  { key: 'home-care.std.3.note', group: 'Home Care and Domiciliary Care', label: 'Standard 3 note', multiline: true, default: 'Every visit, missed contact, and incident must be recorded accurately in real time.' },
  { key: 'home-care.channel', group: 'Home Care and Domiciliary Care', label: 'Example channel', default: 'Voice' },
  { key: 'home-care.question', group: 'Home Care and Domiciliary Care', label: 'Example question', multiline: true, default: 'I have arrived at a service user\'s home and they are not answering the door. The lights are on and I can see them through the window but they are not responding. What is the procedure?' },
  { key: 'home-care.src.1', group: 'Home Care and Domiciliary Care', label: 'Source 1', default: 'Lone Working and Missed Visit Policy' },
  { key: 'home-care.src.2', group: 'Home Care and Domiciliary Care', label: 'Source 2', default: 'Safeguarding Adults Policy' },
  { key: 'home-care.src.3', group: 'Home Care and Domiciliary Care', label: 'Source 3', default: 'CQC Regulation 13, Safeguarding Service Users' },
  { key: 'home-care.ans.1', group: 'Home Care and Domiciliary Care', label: 'Answer point 1', multiline: true, default: 'Exact steps to take before calling emergency services, including contacting the office and next of kin' },
  { key: 'home-care.ans.2', group: 'Home Care and Domiciliary Care', label: 'Answer point 2', multiline: true, default: 'When your policy requires you to call 999 and request a welfare check without delay' },
  { key: 'home-care.ans.3', group: 'Home Care and Domiciliary Care', label: 'Answer point 3', multiline: true, default: 'What to record on the missed visit log and how to notify your manager immediately' },
  { key: 'home-care.ans.4', group: 'Home Care and Domiciliary Care', label: 'Answer point 4', multiline: true, default: 'How this interaction is captured as a safeguarding concern and the referral threshold' },

  // ── Setting: Supported Living ──
  { key: 'supported-living.name', group: 'Supported Living', label: 'Name', default: 'Supported Living' },
  { key: 'supported-living.headline', group: 'Supported Living', label: 'Headline', default: 'Consistent, person-centred practice across every house.' },
  { key: 'supported-living.desc', group: 'Supported Living', label: 'Description', rich: true, default: 'Supported living services operate across multiple dispersed properties with varying support needs. CareStreamAI gives support workers in every house access to the same approved procedures and individual care guidance, at any time.' },
  { key: 'supported-living.point.1', group: 'Supported Living', label: 'Point 1', multiline: true, default: 'Support workers in dispersed houses access behaviour support plans, safeguarding procedures, and risk management guidance in seconds.' },
  { key: 'supported-living.point.2', group: 'Supported Living', label: 'Point 2', multiline: true, default: 'Staff in every property work from the same centrally approved policy library, eliminating inconsistent practice between houses.' },
  { key: 'supported-living.point.3', group: 'Supported Living', label: 'Point 3', multiline: true, default: 'All query and access data is visible to managers across all sites from a single dashboard.' },
  { key: 'supported-living.point.4', group: 'Supported Living', label: 'Point 4', multiline: true, default: 'Multilingual staff access procedures in their own language from day one, supporting rapid onboarding in high-turnover services.' },
  { key: 'supported-living.topic.1', group: 'Supported Living', label: 'Policy topic 1', default: 'Positive Behaviour Support' },
  { key: 'supported-living.topic.2', group: 'Supported Living', label: 'Policy topic 2', default: 'Safeguarding Adults' },
  { key: 'supported-living.topic.3', group: 'Supported Living', label: 'Policy topic 3', default: 'Mental Capacity' },
  { key: 'supported-living.topic.4', group: 'Supported Living', label: 'Policy topic 4', default: 'Risk Management' },
  { key: 'supported-living.topic.5', group: 'Supported Living', label: 'Policy topic 5', default: 'Restrictive Practice' },
  { key: 'supported-living.topic.6', group: 'Supported Living', label: 'Policy topic 6', default: 'Community Access Safety' },
  { key: 'supported-living.std.1.label', group: 'Supported Living', label: 'Standard 1 label', default: 'CQC Regulation 11, Need for Consent' },
  { key: 'supported-living.std.1.note', group: 'Supported Living', label: 'Standard 1 note', multiline: true, default: 'All support must be delivered with valid consent or a documented best interests decision.' },
  { key: 'supported-living.std.2.label', group: 'Supported Living', label: 'Standard 2 label', default: 'CQC Regulation 13, Safeguarding' },
  { key: 'supported-living.std.2.note', group: 'Supported Living', label: 'Standard 2 note', multiline: true, default: 'Safeguarding procedures must be embedded and accessible across every dispersed property.' },
  { key: 'supported-living.std.3.label', group: 'Supported Living', label: 'Standard 3 label', default: 'NICE NG11, Challenging Behaviour and Learning Disabilities' },
  { key: 'supported-living.std.3.note', group: 'Supported Living', label: 'Standard 3 note', multiline: true, default: 'PBS approaches underpin safe, person-centred support and guide all restrictive practice decisions.' },
  { key: 'supported-living.channel', group: 'Supported Living', label: 'Example channel', default: 'Chat' },
  { key: 'supported-living.question', group: 'Supported Living', label: 'Example question', multiline: true, default: 'A resident is becoming very distressed and is showing early warning signs listed in their behaviour support plan. Their key worker is not on shift. What should I do right now?' },
  { key: 'supported-living.src.1', group: 'Supported Living', label: 'Source 1', default: 'Positive Behaviour Support Policy' },
  { key: 'supported-living.src.2', group: 'Supported Living', label: 'Source 2', default: 'Individual Behaviour Support Plan' },
  { key: 'supported-living.src.3', group: 'Supported Living', label: 'Source 3', default: 'NICE NG11, Challenging Behaviour and Learning Disabilities' },
  { key: 'supported-living.ans.1', group: 'Supported Living', label: 'Answer point 1', multiline: true, default: "The proactive and reactive strategies from the resident's individual PBS plan, in the correct sequence" },
  { key: 'supported-living.ans.2', group: 'Supported Living', label: 'Answer point 2', multiline: true, default: 'Environmental adjustments your policy requires before any other intervention' },
  { key: 'supported-living.ans.3', group: 'Supported Living', label: 'Answer point 3', multiline: true, default: 'Your escalation threshold and who to contact if early strategies do not reduce distress' },
  { key: 'supported-living.ans.4', group: 'Supported Living', label: 'Answer point 4', multiline: true, default: 'Recording requirements, including the time, triggers, and strategies used, before end of shift' },

  // ── Setting: Extra Care and Assisted Living ──
  { key: 'extra-care.name', group: 'Extra Care and Assisted Living', label: 'Name', default: 'Extra Care and Assisted Living' },
  { key: 'extra-care.headline', group: 'Extra Care and Assisted Living', label: 'Headline', default: 'Balancing housing and care regulation in one policy library.' },
  { key: 'extra-care.desc', group: 'Extra Care and Assisted Living', label: 'Description', rich: true, default: 'Extra care and assisted living settings navigate both housing and care regulation. CareStreamAI holds your full policy library, giving staff covering multiple flats or wings the right answer from the right document every time.' },
  { key: 'extra-care.point.1', group: 'Extra Care and Assisted Living', label: 'Point 1', multiline: true, default: 'Staff covering multiple properties access the correct care and tenancy procedures quickly, without searching through separate document stores.' },
  { key: 'extra-care.point.2', group: 'Extra Care and Assisted Living', label: 'Point 2', multiline: true, default: 'Managers maintain housing and care policy libraries in one place, with version control ensuring staff always access current procedures.' },
  { key: 'extra-care.point.3', group: 'Extra Care and Assisted Living', label: 'Point 3', multiline: true, default: 'CQC and housing regulation compliance evidence is captured automatically across all interactions.' },
  { key: 'extra-care.point.4', group: 'Extra Care and Assisted Living', label: 'Point 4', multiline: true, default: 'International staff from diverse backgrounds engage with your full policy library in their own language from their first shift.' },
  { key: 'extra-care.topic.1', group: 'Extra Care and Assisted Living', label: 'Policy topic 1', default: 'Mental Capacity and Consent' },
  { key: 'extra-care.topic.2', group: 'Extra Care and Assisted Living', label: 'Policy topic 2', default: 'Medication Administration' },
  { key: 'extra-care.topic.3', group: 'Extra Care and Assisted Living', label: 'Policy topic 3', default: 'Falls Prevention' },
  { key: 'extra-care.topic.4', group: 'Extra Care and Assisted Living', label: 'Policy topic 4', default: 'Tenancy and Care Procedures' },
  { key: 'extra-care.topic.5', group: 'Extra Care and Assisted Living', label: 'Policy topic 5', default: 'Safeguarding Adults' },
  { key: 'extra-care.topic.6', group: 'Extra Care and Assisted Living', label: 'Policy topic 6', default: 'Moving and Handling' },
  { key: 'extra-care.std.1.label', group: 'Extra Care and Assisted Living', label: 'Standard 1 label', default: 'Mental Capacity Act 2005, Sections 2 and 3' },
  { key: 'extra-care.std.1.note', group: 'Extra Care and Assisted Living', label: 'Standard 1 note', multiline: true, default: "Staff must apply the two-stage capacity test before any decision is made on a resident's behalf." },
  { key: 'extra-care.std.2.label', group: 'Extra Care and Assisted Living', label: 'Standard 2 label', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'extra-care.std.2.note', group: 'Extra Care and Assisted Living', label: 'Standard 2 note', multiline: true, default: 'Safe care obligations cover both the care and housing elements of the service.' },
  { key: 'extra-care.std.3.label', group: 'Extra Care and Assisted Living', label: 'Standard 3 label', default: 'CQC Regulation 10, Dignity and Respect' },
  { key: 'extra-care.std.3.note', group: 'Extra Care and Assisted Living', label: 'Standard 3 note', multiline: true, default: "Residents' rights as tenants and care recipients must be upheld in every interaction." },
  { key: 'extra-care.channel', group: 'Extra Care and Assisted Living', label: 'Example channel', default: 'Email' },
  { key: 'extra-care.question', group: 'Extra Care and Assisted Living', label: 'Example question', multiline: true, default: 'A resident is refusing their medication this morning and saying they do not want it today. How do I carry out a capacity assessment and what do I need to record?' },
  { key: 'extra-care.src.1', group: 'Extra Care and Assisted Living', label: 'Source 1', default: 'Mental Capacity and Consent Policy' },
  { key: 'extra-care.src.2', group: 'Extra Care and Assisted Living', label: 'Source 2', default: 'Medication Administration Policy' },
  { key: 'extra-care.src.3', group: 'Extra Care and Assisted Living', label: 'Source 3', default: 'Mental Capacity Act 2005, Sections 2 and 3' },
  { key: 'extra-care.ans.1', group: 'Extra Care and Assisted Living', label: 'Answer point 1', multiline: true, default: 'The two-stage Mental Capacity Act test your policy requires, applied to this specific decision' },
  { key: 'extra-care.ans.2', group: 'Extra Care and Assisted Living', label: 'Answer point 2', multiline: true, default: 'How to record the capacity assessment in the medication administration record' },
  { key: 'extra-care.ans.3', group: 'Extra Care and Assisted Living', label: 'Answer point 3', multiline: true, default: 'Who to notify if you assess the resident as lacking capacity for this decision' },
  { key: 'extra-care.ans.4', group: 'Extra Care and Assisted Living', label: 'Answer point 4', multiline: true, default: "Your policy's best interests process, including family involvement and GP notification" },

  // ── Setting: Hospices and Palliative Care ──
  { key: 'hospices.name', group: 'Hospices and Palliative Care', label: 'Name', default: 'Hospices and Palliative Care' },
  { key: 'hospices.headline', group: 'Hospices and Palliative Care', label: 'Headline', default: 'The right procedure when it matters most.' },
  { key: 'hospices.desc', group: 'Hospices and Palliative Care', label: 'Description', rich: true, default: 'In hospice and palliative care, staff face some of the most emotionally and clinically complex situations in the sector. CareStreamAI ensures your full clinical and care procedure library is available to every staff member, at any hour.' },
  { key: 'hospices.point.1', group: 'Hospices and Palliative Care', label: 'Point 1', multiline: true, default: 'Clinical and care staff access complex symptom management, pain management, and end of life care protocols at any time, day or night.' },
  { key: 'hospices.point.2', group: 'Hospices and Palliative Care', label: 'Point 2', multiline: true, default: 'Bereavement support, family communication, and spiritual care procedures are always available without delay.' },
  { key: 'hospices.point.3', group: 'Hospices and Palliative Care', label: 'Point 3', multiline: true, default: 'CQC inspection evidence demonstrating dignity and person-centred care practice is built from every query and policy interaction.' },
  { key: 'hospices.point.4', group: 'Hospices and Palliative Care', label: 'Point 4', multiline: true, default: 'Staff working across inpatient and community palliative care access the same approved procedure library from any channel.' },
  { key: 'hospices.topic.1', group: 'Hospices and Palliative Care', label: 'Policy topic 1', default: 'Syringe Driver Management' },
  { key: 'hospices.topic.2', group: 'Hospices and Palliative Care', label: 'Policy topic 2', default: 'Breakthrough Pain Protocol' },
  { key: 'hospices.topic.3', group: 'Hospices and Palliative Care', label: 'Policy topic 3', default: 'DNACPR Procedures' },
  { key: 'hospices.topic.4', group: 'Hospices and Palliative Care', label: 'Policy topic 4', default: 'Bereavement Support' },
  { key: 'hospices.topic.5', group: 'Hospices and Palliative Care', label: 'Policy topic 5', default: 'Controlled Drug Administration' },
  { key: 'hospices.topic.6', group: 'Hospices and Palliative Care', label: 'Policy topic 6', default: 'End of Life Care Planning' },
  { key: 'hospices.std.1.label', group: 'Hospices and Palliative Care', label: 'Standard 1 label', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'hospices.std.1.note', group: 'Hospices and Palliative Care', label: 'Standard 1 note', multiline: true, default: 'Clinical symptom management protocols must be accessible and followed correctly at all hours.' },
  { key: 'hospices.std.2.label', group: 'Hospices and Palliative Care', label: 'Standard 2 label', default: 'NICE NG31, Care of Dying Adults in the Last Days of Life' },
  { key: 'hospices.std.2.note', group: 'Hospices and Palliative Care', label: 'Standard 2 note', multiline: true, default: 'Provides nationally recognised guidance on comfort, dignity, and communication at end of life.' },
  { key: 'hospices.std.3.label', group: 'Hospices and Palliative Care', label: 'Standard 3 label', default: 'CQC Regulation 11, Need for Consent' },
  { key: 'hospices.std.3.note', group: 'Hospices and Palliative Care', label: 'Standard 3 note', multiline: true, default: 'Advance decisions and DNACPR documentation must be accessible and acted on correctly.' },
  { key: 'hospices.channel', group: 'Hospices and Palliative Care', label: 'Example channel', default: 'Voice' },
  { key: 'hospices.question', group: 'Hospices and Palliative Care', label: 'Example question', multiline: true, default: 'A patient on a syringe driver appears to be in breakthrough pain two hours after the driver was set up. What does the palliative pain management policy say I should check and when do I escalate?' },
  { key: 'hospices.src.1', group: 'Hospices and Palliative Care', label: 'Source 1', default: 'Syringe Driver and Subcutaneous Infusion Policy' },
  { key: 'hospices.src.2', group: 'Hospices and Palliative Care', label: 'Source 2', default: 'Palliative Pain Management Protocol' },
  { key: 'hospices.src.3', group: 'Hospices and Palliative Care', label: 'Source 3', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'hospices.ans.1', group: 'Hospices and Palliative Care', label: 'Answer point 1', multiline: true, default: 'Syringe driver site assessment checklist and what to look for at the infusion site' },
  { key: 'hospices.ans.2', group: 'Hospices and Palliative Care', label: 'Answer point 2', multiline: true, default: 'Authorised breakthrough medication doses and the conditions under which you can administer them' },
  { key: 'hospices.ans.3', group: 'Hospices and Palliative Care', label: 'Answer point 3', multiline: true, default: 'When your policy requires you to call the on-call palliative care team or prescriber' },
  { key: 'hospices.ans.4', group: 'Hospices and Palliative Care', label: 'Answer point 4', multiline: true, default: "Mandatory documentation in the controlled drug register and the patient's care record" },

  // ── Setting: Day Services and Respite Care ──
  { key: 'day-services.name', group: 'Day Services and Respite Care', label: 'Name', default: 'Day Services and Respite Care' },
  { key: 'day-services.headline', group: 'Day Services and Respite Care', label: 'Headline', default: 'Policy access that moves with your team throughout the day.' },
  { key: 'day-services.desc', group: 'Day Services and Respite Care', label: 'Description', rich: true, default: 'Day services and respite care staff often move between multiple service users and environments without a fixed base. CareStreamAI gives your team instant procedure access wherever the working day takes them.' },
  { key: 'day-services.point.1', group: 'Day Services and Respite Care', label: 'Point 1', multiline: true, default: 'Staff moving between service users throughout the day access procedures via the hub or voice note hands-free, without pausing the activity.' },
  { key: 'day-services.point.2', group: 'Day Services and Respite Care', label: 'Point 2', multiline: true, default: 'Safeguarding, incident, and emergency procedures are always available, including off-site and community visits.' },
  { key: 'day-services.point.3', group: 'Day Services and Respite Care', label: 'Point 3', multiline: true, default: 'Respite coordinators can log and review every procedure query from their team from a single dashboard.' },
  { key: 'day-services.point.4', group: 'Day Services and Respite Care', label: 'Point 4', multiline: true, default: 'Quick query logging reduces the administrative burden on staff during a busy, activity-led day.' },
  { key: 'day-services.topic.1', group: 'Day Services and Respite Care', label: 'Policy topic 1', default: 'Epilepsy and Seizure Management' },
  { key: 'day-services.topic.2', group: 'Day Services and Respite Care', label: 'Policy topic 2', default: 'First Aid and Emergencies' },
  { key: 'day-services.topic.3', group: 'Day Services and Respite Care', label: 'Policy topic 3', default: 'Safeguarding Adults' },
  { key: 'day-services.topic.4', group: 'Day Services and Respite Care', label: 'Policy topic 4', default: 'Community Access Risk' },
  { key: 'day-services.topic.5', group: 'Day Services and Respite Care', label: 'Policy topic 5', default: 'Medication Administration' },
  { key: 'day-services.topic.6', group: 'Day Services and Respite Care', label: 'Policy topic 6', default: 'Incident Reporting' },
  { key: 'day-services.std.1.label', group: 'Day Services and Respite Care', label: 'Standard 1 label', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'day-services.std.1.note', group: 'Day Services and Respite Care', label: 'Standard 1 note', multiline: true, default: 'Emergency procedures and medical management plans must be accessible during all activities and outings.' },
  { key: 'day-services.std.2.label', group: 'Day Services and Respite Care', label: 'Standard 2 label', default: 'CQC Regulation 13, Safeguarding' },
  { key: 'day-services.std.2.note', group: 'Day Services and Respite Care', label: 'Standard 2 note', multiline: true, default: 'Safeguarding procedures apply in day service environments and during all community visits.' },
  { key: 'day-services.std.3.label', group: 'Day Services and Respite Care', label: 'Standard 3 label', default: 'CQC Regulation 17, Good Governance' },
  { key: 'day-services.std.3.note', group: 'Day Services and Respite Care', label: 'Standard 3 note', multiline: true, default: 'All incidents, near misses, and emergency responses must be recorded on the day they occur.' },
  { key: 'day-services.channel', group: 'Day Services and Respite Care', label: 'Example channel', default: 'Chat' },
  { key: 'day-services.question', group: 'Day Services and Respite Care', label: 'Example question', multiline: true, default: 'A service user has had a tonic-clonic seizure during an activity session. The seizure has stopped after two minutes. What does the epilepsy management policy say I need to do right now?' },
  { key: 'day-services.src.1', group: 'Day Services and Respite Care', label: 'Source 1', default: 'Epilepsy and Seizure Management Policy' },
  { key: 'day-services.src.2', group: 'Day Services and Respite Care', label: 'Source 2', default: 'First Aid and Emergency Procedures Policy' },
  { key: 'day-services.src.3', group: 'Day Services and Respite Care', label: 'Source 3', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'day-services.ans.1', group: 'Day Services and Respite Care', label: 'Answer point 1', multiline: true, default: 'Immediate post-seizure observations and the recovery position guidance from your policy' },
  { key: 'day-services.ans.2', group: 'Day Services and Respite Care', label: 'Answer point 2', multiline: true, default: "Your policy's threshold for calling 999, including seizure duration and the five-minute rule" },
  { key: 'day-services.ans.3', group: 'Day Services and Respite Care', label: 'Answer point 3', multiline: true, default: 'Who to notify, including parents, carers, and the registered manager, and within what timeframe' },
  { key: 'day-services.ans.4', group: 'Day Services and Respite Care', label: 'Answer point 4', multiline: true, default: 'Incident form requirements, including seizure log entries, before the end of the session' },

  // ── Setting: Mental Health Residential Services ──
  { key: 'mental-health.name', group: 'Mental Health Residential Services', label: 'Name', default: 'Mental Health Residential Services' },
  { key: 'mental-health.headline', group: 'Mental Health Residential Services', label: 'Headline', default: 'Crisis procedures, de-escalation, and risk guidance when your team needs them.' },
  { key: 'mental-health.desc', group: 'Mental Health Residential Services', label: 'Description', rich: true, default: 'Mental health residential services require staff to access complex risk, medication, and de-escalation procedures under pressure. CareStreamAI gives your whole team immediate procedure access around the clock.' },
  { key: 'mental-health.point.1', group: 'Mental Health Residential Services', label: 'Point 1', multiline: true, default: 'Risk assessment, de-escalation, and medication procedures are available instantly, including during active crisis situations.' },
  { key: 'mental-health.point.2', group: 'Mental Health Residential Services', label: 'Point 2', multiline: true, default: 'Voice note access means staff can ask a procedure question without breaking focus or leaving a service user unattended.' },
  { key: 'mental-health.point.3', group: 'Mental Health Residential Services', label: 'Point 3', multiline: true, default: 'Every procedure query is logged with staff member, time, and context, supporting post-incident reviews and CQC evidence.' },
  { key: 'mental-health.point.4', group: 'Mental Health Residential Services', label: 'Point 4', multiline: true, default: 'Policy updates reach the whole team immediately, with access tracked so managers know when a change has landed.' },
  { key: 'mental-health.topic.1', group: 'Mental Health Residential Services', label: 'Policy topic 1', default: 'De-escalation and Restraint' },
  { key: 'mental-health.topic.2', group: 'Mental Health Residential Services', label: 'Policy topic 2', default: 'Self-Harm Risk Management' },
  { key: 'mental-health.topic.3', group: 'Mental Health Residential Services', label: 'Policy topic 3', default: 'Observation Levels' },
  { key: 'mental-health.topic.4', group: 'Mental Health Residential Services', label: 'Policy topic 4', default: 'Medication Management' },
  { key: 'mental-health.topic.5', group: 'Mental Health Residential Services', label: 'Policy topic 5', default: 'Mental Health Act Procedures' },
  { key: 'mental-health.topic.6', group: 'Mental Health Residential Services', label: 'Policy topic 6', default: 'Post-Incident Debrief' },
  { key: 'mental-health.std.1.label', group: 'Mental Health Residential Services', label: 'Standard 1 label', default: 'CQC Regulation 17, Good Governance' },
  { key: 'mental-health.std.1.note', group: 'Mental Health Residential Services', label: 'Standard 1 note', multiline: true, default: 'Post-incident reviews and accurate risk documentation are core compliance requirements.' },
  { key: 'mental-health.std.2.label', group: 'Mental Health Residential Services', label: 'Standard 2 label', default: 'Mental Health Act 1983, Sections 2 and 3' },
  { key: 'mental-health.std.2.note', group: 'Mental Health Residential Services', label: 'Standard 2 note', multiline: true, default: 'Detention, consent to treatment, and leave procedures must be followed precisely and documented.' },
  { key: 'mental-health.std.3.label', group: 'Mental Health Residential Services', label: 'Standard 3 label', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'mental-health.std.3.note', group: 'Mental Health Residential Services', label: 'Standard 3 note', multiline: true, default: 'Risk management and medication procedures must be accessible and consistently applied around the clock.' },
  { key: 'mental-health.channel', group: 'Mental Health Residential Services', label: 'Example channel', default: 'Voice' },
  { key: 'mental-health.question', group: 'Mental Health Residential Services', label: 'Example question', multiline: true, default: 'A resident is becoming increasingly agitated, is refusing to engage, and has a documented history of self-harm. What does the de-escalation policy say I should do and at what point do I call for support?' },
  { key: 'mental-health.src.1', group: 'Mental Health Residential Services', label: 'Source 1', default: 'De-escalation and Positive Engagement Policy' },
  { key: 'mental-health.src.2', group: 'Mental Health Residential Services', label: 'Source 2', default: 'Self-Harm Risk Management Policy' },
  { key: 'mental-health.src.3', group: 'Mental Health Residential Services', label: 'Source 3', default: 'CQC Regulation 17, Good Governance' },
  { key: 'mental-health.ans.1', group: 'Mental Health Residential Services', label: 'Answer point 1', multiline: true, default: 'The staged de-escalation approach from your policy, including verbal and environmental strategies in sequence' },
  { key: 'mental-health.ans.2', group: 'Mental Health Residential Services', label: 'Answer point 2', multiline: true, default: 'Your threshold for a two-person response and the circumstances that require an immediate manager call' },
  { key: 'mental-health.ans.3', group: 'Mental Health Residential Services', label: 'Answer point 3', multiline: true, default: 'Observations your policy requires following a self-harm risk episode, and who records them' },
  { key: 'mental-health.ans.4', group: 'Mental Health Residential Services', label: 'Answer point 4', multiline: true, default: 'Post-incident debrief requirements and what must be entered in the risk management record' },

  // ── Setting: Learning Disability Services ──
  { key: 'learning-disability.name', group: 'Learning Disability Services', label: 'Name', default: 'Learning Disability Services' },
  { key: 'learning-disability.headline', group: 'Learning Disability Services', label: 'Headline', default: 'Plain language procedure access for every member of your team.' },
  { key: 'learning-disability.desc', group: 'Learning Disability Services', label: 'Description', rich: true, default: 'Learning disability and autism services rely on highly consistent, person-centred practice across residential, community, and day settings. CareStreamAI makes your full procedure library accessible to every staff member, in clear language, at any time.' },
  { key: 'learning-disability.point.1', group: 'Learning Disability Services', label: 'Point 1', multiline: true, default: 'Support workers access positive behaviour support plans, safeguarding procedures, and individual care guidance in seconds.' },
  { key: 'learning-disability.point.2', group: 'Learning Disability Services', label: 'Point 2', multiline: true, default: 'Multilingual staff access procedures in their own language, supporting a diverse workforce with varying English confidence.' },
  { key: 'learning-disability.point.3', group: 'Learning Disability Services', label: 'Point 3', multiline: true, default: 'Managers track policy engagement across all registered services from a single dashboard, identifying where support or retraining is needed.' },
  { key: 'learning-disability.point.4', group: 'Learning Disability Services', label: 'Point 4', multiline: true, default: 'Consistent procedure access across all service types reduces variation in support quality between different settings and teams.' },
  { key: 'learning-disability.topic.1', group: 'Learning Disability Services', label: 'Policy topic 1', default: 'Positive Behaviour Support' },
  { key: 'learning-disability.topic.2', group: 'Learning Disability Services', label: 'Policy topic 2', default: 'Restrictive Practice' },
  { key: 'learning-disability.topic.3', group: 'Learning Disability Services', label: 'Policy topic 3', default: 'Safeguarding Adults' },
  { key: 'learning-disability.topic.4', group: 'Learning Disability Services', label: 'Policy topic 4', default: 'Mental Capacity and Best Interests' },
  { key: 'learning-disability.topic.5', group: 'Learning Disability Services', label: 'Policy topic 5', default: 'Communication Support Plans' },
  { key: 'learning-disability.topic.6', group: 'Learning Disability Services', label: 'Policy topic 6', default: 'Community Safety' },
  { key: 'learning-disability.std.1.label', group: 'Learning Disability Services', label: 'Standard 1 label', default: 'NICE NG11, Challenging Behaviour and Learning Disabilities' },
  { key: 'learning-disability.std.1.note', group: 'Learning Disability Services', label: 'Standard 1 note', multiline: true, default: 'PBS must be the primary framework for any behaviour that challenges, before restriction is considered.' },
  { key: 'learning-disability.std.2.label', group: 'Learning Disability Services', label: 'Standard 2 label', default: 'CQC Regulation 13, Safeguarding' },
  { key: 'learning-disability.std.2.note', group: 'Learning Disability Services', label: 'Standard 2 note', multiline: true, default: 'Safeguarding procedures must be accessible to all staff across residential, community, and day settings.' },
  { key: 'learning-disability.std.3.label', group: 'Learning Disability Services', label: 'Standard 3 label', default: 'Mental Capacity Act 2005' },
  { key: 'learning-disability.std.3.note', group: 'Learning Disability Services', label: 'Standard 3 note', multiline: true, default: "Every decision made on a person's behalf must follow a documented best interests process." },
  { key: 'learning-disability.channel', group: 'Learning Disability Services', label: 'Example channel', default: 'Email' },
  { key: 'learning-disability.question', group: 'Learning Disability Services', label: 'Example question', multiline: true, default: 'A service user has started repeatedly hitting themselves and it is escalating. What does the restrictive practice policy say about physical intervention and who has to authorise it?' },
  { key: 'learning-disability.src.1', group: 'Learning Disability Services', label: 'Source 1', default: 'Restrictive Practice and Physical Intervention Policy' },
  { key: 'learning-disability.src.2', group: 'Learning Disability Services', label: 'Source 2', default: 'Positive Behaviour Support Policy' },
  { key: 'learning-disability.src.3', group: 'Learning Disability Services', label: 'Source 3', default: 'NICE NG11, Challenging Behaviour and Learning Disabilities' },
  { key: 'learning-disability.ans.1', group: 'Learning Disability Services', label: 'Answer point 1', multiline: true, default: 'The PBS-guided de-escalation steps your policy requires before any physical intervention is considered' },
  { key: 'learning-disability.ans.2', group: 'Learning Disability Services', label: 'Answer point 2', multiline: true, default: 'Which specific physical interventions are permitted under your policy and which are prohibited' },
  { key: 'learning-disability.ans.3', group: 'Learning Disability Services', label: 'Answer point 3', multiline: true, default: 'The authorisation requirement, including who must be notified and within what timeframe' },
  { key: 'learning-disability.ans.4', group: 'Learning Disability Services', label: 'Answer point 4', multiline: true, default: 'Post-incident recording obligations, including body map completion and the debrief process' },

  // ── Setting: Reablement and Intermediate Care ──
  { key: 'reablement.name', group: 'Reablement and Intermediate Care', label: 'Name', default: 'Reablement and Intermediate Care' },
  { key: 'reablement.headline', group: 'Reablement and Intermediate Care', label: 'Headline', default: 'Rapid onboarding and consistent practice during short, intensive care episodes.' },
  { key: 'reablement.desc', group: 'Reablement and Intermediate Care', label: 'Description', rich: true, default: 'Reablement services are time-limited and intensely goal-focused, with staff often joining at short notice. CareStreamAI ensures your full procedure library is available to every team member from their very first shift.' },
  { key: 'reablement.point.1', group: 'Reablement and Intermediate Care', label: 'Point 1', multiline: true, default: 'New staff access your full procedure library from day one, without waiting for a formal induction session.' },
  { key: 'reablement.point.2', group: 'Reablement and Intermediate Care', label: 'Point 2', multiline: true, default: 'Clinical reablement procedures are available to therapy and care staff in the field via the hub or voice note.' },
  { key: 'reablement.point.3', group: 'Reablement and Intermediate Care', label: 'Point 3', multiline: true, default: 'Every procedure query is logged throughout the reablement episode, providing automatic CQC evidence of consistent practice.' },
  { key: 'reablement.point.4', group: 'Reablement and Intermediate Care', label: 'Point 4', multiline: true, default: 'Managers see which procedures are being queried most during the reablement period, informing team briefings and clinical supervision.' },
  { key: 'reablement.topic.1', group: 'Reablement and Intermediate Care', label: 'Policy topic 1', default: 'Falls Prevention and Management' },
  { key: 'reablement.topic.2', group: 'Reablement and Intermediate Care', label: 'Policy topic 2', default: 'Reablement Goal Setting' },
  { key: 'reablement.topic.3', group: 'Reablement and Intermediate Care', label: 'Policy topic 3', default: 'Moving and Handling' },
  { key: 'reablement.topic.4', group: 'Reablement and Intermediate Care', label: 'Policy topic 4', default: 'Infection Control' },
  { key: 'reablement.topic.5', group: 'Reablement and Intermediate Care', label: 'Policy topic 5', default: 'Medication Administration' },
  { key: 'reablement.topic.6', group: 'Reablement and Intermediate Care', label: 'Policy topic 6', default: 'Discharge Planning' },
  { key: 'reablement.std.1.label', group: 'Reablement and Intermediate Care', label: 'Standard 1 label', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'reablement.std.1.note', group: 'Reablement and Intermediate Care', label: 'Standard 1 note', multiline: true, default: 'Falls management and manual handling procedures must be accessible to all reablement staff in the field.' },
  { key: 'reablement.std.2.label', group: 'Reablement and Intermediate Care', label: 'Standard 2 label', default: 'CQC Regulation 17, Good Governance' },
  { key: 'reablement.std.2.note', group: 'Reablement and Intermediate Care', label: 'Standard 2 note', multiline: true, default: 'Goal progress, incidents, and care decisions must be recorded throughout the reablement episode.' },
  { key: 'reablement.std.3.label', group: 'Reablement and Intermediate Care', label: 'Standard 3 label', default: 'NICE NG27, Rehabilitation After Critical Illness' },
  { key: 'reablement.std.3.note', group: 'Reablement and Intermediate Care', label: 'Standard 3 note', multiline: true, default: 'Rehabilitation goals must be person-centred, time-limited, and reviewed regularly with the clinical team.' },
  { key: 'reablement.channel', group: 'Reablement and Intermediate Care', label: 'Example channel', default: 'Chat' },
  { key: 'reablement.question', group: 'Reablement and Intermediate Care', label: 'Example question', multiline: true, default: "A service user attempted to stand from the chair without prompting and lost balance. They were not injured but are now unsettled. What is the falls protocol during a reablement episode and do I adjust today's goal?" },
  { key: 'reablement.src.1', group: 'Reablement and Intermediate Care', label: 'Source 1', default: 'Falls Prevention and Management Policy' },
  { key: 'reablement.src.2', group: 'Reablement and Intermediate Care', label: 'Source 2', default: 'Reablement Goal Management Protocol' },
  { key: 'reablement.src.3', group: 'Reablement and Intermediate Care', label: 'Source 3', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'reablement.ans.1', group: 'Reablement and Intermediate Care', label: 'Answer point 1', multiline: true, default: 'Post-incident checks your policy requires, including pain assessment and neurological observations' },
  { key: 'reablement.ans.2', group: 'Reablement and Intermediate Care', label: 'Answer point 2', multiline: true, default: 'Your protocol for pausing or modifying a reablement goal following a near-miss incident' },
  { key: 'reablement.ans.3', group: 'Reablement and Intermediate Care', label: 'Answer point 3', multiline: true, default: 'Who to notify, including the allocated occupational therapist or physiotherapist, and within what timeframe' },
  { key: 'reablement.ans.4', group: 'Reablement and Intermediate Care', label: 'Answer point 4', multiline: true, default: 'Incident recording requirements and what must be flagged in the next handover' },

  // ── Setting: Community Care and Outreach ──
  { key: 'community-care.name', group: 'Community Care and Outreach', label: 'Name', default: 'Community Care and Outreach' },
  { key: 'community-care.headline', group: 'Community Care and Outreach', label: 'Headline', default: 'Procedure access for staff who are never at a desk.' },
  { key: 'community-care.desc', group: 'Community Care and Outreach', label: 'Description', rich: true, default: 'Community care and outreach workers operate entirely in the field, often without access to an office, a desktop, or a colleague nearby. CareStreamAI gives them full procedure access via the channels they already use.' },
  { key: 'community-care.point.1', group: 'Community Care and Outreach', label: 'Point 1', multiline: true, default: 'Lone workers check safeguarding, consent, capacity, and incident procedures via the hub or voice note in any community setting.' },
  { key: 'community-care.point.2', group: 'Community Care and Outreach', label: 'Point 2', multiline: true, default: 'Policy updates reach the entire community workforce instantly, with access tracked so managers know the change has arrived.' },
  { key: 'community-care.point.3', group: 'Community Care and Outreach', label: 'Point 3', multiline: true, default: 'All three channels (chat, email, and voice) suit staff without regular access to a desk or an office computer.' },
  { key: 'community-care.point.4', group: 'Community Care and Outreach', label: 'Point 4', multiline: true, default: 'Every interaction is logged, supporting lone working safeguards and providing automatic evidence for CQC and commissioning audits.' },
  { key: 'community-care.topic.1', group: 'Community Care and Outreach', label: 'Policy topic 1', default: 'Lone Working and Personal Safety' },
  { key: 'community-care.topic.2', group: 'Community Care and Outreach', label: 'Policy topic 2', default: 'Safeguarding Adults' },
  { key: 'community-care.topic.3', group: 'Community Care and Outreach', label: 'Policy topic 3', default: 'Financial Abuse and Exploitation' },
  { key: 'community-care.topic.4', group: 'Community Care and Outreach', label: 'Policy topic 4', default: 'Mental Capacity and Consent' },
  { key: 'community-care.topic.5', group: 'Community Care and Outreach', label: 'Policy topic 5', default: 'Medication Administration' },
  { key: 'community-care.topic.6', group: 'Community Care and Outreach', label: 'Policy topic 6', default: 'Infection Control' },
  { key: 'community-care.std.1.label', group: 'Community Care and Outreach', label: 'Standard 1 label', default: 'CQC Regulation 13, Safeguarding Service Users' },
  { key: 'community-care.std.1.note', group: 'Community Care and Outreach', label: 'Standard 1 note', multiline: true, default: 'Staff must recognise, report, and document safeguarding concerns in any community setting.' },
  { key: 'community-care.std.2.label', group: 'Community Care and Outreach', label: 'Standard 2 label', default: 'Care Act 2014, Section 42' },
  { key: 'community-care.std.2.note', group: 'Community Care and Outreach', label: 'Standard 2 note', multiline: true, default: 'Safeguarding enquiries must be initiated when abuse or neglect is suspected, regardless of location.' },
  { key: 'community-care.std.3.label', group: 'Community Care and Outreach', label: 'Standard 3 label', default: 'CQC Regulation 12, Safe Care and Treatment' },
  { key: 'community-care.std.3.note', group: 'Community Care and Outreach', label: 'Standard 3 note', multiline: true, default: 'Lone workers must have access to safe care procedures during every community visit.' },
  { key: 'community-care.channel', group: 'Community Care and Outreach', label: 'Example channel', default: 'Voice' },
  { key: 'community-care.question', group: 'Community Care and Outreach', label: 'Example question', multiline: true, default: 'A service user has told me that their family member has been taking money from them without permission. What is the safeguarding procedure I need to follow right now, while I am still at the address?' },
  { key: 'community-care.src.1', group: 'Community Care and Outreach', label: 'Source 1', default: 'Safeguarding Adults Policy' },
  { key: 'community-care.src.2', group: 'Community Care and Outreach', label: 'Source 2', default: 'Financial Abuse and Exploitation Procedure' },
  { key: 'community-care.src.3', group: 'Community Care and Outreach', label: 'Source 3', default: 'CQC Regulation 13, Safeguarding Service Users' },
  { key: 'community-care.ans.1', group: 'Community Care and Outreach', label: 'Answer point 1', multiline: true, default: 'Immediate steps your policy requires, including not investigating yourself or confronting the alleged perpetrator' },
  { key: 'community-care.ans.2', group: 'Community Care and Outreach', label: 'Answer point 2', multiline: true, default: 'How to make a safeguarding referral to the local authority while still at the address' },
  { key: 'community-care.ans.3', group: 'Community Care and Outreach', label: 'Answer point 3', multiline: true, default: "Your policy's confidentiality and disclosure rules, including when you can share information without consent" },
  { key: 'community-care.ans.4', group: 'Community Care and Outreach', label: 'Answer point 4', multiline: true, default: 'What to record today, including the exact words used by the service user, before leaving the visit' },

  // Disclaimer
  { key: 'disclaimer.label', group: 'Important notice', label: 'Eyebrow', default: 'Important notice' },
  { key: 'disclaimer.p1', group: 'Important notice', label: 'Paragraph 1', rich: true, default: "CareStreamAI does not provide professional, legal, clinical, or regulatory advice of any kind. The system retrieves and presents accurate information drawn directly from your organisation's own approved policies, procedures, and handbooks, and from publicly available external regulations and guidance. All responses reflect the content of those documents as uploaded and maintained by your organisation." },
  { key: 'disclaimer.p2', group: 'Important notice', label: 'Paragraph 2', rich: true, default: 'Staff should always exercise their own professional judgement and, where required, seek guidance from a registered manager, clinician, or qualified professional. CareStreamAI is an information access tool. It does not replace supervision, professional registration, clinical decision-making, or the duty of care that rests with your organisation and its staff.' },

  // Cross-cutting benefits strip
  { key: 'strip.label', group: 'Across every setting', label: 'Eyebrow', default: 'Across every setting' },
  { key: 'strip.1.heading', group: 'Across every setting', label: 'Item 1 heading', default: 'All three channels' },
  { key: 'strip.1.body', group: 'Across every setting', label: 'Item 1 body', multiline: true, default: 'Chat, email, and voice. Staff access policies whichever way suits their role and environment.' },
  { key: 'strip.2.heading', group: 'Across every setting', label: 'Item 2 heading', default: '50 plus languages' },
  { key: 'strip.2.body', group: 'Across every setting', label: 'Item 2 body', multiline: true, default: 'Every staff member gets the same quality of policy access regardless of their first language.' },
  { key: 'strip.3.heading', group: 'Across every setting', label: 'Item 3 heading', default: 'CQC evidence built in' },
  { key: 'strip.3.body', group: 'Across every setting', label: 'Item 3 body', multiline: true, default: 'Every query is logged. Your CQC Readiness Report is generated automatically, not assembled under pressure.' },
  { key: 'strip.4.heading', group: 'Across every setting', label: 'Item 4 heading', default: 'Always up to date' },
  { key: 'strip.4.body', group: 'Across every setting', label: 'Item 4 body', multiline: true, default: 'Upload a new policy version and CareStreamAI answers from it immediately. Staff never read superseded guidance.' },

  // Persona: Registered Manager
  { key: 'persona.1.badge', group: 'Role: Registered Manager', label: 'Badge', default: 'Registered Manager' },
  { key: 'persona.1.headline', group: 'Role: Registered Manager', label: 'Headline', default: 'Policy support for your team, even when you are not there.' },
  { key: 'persona.1.benefit.1', group: 'Role: Registered Manager', label: 'Benefit 1', multiline: true, default: 'Staff on night shifts get instant policy answers without calling you, reducing out-of-hours interruptions and giving your team confidence to act correctly.' },
  { key: 'persona.1.benefit.2', group: 'Role: Registered Manager', label: 'Benefit 2', multiline: true, default: 'Your CQC Readiness Report is built automatically, showing inspectors exactly how your team engages with your policies.' },
  { key: 'persona.1.benefit.3', group: 'Role: Registered Manager', label: 'Benefit 3', multiline: true, default: 'When a policy is updated, CareStreamAI tracks whether staff accessed the new version, so you know the change actually reached your team.' },
  { key: 'persona.1.benefit.4', group: 'Role: Registered Manager', label: 'Benefit 4', multiline: true, default: 'Policy gap detection tells you what your library is missing before a CQC inspector asks.' },

  // Persona: HR Director and People Lead
  { key: 'persona.2.badge', group: 'Role: HR Director and People Lead', label: 'Badge', default: 'HR Director and People Lead' },
  { key: 'persona.2.headline', group: 'Role: HR Director and People Lead', label: 'Headline', default: 'Stop answering the same questions. Let your handbook answer them.' },
  { key: 'persona.2.benefit.1', group: 'Role: HR Director and People Lead', label: 'Benefit 1', multiline: true, default: 'Annual leave, sickness procedures, disciplinary processes: staff get instant answers from your actual handbook, 24 hours a day, without HR intervention.' },
  { key: 'persona.2.benefit.2', group: 'Role: HR Director and People Lead', label: 'Benefit 2', multiline: true, default: 'New starters, including international recruits, can ask questions about their employment terms in their own language from day one.' },
  { key: 'persona.2.benefit.3', group: 'Role: HR Director and People Lead', label: 'Benefit 3', multiline: true, default: 'Handbook access is fully logged, so you can see which sections staff query most and identify where onboarding communications need improving.' },
  { key: 'persona.2.benefit.4', group: 'Role: HR Director and People Lead', label: 'Benefit 4', multiline: true, default: 'Reduces repetitive HR query load, freeing your team for work that requires human judgement.' },

  // Persona: Operations Director
  { key: 'persona.3.badge', group: 'Role: Operations Director', label: 'Badge', default: 'Operations Director' },
  { key: 'persona.3.headline', group: 'Role: Operations Director', label: 'Headline', default: 'One policy library. Consistent answers. Across every service.' },
  { key: 'persona.3.benefit.1', group: 'Role: Operations Director', label: 'Benefit 1', multiline: true, default: 'All services draw from the same centrally managed, approved policy library, eliminating version drift and inconsistent practice.' },
  { key: 'persona.3.benefit.2', group: 'Role: Operations Director', label: 'Benefit 2', multiline: true, default: 'Per-service analytics show which locations are engaged and where to focus support.' },
  { key: 'persona.3.benefit.3', group: 'Role: Operations Director', label: 'Benefit 3', multiline: true, default: 'When a policy is updated centrally, you can see which services accessed the new version and confirm the change reached the whole team.' },
  { key: 'persona.3.benefit.4', group: 'Role: Operations Director', label: 'Benefit 4', multiline: true, default: 'Group CQC Readiness Reports cover all registered services in a single export.' },

  // Persona: Finance Director and Owner
  { key: 'persona.4.badge', group: 'Role: Finance Director and Owner', label: 'Badge', default: 'Finance Director and Owner' },
  { key: 'persona.4.headline', group: 'Role: Finance Director and Owner', label: 'Headline', default: 'A return on investment you can calculate in under five minutes.' },
  { key: 'persona.4.benefit.1', group: 'Role: Finance Director and Owner', label: 'Benefit 1', multiline: true, default: 'If CareStreamAI saves each manager one hour per week of policy query handling, it pays for itself in the first month.' },
  { key: 'persona.4.benefit.2', group: 'Role: Finance Director and Owner', label: 'Benefit 2', multiline: true, default: 'Reduces procedural risk by ensuring staff act on correct, approved guidance, with a full audit trail to demonstrate due diligence.' },
  { key: 'persona.4.benefit.3', group: 'Role: Finance Director and Owner', label: 'Benefit 3', multiline: true, default: 'Reduces CQC preparation time: inspection evidence is built automatically, not assembled manually under pressure.' },
  { key: 'persona.4.benefit.4', group: 'Role: Finance Director and Owner', label: 'Benefit 4', multiline: true, default: 'Improves staff confidence and reduces early turnover, particularly for international recruits who gain full policy access in their own language from day one.' },
]
