// The audit report as a real PDF: generated by the server, branded with the home's logo, saved against
// the audit when it is completed (or signed off, when manager approval is on) and emailed to admins.
//
// Built from buildAuditReport, the same data the report page and printed view use. pdfkit, as for policy
// PDFs (see services/policy/policy-pdf.ts for why, and for the standard-font imports below).

import PDFDocument from 'pdfkit'
import sharp from 'sharp'
import 'pdfkit/standard-fonts/Helvetica'
import 'pdfkit/standard-fonts/HelveticaBold'
import 'pdfkit/standard-fonts/HelveticaOblique'
import { randomUUID } from 'crypto'
import { prisma } from '../../db/client'
import { logoForPdf } from '../policy/policy-pdf'
import { downloadFile, uploadAuditEvidence } from '../storage/s3'
import { buildAuditReport } from './report'
import { actionsDeadlineLabel, isScored } from '../../lib/audit-questions'

const db = prisma as any
const TEAL = '#0f766e', DARK = '#111827', MID = '#6b7280', LINE = '#e5e7eb', RED = '#b91c1c', GREEN = '#15803d', AMBER = '#b45309'
const PAGE = { w: 595.28, h: 841.89, m: 42 }
const PHOTOS_PER_QUESTION = 3

// Standard PDF fonts only cover Windows-1252. Swap common punctuation and drop the rest, so an emoji
// or an unusual character in a note can never break the document.
function clean(v: any): string {
  return String(v ?? '')
    .replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/[–—]/g, '-').replace(/…/g, '...')
    .replace(/[•●]/g, '-').replace(/ /g, ' ')
    .replace(/[^\x09\x0A\x0D\x20-\x7E -ÿ€]/g, '')
}
const dateLong = (d: any) => d ? new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Europe/London' }) : ''
const monthLong = (d: any) => d ? new Date(d).toLocaleDateString('en-GB', { month: 'long', year: 'numeric', timeZone: 'Europe/London' }) : ''

async function thumb(buf: Buffer): Promise<Buffer | null> {
  try { return await sharp(buf).rotate().resize({ width: 320, height: 320, fit: 'inside', withoutEnlargement: true }).jpeg({ quality: 70 }).toBuffer() } catch { return null }
}

export async function renderAuditReportPdf(tenantId: string, runId: string): Promise<{ pdf: Buffer; report: any } | null> {
  const report = await buildAuditReport(tenantId, runId)
  if (!report) return null
  const run = await db.auditRun.findUnique({ where: { id: runId }, select: { auditor_signature_key: true, manager_signature_key: true } })
  const [tenant, evidence, actions] = await Promise.all([
    db.tenant.findUnique({ where: { id: tenantId }, select: { logo_url: true } }),
    db.auditAnswerEvidence.findMany({ where: { run_id: runId }, orderBy: { created_at: 'asc' }, select: { question_id: true, s3_key: true } }),
    db.auditAction.findMany({ where: { run_id: runId }, orderBy: { created_at: 'asc' } }),
  ])
  const logo = await logoForPdf(tenant?.logo_url)
  const load = async (key?: string | null) => { if (!key) return null; try { return await downloadFile(key) } catch { return null } }
  const [auditorSig, managerSig] = await Promise.all([load(run?.auditor_signature_key), load(run?.manager_signature_key)])
  const photos = new Map<string, Buffer[]>()
  for (const e of evidence as any[]) {
    const list = photos.get(e.question_id) ?? []
    if (list.length >= PHOTOS_PER_QUESTION) continue
    const raw = await load(e.s3_key)
    const t = raw ? await thumb(raw) : null
    if (t) { list.push(t); photos.set(e.question_id, list) }
  }

  const doc = new PDFDocument({ size: 'A4', margin: PAGE.m, bufferPages: true, info: { Title: clean(`${report.audit_name} audit report`), Author: clean(report.organisation) } })
  const chunks: Buffer[] = []
  doc.on('data', (c: Buffer) => chunks.push(c))
  const done = new Promise<Buffer>(resolve => doc.on('end', () => resolve(Buffer.concat(chunks))))
  const width = PAGE.w - PAGE.m * 2
  const bottom = PAGE.h - PAGE.m - 24
  const ensure = (h: number) => { if (doc.y + h > bottom) doc.addPage() }
  const rule = (colour = LINE) => { doc.moveTo(PAGE.m, doc.y).lineTo(PAGE.w - PAGE.m, doc.y).lineWidth(0.7).strokeColor(colour).stroke(); doc.moveDown(0.4) }
  const heading = (text: string) => {
    ensure(80)   // keep a heading with at least a little of what follows it
    doc.moveDown(0.6)
    const y = doc.y
    doc.rect(PAGE.m, y, width, 20).fill(TEAL)
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(10.5).text(clean(text).toUpperCase(), PAGE.m + 8, y + 5.5, { width: width - 16 })
    doc.y = y + 28
    doc.x = PAGE.m
  }

  // ── Letterhead
  const top = doc.y
  if (logo) { try { doc.image(logo, PAGE.m, top, { fit: [140, 44] }) } catch { /* no logo */ } }
  doc.fillColor(MID).font('Helvetica').fontSize(9).text(clean(report.organisation), PAGE.m, top + 4, { width, align: 'right' })
  doc.y = top + 52
  const scopeLabel: Record<string, string> = { resident: 'Resident', staff: 'Staff member', room: 'Room' }
  const title = report.subject ? `${report.audit_name}: ${scopeLabel[report.subject_scope] ?? ''} ${report.subject}${report.subject_room ? ` (Room ${report.subject_room})` : ''}` : report.audit_name
  doc.fillColor(DARK).font('Helvetica-Bold').fontSize(18).text(clean(title), PAGE.m, doc.y, { width })
  doc.moveDown(0.3)
  doc.moveTo(PAGE.m, doc.y).lineTo(PAGE.w - PAGE.m, doc.y).lineWidth(2.5).strokeColor(TEAL).stroke()
  doc.moveDown(0.7)

  // ── Details
  const details: Array<[string, string]> = [
    ['Audit period', monthLong(report.audit_month)],
    ['Auditor', [report.auditor_name, report.auditor_role].filter(Boolean).join(', ')],
    ['Completed', report.completed_at ? dateLong(report.completed_at) : 'Not completed'],
    ['Audit version', report.template_version ? `Version ${report.template_version}` : ''],
    ['Sign-off', report.approval_status === 'approved' ? `Approved by ${report.approved_by_name ?? 'the manager'}${report.approved_at ? ` on ${dateLong(report.approved_at)}` : ''}` : report.approval_status === 'pending_manager' ? 'Awaiting manager approval' : ''],
  ].filter(([, v]) => v) as Array<[string, string]>
  for (const [k, v] of details) {
    const y = doc.y
    doc.fillColor(MID).font('Helvetica').fontSize(9).text(k, PAGE.m, y, { width: 110 })
    doc.fillColor(DARK).font('Helvetica').fontSize(9.5).text(clean(v), PAGE.m + 115, y, { width: width - 115 })
    doc.moveDown(0.25)
  }

  // ── Scores
  const scoredOf = (qs: any[]) => qs.filter(q => isScored(q) && (q.outcome === 'pass' || q.outcome === 'fail'))
  const all = report.sections.flatMap((s: any) => s.questions)
  const allScored = scoredOf(all)
  if (allScored.length) {
    const pass = allScored.filter((q: any) => q.outcome === 'pass').length
    const pct = Math.round((pass / allScored.length) * 100)
    heading('Results')
    const ry = doc.y
    doc.fillColor(pct >= 80 ? GREEN : pct >= 60 ? AMBER : RED).font('Helvetica-Bold').fontSize(22).text(`${pct}%`, PAGE.m, ry, { width: 80, lineBreak: false })
    doc.fillColor(MID).font('Helvetica').fontSize(10).text(`${pass} of ${allScored.length} scored checks met`, PAGE.m + 80, ry + 8, { width: width - 80, lineBreak: false })
    doc.x = PAGE.m
    doc.y = ry + 34
    for (const s of report.sections) {
      const sc = scoredOf(s.questions)
      if (!sc.length) continue
      const p = sc.filter((q: any) => q.outcome === 'pass').length
      const sp = Math.round((p / sc.length) * 100)
      ensure(16)
      const y = doc.y
      doc.fillColor(DARK).font('Helvetica').fontSize(9).text(clean(s.title), PAGE.m, y, { width: 250, lineBreak: false, ellipsis: true })
      doc.rect(PAGE.m + 260, y + 2, 180, 6).fill('#f3f4f6')
      doc.rect(PAGE.m + 260, y + 2, Math.max(2, 1.8 * sp), 6).fill(sp >= 80 ? GREEN : sp >= 60 ? AMBER : RED)
      doc.fillColor(MID).fontSize(9).text(`${p}/${sc.length} (${sp}%)`, PAGE.m + 450, y, { width: width - 450, align: 'right' })
      doc.y = y + 14
    }
  }

  // ── Answers
  const outcomeLabel: Record<string, [string, string]> = { pass: ['Met', GREEN], fail: ['Not met', RED], na: ['N/A', MID], unanswered: ['Not answered', AMBER], info: ['', DARK] }
  for (const s of report.sections) {
    heading(s.title)
    for (const q of s.questions) {
      ensure(46)
      const narrative = q.question_type === 'findings' || q.question_type === 'free_text'
      doc.fillColor(DARK).font('Helvetica-Bold').fontSize(10).text(clean(q.question), PAGE.m, doc.y, { width })
      if (q.quality_statement) doc.fillColor(MID).font('Helvetica-Oblique').fontSize(8).text(clean(`CQC quality statement: ${q.quality_statement}`), { width })
      if (!narrative) {
        const [label, colour] = outcomeLabel[q.outcome] ?? ['', DARK]
        const noNote = q.answer_yn === false && q.no_compliant === true ? ' (No is the correct answer)' : ''
        doc.fillColor(DARK).font('Helvetica').fontSize(9.5).text(clean(`Answer: ${q.answer_text}${noNote}`), { width, continued: !!label })
        if (label) doc.fillColor(colour).font('Helvetica-Bold').text(`   ${label}`)
      }
      if (q.outcome_text) doc.fillColor(DARK).font('Helvetica').fontSize(9.5).text(clean(`${narrative ? 'Findings' : 'Notes'}: ${q.outcome_text}`), { width })
      if (q.actions_text && q.question_type !== 'free_text') doc.fillColor(DARK).font('Helvetica').fontSize(9.5).text(clean(`Actions: ${q.actions_text}`), { width })
      const pics = photos.get(q.id) ?? []
      if (pics.length) {
        ensure(96)
        const y = doc.y + 4
        pics.forEach((p, i) => { try { doc.image(p, PAGE.m + i * 120, y, { fit: [110, 86] }) } catch { /* skip */ } })
        doc.y = y + 92
      }
      doc.moveDown(0.3)
      rule()
    }
  }

  // ── Summary
  if (report.strengths || report.improvements || report.actions_deadline) {
    heading('Audit summary')
    for (const [k, v] of [['Strengths identified', report.strengths], ['Areas requiring improvement', report.improvements], ['Deadline for actions', actionsDeadlineLabel(report.actions_deadline)]] as Array<[string, string]>) {
      if (!v) continue
      ensure(30)
      doc.fillColor(DARK).font('Helvetica-Bold').fontSize(10).text(k)
      doc.font('Helvetica').fontSize(9.5).text(clean(v), { width })
      doc.moveDown(0.4)
    }
  }

  // ── AI recommendations (## headings, - bullets, **bold** markers dropped)
  if (report.ai_recommendations) {
    heading('Recommendations')
    for (const raw of String(report.ai_recommendations).split('\n')) {
      const line = raw.trim()
      if (!line) { doc.moveDown(0.25); continue }
      ensure(18)
      const text = clean(line.replace(/\*\*/g, ''))
      if (line.startsWith('## ')) { doc.moveDown(0.3); doc.fillColor(TEAL).font('Helvetica-Bold').fontSize(10.5).text(text.slice(3), { width }) }
      else if (/^[-*] /.test(line)) doc.fillColor(DARK).font('Helvetica').fontSize(9.5).text(`-  ${text.slice(2)}`, PAGE.m + 8, doc.y, { width: width - 8 })
      else doc.fillColor(DARK).font('Helvetica').fontSize(9.5).text(text, PAGE.m, doc.y, { width })
    }
  }

  // ── Action plan
  if ((actions as any[]).length) {
    heading('Action plan')
    for (const a of actions as any[]) {
      ensure(40)
      const who = a.is_external ? `External: ${a.external_name ?? 'contractor'}` : a.assigned_to ?? 'Unassigned'
      const status = a.status === 'done' ? `Done${a.done_at ? ` ${dateLong(a.done_at)}` : ''}` : a.status === 'in_progress' ? 'In progress' : 'Open'
      doc.fillColor(DARK).font('Helvetica-Bold').fontSize(9.5).text(clean(a.description), PAGE.m, doc.y, { width })
      doc.fillColor(MID).font('Helvetica').fontSize(8.5).text(clean(`${a.priority} · ${who}${a.due_date ? ` · due ${dateLong(a.due_date)}` : ''} · ${status}`), { width })
      if (a.completion_note) doc.fillColor(DARK).fontSize(9).text(clean(`What was done: ${a.completion_note}`), { width })
      if (a.verified_result) doc.fillColor(a.verified_result === 'fixed' ? GREEN : RED).fontSize(9).text(a.verified_result === 'fixed' ? 'Checked at the next audit: still fixed' : 'Checked at the next audit: not fixed, reopened', { width })
      doc.moveDown(0.35)
    }
  }

  // ── Signatures
  if (auditorSig || managerSig || report.approved_by_name) {
    heading('Signatures')
    ensure(110)
    const y = doc.y
    const col = (x: number, label: string, sig: Buffer | null, name: string, when: string) => {
      doc.fillColor(MID).font('Helvetica').fontSize(8.5).text(label, x, y, { width: width / 2 - 10 })
      if (sig) { try { doc.image(sig, x, y + 14, { fit: [180, 56] }) } catch { /* skip */ } }
      doc.moveTo(x, y + 74).lineTo(x + 200, y + 74).lineWidth(0.7).strokeColor(LINE).stroke()
      doc.fillColor(DARK).font('Helvetica-Bold').fontSize(9.5).text(clean(name), x, y + 80, { width: width / 2 - 10 })
      if (when) doc.fillColor(MID).font('Helvetica').fontSize(8.5).text(when, x, y + 94, { width: width / 2 - 10 })
    }
    if (auditorSig || report.auditor_signed_name) col(PAGE.m, 'Auditor', auditorSig, report.auditor_signed_name ?? report.auditor_name ?? '', dateLong(report.auditor_signed_at))
    if (managerSig || report.approved_by_name) col(PAGE.m + width / 2, 'Manager sign-off', managerSig, report.approved_by_name ?? '', dateLong(report.manager_signed_at ?? report.approved_at))
    doc.y = y + 112
  }

  // ── Footer on every page
  const range = doc.bufferedPageRange()
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i)
    // The footer sits in the bottom margin; with the margin in place pdfkit would start a new page for it.
    const margin = doc.page.margins.bottom
    doc.page.margins.bottom = 0
    doc.fillColor(MID).font('Helvetica').fontSize(7.5)
      .text(clean(`${report.audit_name} · ${report.organisation} · Generated ${dateLong(new Date())} · Page ${i + 1} of ${range.count}`), PAGE.m, PAGE.h - PAGE.m + 6, { width, align: 'center', lineBreak: false })
    doc.page.margins.bottom = margin
  }
  doc.end()
  return { pdf: await done, report }
}

// Generate, save against the run, and email to the home's admins (unless the home has turned that off).
// Returns 'emailed', 'stored' (saved, not emailed) or 'none'.
export async function generateAndStoreAuditReport(tenantId: string, runId: string, opts: { email: boolean }): Promise<'emailed' | 'stored' | 'none'> {
  const out = await renderAuditReportPdf(tenantId, runId)
  if (!out) return 'none'
  const key = await uploadAuditEvidence({ tenantId, runId, key: `report-${randomUUID()}.pdf`, buffer: out.pdf, mimeType: 'application/pdf' })
  await db.auditRun.update({ where: { id: runId }, data: { report_pdf_key: key, report_generated_at: new Date() } })
  if (!opts.email) return 'stored'
  const t = await db.tenant.findUnique({ where: { id: tenantId }, select: { name: true, organisation_details: true } })
  if ((t?.organisation_details as any)?.audit_report_email === 'off') return 'stored'
  const admins = await db.user.findMany({ where: { tenant_id: tenantId, role: 'admin', is_active: true }, select: { id: true } })
  const { notifyUsers } = await import('../../lib/notify')
  const { sendAuditReportEmail } = await import('../email/outbound')
  await notifyUsers(tenantId, 'audit_updates', (admins as any[]).map(a => a.id), (email, name) => sendAuditReportEmail({
    to: email, name, orgName: t?.name ?? '', auditName: out.report.audit_name, subject: out.report.subject ?? null,
    period: monthLong(out.report.audit_month), approved: out.report.approval_status === 'approved', runId, pdf: out.pdf,
  }))
  return 'emailed'
}

export function reportFileName(report: { audit_name: string; audit_month: any; subject?: string | null }): string {
  const slug = (s: string) => clean(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
  const month = report.audit_month ? new Date(report.audit_month).toISOString().slice(0, 7) : ''
  return `${[slug(report.audit_name), report.subject ? slug(report.subject) : '', month].filter(Boolean).join('-')}.pdf`
}
