import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'complex-care',
  label: 'Complex Care',
  settingNoun: 'complex care service',
  navDescription: 'Your clinical protocols and client care plans, exactly as trained, for support workers delivering complex care at home.',
  iconKey: 'activity',
  meta: {
    title: 'CareStream for Complex Care',
    description: 'CareStream gives complex care support workers instant access to your clinical protocols and the specific client care plan they are working to, in any language, in the person’s own home, with every answer cited and every query logged for inspection.',
    ogDescription: 'Your clinical protocols and the specific client’s care plan, exactly as trained, for support workers delivering complex care at home.',
  },
  hero: {
    h1: 'The exact protocol, and this client’s care plan, in the person’s own home.',
    subtitle: 'Complex care happens one to one, often alone, in someone’s home, with very high clinical risk and the family in the room. CareStream gives your trained support workers instant access to your clinical protocols and the specific client’s care plan, grounded in your own uploaded documents, so they carry out delegated healthcare tasks exactly as documented and exactly as trained.',
  },
  mockup: {
    orgName: 'Meridian Complex Care',
    badge: 'On shift',
    tabs: ['Care plan', 'Policies', 'Training', 'CQC'],
    question: 'What suction technique should I use for my client’s tracheostomy?',
    policyName: 'From your client’s Tracheostomy Care Plan',
    answer: 'Follow the suction technique and pressure set out in this client’s care plan and your training. Suction on withdrawal only, keep it brief, and stop and escalate if you see any signs of distress or obstruction.',
    citation: 'Tracheostomy Care Plan · Section 3',
    followups: ['What are the signs of a blocked tube?', 'Who do I escalate to?'],
  },
  challenge: {
    h2: 'Very high clinical risk, one support worker, and a regulator that looks closely.',
    para1: 'A support worker is alone in a client’s home, carrying out a delegated healthcare task such as tracheostomy suction or PEG feeding, and needs to be certain of the exact technique set out for this particular person. The clinical lead is not in the room, the family is, and there is no folder to leaf through under pressure. A worker whose first language is not English needs to be just as sure as a colleague who speaks English fluently.',
    para2: 'Complex care at home draws close CQC scrutiny, particularly around safe delivery of delegated healthcare tasks and how staff follow each client’s plan in practice. CareStream closes the gap between the documented protocol and what happens in the home, for every support worker, on every visit.',
    items: [
      { iconKey: 'activity', title: 'Very high clinical risk', body: 'Tracheostomy, ventilation, PEG feeding, catheter care, seizure and bowel care leave no room for guessing the technique.' },
      { iconKey: 'home', title: 'Delivered alone in the home', body: 'A support worker is often one to one in the person’s own home, without a colleague or the clinical lead beside them.' },
      { iconKey: 'file', title: 'The exact protocol and this client’s plan', body: 'The right answer is the documented procedure and the specific care plan for this person, never a general rule of thumb.' },
      { iconKey: 'shield', title: 'Close CQC scrutiny', body: 'Inspectors look hard at how delegated healthcare tasks are delivered safely and how staff follow each client’s plan.' },
    ],
  },
  servicesH2: 'One platform for clinical protocols, care plans, training, audits and CQC.',
  serviceDescriptions: {
    policies: 'Your clinical protocols and each client’s care plan answerable in the home, in any language, with the source document and version cited.',
    hr: 'Your staff handbook on demand for your support workers. Leave, pay, travel and employment questions answered 24/7.',
    training: 'Modules built from your own clinical protocols, delivered in the hub, with renewal reminders so competencies stay current.',
    audits: 'Guided audits for medicines, infection prevention and care plan adherence, scored as you go and inspection-ready.',
    cqc: 'Evidence that builds itself, plus regulation coverage showing where your protocols and plans leave a gap.',
    staffq: 'Prepare your support workers for the conversations inspectors have about delegated healthcare tasks.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own protocols and care plans.',
    continuity: 'Make your continuity information instantly reachable by every support worker, in any home, on any visit.',
  },
  scenarios: {
    h2: 'How your complex care service uses CareStream, visit to visit.',
    sub: 'CareStream is not another system your team has to remember to use. It fits the moments that already happen on every visit, and gives the right answer, from the right document, at the moment it matters.',
    items: [
      { tag: 'Alone with a ventilated client', body: 'A support worker has a question about the ventilator alarm sequence for the person they support. Rather than wait for the clinical lead to call back, they ask CareStream and get the exact steps from this client’s care plan and their training, in seconds, so they respond calmly with the family looking on.' },
      { tag: 'A new worker on their first visit', body: 'A support worker new to a package is not yet sure of the bowel care routine documented for this client. Instead of guessing or improvising, they check the hub and receive the person’s own plan, so their practice matches what the client and family expect from the very first visit.' },
      { tag: 'During a PEG feed', body: 'A support worker is unsure of the flush volume or the rate set out for this client’s enteral feed. They check the care plan in the hub at the bedside, see the answer with the source, and feed exactly as documented and as they were trained.' },
      { tag: 'When a seizure starts', body: 'A client begins seizing and the support worker needs to be certain of the rescue medication protocol written for this person. They ask the hub, follow the documented steps and escalation point, and act without delay, because the answer comes from the client’s own plan.' },
      { tag: 'In a language they are confident in', body: 'A support worker whose first language is Portuguese asks a catheter care question by voice, in Portuguese, and listens to the answer read back. The guidance is exactly the same as an English-speaking colleague would receive, drawn from the same documents.' },
      { tag: 'Getting ready for inspection', body: 'Before an inspection, the registered manager sends CQC practice questions to the team, reviews who has answered, and checks the regulation coverage report to see where a protocol needs strengthening, all before the inspector arrives.' },
    ],
  },
  deepDive: {
    label: 'Clinical Procedures, Exactly As Trained',
    h2: 'The precise documented procedure, and this client’s plan, at the point of care.',
    para1: 'A support worker asks a question in plain language and gets the answer from your own clinical protocol and the specific client’s care plan, with the source and version shown. No hunting through a folder, no waiting for a callback, and no improvising in the home.',
    para2: 'Because every answer is grounded in your documents and cites them, your support workers confirm the exact procedure for the person in front of them, every time. CareStream supports them to follow your documented protocols, the client’s care plan and their training. It does not give clinical advice of its own and never replaces training or sign-off for a delegated healthcare task.',
    chips: ['Tracheostomy care', 'Ventilation', 'PEG and enteral feeding', 'Catheter care', 'Seizure management', 'Bowel care', 'Emergency protocols', 'Infection prevention'],
    panelH3: 'In the language your team thinks in.',
    panelBody: 'Your protocols and care plans stay in English. A support worker can ask in Portuguese, Romanian, Tagalog or any of over 60 languages, by typing or speaking, and hear the answer read back in the same language. Nobody is held back by a written procedure they find hard to follow at speed in the home.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for every support worker'],
  },
  outcomes: {
    h2: 'Safer delegated care, a confident workforce, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'activity', title: 'The exact protocol at the point of care', body: 'Support workers confirm the documented procedure and the client’s plan in the home, without waiting for the clinical lead.' },
      { iconKey: 'file', title: 'Care delivered to each client’s plan', body: 'Answers are grounded in the specific person’s care plan, so practice matches what is documented for them, every visit.' },
      { iconKey: 'globe', title: 'A workforce supported in its own language', body: 'Every support worker understands your protocols and the care plan, whatever language they are most confident in.' },
      { iconKey: 'graduation', title: 'Competencies kept current', body: 'Training built from your own protocols, with automatic renewal reminders and a live compliance dashboard.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, visit-to-visit use of your protocols and plans.' },
      { iconKey: 'shield', title: 'Clear about its limits', body: 'CareStream points staff to your documented procedures and the client’s plan. It never gives clinical advice of its own or replaces sign-off.' },
    ],
  },
  cqc: {
    h2: 'Built around the areas inspectors look at most.',
    intro: 'Complex care at home is assessed closely on the safe delivery of delegated healthcare tasks and on how staff follow each client’s plan. CareStream gives you evidence that your protocols and care plans are live and in use, prepares your team for inspector conversations, and shows you where your documents leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of protocol use', body: 'Every query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Staff ready to be asked', body: 'Inspector-style questions across the five key questions, answered by staff in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your protocols and care plans and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Can it answer questions about a specific client’s care plan, not just general policies?', answer: 'Yes. CareStream answers from the documents you upload, including the client care plans you add. A support worker can ask about this person’s tracheostomy suction, PEG feed or seizure protocol and get an answer drawn from that client’s own plan, with the source and version shown so they can check it.' },
    { question: 'Does it give clinical advice or replace training and sign-off?', answer: 'No. CareStream supports staff to follow your documented protocols, the client’s care plan and their training. It does not give clinical advice of its own, and it never replaces the training or sign-off required for a delegated healthcare task. Every answer cites the document it came from.' },
    { question: 'Our support workers speak many languages. Does it help?', answer: 'Yes. Staff can ask in over 60 languages and get the answer back in the same language, while your protocols and care plans stay in English. This is a real help for the international workforce in many complex care services, and the guidance is identical to what an English speaker receives.' },
    { question: 'How does it help with competencies and renewals?', answer: 'CareStream can build training modules from your own protocols, deliver them in the hub, and send automatic renewal reminders at 90, 30 and 7 days, with a manager digest and a live compliance dashboard so you can see exactly who is current and who is due.' },
    { question: 'Is client and clinical information kept private and secure?', answer: 'Yes. Your library, including the care plans you upload, is stored in an isolated environment for your service alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, and every query is logged for your audit trail.' },
    { question: 'How quickly can a complex care service get started?', answer: 'Most services are up and running the same day. You upload your protocols and client care plans, invite your team with a one-tap sign-in link, and support workers can begin asking questions straight away.' },
  ],
  cta: {
    heading: 'Give every support worker the exact protocol, and this client’s plan, in the home.',
    sub: 'See how CareStream works for your complex care service.',
  },
}
