import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'dental-practices',
  label: 'Dental Practices',
  settingNoun: 'practice',
  iconKey: 'shield',
  navDescription: 'Decontamination, radiography and emergency answers for the whole dental team, between patients.',
  meta: {
    title: 'CareStream for Dental Practices',
    description: 'CareStream gives the whole dental team instant access to your decontamination, radiography, emergency and compliance policies, in any language, between patients, with every query logged for inspection.',
    ogDescription: 'Instant access to decontamination, radiography, emergency and compliance answers for your whole dental team, in any language, between patients.',
  },
  hero: {
    h1: 'The right answer between patients, for the whole dental team, in every language they speak.',
    subtitle: 'Dental practices run small teams to a packed appointment book, with decontamination, radiography, medical emergencies and a regulator that expects CQC and GDC standards to be met together. CareStream gives every member of your team instant access to your protocols and policies, grounded in your own documents, without leaving the surgery.',
  },
  mockup: {
    orgName: 'Bridge Street Dental',
    badge: 'Between patients',
    tabs: ['Policies', 'Protocols', 'Training', 'CQC'],
    question: 'What is our decontamination process between patients?',
    policyName: 'From your Decontamination Policy',
    answer: 'Follow your decontamination cycle: clean, inspect, sterilise and store instruments correctly, and record each cycle. Use the right PPE and keep clean and dirty areas separated at all times.',
    citation: 'Decontamination Policy v2.3 · Section 3',
    followups: ['How do I record a cycle?', 'What PPE is needed?'],
  },
  challenge: {
    h2: 'A small team, a packed book, and two sets of standards to meet at once.',
    para1: 'A dental nurse needs the decontamination steps confirmed before the next patient walks in, but the practice manager is on a call and the policy folder is in the office. A new associate is unsure of your local radiography protocol. A team member whose first language is not English struggles to follow a written procedure with the next patient already waiting.',
    para2: 'Dental practices are inspected by CQC while the clinical team also works to GDC standards, all with a small team and very little spare time. CareStream closes the gap between the protocol on paper and the practice in the surgery, for every member of the team, between patients.',
    items: [
      { iconKey: 'clock', title: 'A packed appointment book', body: 'Questions about decontamination, radiography and protocols come up between patients, with no time to hunt through a folder.' },
      { iconKey: 'users', title: 'A small, mixed team', body: 'Dentists, hygienists, therapists, nurses and reception all need consistent answers from the same approved protocols.' },
      { iconKey: 'shield', title: 'Decontamination and infection control', body: 'Instrument processing, PPE and clean and dirty separation have to be right every single time, and recorded.' },
      { iconKey: 'cqc', title: 'CQC alongside GDC standards', body: 'Inspectors look at safety, radiography and emergencies, while the clinical team also works to GDC expectations.' },
    ],
  },
  servicesH2: 'One platform for protocols, training, audits and CQC.',
  serviceDescriptions: {
    policies: 'Decontamination, radiography and emergency protocols answerable in the surgery, in any language, with the source policy and version cited.',
    hr: 'Your staff handbook on demand for the whole practice. Leave, pay and employment questions answered any time.',
    training: 'Modules built from your own protocols, delivered in the hub, with renewal reminders for mandatory training.',
    audits: 'Guided audits for decontamination, infection control, radiography and health and safety, scored as you go and inspection-ready.',
    cqc: 'Evidence that builds itself, plus regulation coverage showing where your policies leave a gap.',
    staffq: 'Prepare your dentists, nurses and reception for the conversations inspectors have on the floor.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own policies.',
    continuity: 'Make your continuity information instantly reachable by every member of the team, on any day.',
  },
  scenarios: {
    h2: 'How your practice uses CareStream, day to day.',
    sub: 'CareStream is not another system your team has to remember to use. It fits the moments that already happen between patients, and gives the right answer at the moment it matters.',
    items: [
      { tag: 'Between patients', body: 'A dental nurse turning the surgery around wants to confirm the decontamination steps before the next patient is seated. Rather than wait for the practice manager, they ask CareStream and get your exact cycle, drawn from your own policy, in seconds. The room is ready on time and recorded correctly.' },
      { tag: 'A new associate settling in', body: 'A newly arrived associate is not yet sure of your local radiography protocol. Instead of interrupting colleagues or guessing, they ask the hub and receive your approved procedure every time, so their practice matches the rest of the team from their very first list.' },
      { tag: 'A medical emergency in the chair', body: 'A patient becomes faint and unwell in the chair. A team member checks your medical emergency protocol in the hub, sees the immediate steps and where the emergency kit and drugs are kept, drawn from your own policy, and the team responds together.' },
      { tag: 'When a patient raises a concern', body: 'A patient at reception raises a complaint about their treatment. Reception checks your complaints procedure in the hub and follows your exact steps and timescales, rather than promising to find out and ring back.' },
      { tag: 'In a language they are confident in', body: 'A dental nurse whose first language is Portuguese asks an infection control question by voice, in Portuguese, and listens to the answer read back. The guidance is exactly the same as an English-speaking colleague would receive.' },
      { tag: 'Getting ready for inspection', body: 'Before an inspection, the practice manager sends CQC practice questions to the team, reviews who has answered, and checks the regulation coverage report to see where a policy needs strengthening, all before the inspector arrives.' },
    ],
  },
  deepDive: {
    label: 'Answers Between Patients, For The Whole Team',
    h2: 'Your protocols, answered the moment they are needed, without leaving the surgery.',
    para1: 'Any member of the team asks a question in plain language and gets the answer from your own protocol, with the source and version shown. No hunting through a folder, no waiting until the manager is free, and no guessing with the next patient already waiting.',
    para2: 'Because every answer is grounded in your documents and cites them, your dentists, nurses, hygienists, therapists and reception act on the same approved guidance, every time.',
    chips: ['Decontamination and infection control', 'Radiography', 'Medical emergencies', 'Safeguarding', 'Consent', 'Complaints', 'CQC and GDC standards', 'Health and safety'],
    panelH3: 'In the language your team thinks in.',
    panelBody: 'Your policies stay in English. A team member whose first language is not English can ask in Portuguese, Romanian, Polish or any of over 60 languages, by typing or speaking, and hear the answer read back in the same language. Nobody is held back by a written procedure they find hard to follow at speed.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for every member of the team'],
  },
  outcomes: {
    h2: 'Safer practice, a confident team, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'shield', title: 'Protocol answers between patients', body: 'The team gets approved guidance in the surgery, between patients, without waiting for the practice manager to be free.' },
      { iconKey: 'users', title: 'Consistent practice across the team', body: 'Dentists, nurses, hygienists, therapists and reception act on the same protocols, so practice is consistent whoever is in.' },
      { iconKey: 'globe', title: 'A team supported in its own language', body: 'Every member of the team understands your protocols, whatever language they are most confident in.' },
      { iconKey: 'graduation', title: 'Mandatory training kept current', body: 'Training built from your own protocols, with automatic renewal reminders and a live compliance dashboard.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, day-to-day policy use.' },
      { iconKey: 'clock', title: 'New and locum staff up to speed fast', body: 'A new starter can ask your exact protocols from day one, instead of relying on whoever is nearby.' },
    ],
  },
  cqc: {
    h2: 'Built around the areas inspectors look at most.',
    intro: 'Dental practices are inspected by CQC on safety and effectiveness, while the clinical team also works to GDC standards. CareStream gives you evidence that your policies are live and in use, prepares your team for inspector conversations, and shows you where your policies leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of policy use', body: 'Every policy query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Staff ready to be asked', body: 'Inspector-style questions across the five key questions, answered by staff in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your policies and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Can it answer clinical protocol questions, not just admin policies?', answer: 'Yes. CareStream answers from the documents you upload, including your clinical protocols. A team member can ask about decontamination, radiography, consent or your medical emergency protocol and get an answer drawn from your own policy, with the source and version shown so they can check it.' },
    { question: 'Does it replace clinical judgement or training?', answer: 'No. CareStream points the team to your own approved protocols and guidance. It supports professional judgement, your training and GDC expectations, it does not replace them, and every answer cites the policy it came from.' },
    { question: 'Our team speaks more than one language. Does it help?', answer: 'Yes. Staff can ask in over 60 languages and get the answer back in the same language, while your policies stay in English. This is a real help for the mixed teams found in many practices.' },
    { question: 'How does it help with mandatory training and renewals?', answer: 'CareStream can build training modules from your own protocols, deliver them in the hub, and send automatic renewal reminders at 90, 30 and 7 days, with a live compliance dashboard so you can see exactly who is current and who is due.' },
    { question: 'Is patient and practice information kept private and secure?', answer: 'Yes. Your library is stored in an isolated environment for your practice alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, and every query is logged for your audit trail, supporting your information governance.' },
    { question: 'How quickly can a dental practice get started?', answer: 'Most practices are up and running the same day. You upload your policies, invite your team with a one-tap sign-in link, and staff can begin asking questions straight away.' },
  ],
  cta: {
    heading: 'Give your whole dental team the right answer, between patients.',
    sub: 'See how CareStream works for your dental practice.',
  },
}
