import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'domiciliary-care',
  label: 'Domiciliary Care',
  settingNoun: 'domiciliary care service',
  iconKey: 'mapPin',
  navDescription: 'Approved answers for lone care workers in clients’ homes, on any phone, in any language.',
  meta: {
    title: 'CareStream for Domiciliary Care',
    description: 'CareStream gives lone care workers instant access to your care and HR policies, training, audits and CQC tools, on their own phone, in any language, in any client’s home, with every query logged for inspection.',
    ogDescription: 'Approved answers for dispersed lone care workers, on their own phone, in any language, in any client’s home.',
  },
  hero: {
    h1: 'Approved answers in your client’s home, on the phone in your worker’s pocket.',
    subtitle: 'Domiciliary care workers are out on rounds all day, often alone in a client’s home with no colleague or office nearby. CareStream puts your care and HR policies, training and CQC tools in the hub on their own phone, grounded in your own documents, so the right answer is always within reach wherever they are.',
  },
  mockup: {
    orgName: 'Bluebird Home Care',
    badge: 'On a visit',
    tabs: ['Policies', 'Handbook', 'Training', 'CQC'],
    question: 'My client is refusing their medication, what should I do?',
    policyName: 'From your Medication Policy',
    answer: 'Do not force or hide medication unless a specific covert plan is in place. Record the refusal, try again later if appropriate, and report it to the office and the GP if it continues.',
    citation: 'Medication Policy v2.0 · Section 5',
    followups: ['How do I report a missed dose?', 'Who do I call out of hours?'],
  },
  challenge: {
    h2: 'A dispersed team, lone working, and a regulator that still expects consistency.',
    para1: 'A care worker is alone in a client’s home and the client is refusing their medication, but there is no colleague to ask and the office line is engaged. A new worker is unsure how to record a missed visit. A worker whose first language is not English struggles to follow a written procedure on their own under pressure.',
    para2: 'Domiciliary care is delivered out of sight, in dozens of separate homes, by people who are usually working alone. CareStream closes the gap between the procedure on paper and the practice on the doorstep, for every worker, on every round, on the phone already in their pocket.',
    items: [
      { iconKey: 'mapPin', title: 'Lone working, out on rounds', body: 'Workers are alone in clients’ homes all day, with no colleague nearby and no office to walk into.' },
      { iconKey: 'pill', title: 'Medication in the home', body: 'Refusals, missed doses and covert questions come up at the doorstep, far from any senior to ask.' },
      { iconKey: 'globe', title: 'A multilingual workforce', body: 'A large part of the care workforce speaks English as a second language and works without support.' },
      { iconKey: 'shield', title: 'CQC across many homes', body: 'Inspectors expect consistent, safe practice across every worker and every visit, however dispersed.' },
    ],
  },
  servicesH2: 'One platform for care answers, training, audits and CQC, on every round.',
  serviceDescriptions: {
    policies: 'Care procedures answerable in the client’s home, in any language, with the source policy and version cited.',
    hr: 'Your staff handbook on demand for workers out on rounds. Travel, pay and lone-working questions answered 24/7.',
    training: 'Modules built from your own care policies, delivered in the hub on the phone, with renewal reminders for mandatory training.',
    audits: 'Guided audits for medication, infection prevention and care records, scored as you go and inspection-ready.',
    cqc: 'Evidence that builds itself, plus regulation coverage showing where your policies leave a gap.',
    staffq: 'Prepare your care workers for the conversations inspectors have about practice in the home.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own policies.',
    continuity: 'Make your continuity information instantly reachable by every worker, wherever they are on their round.',
  },
  scenarios: {
    h2: 'How your domiciliary care service uses CareStream, visit to visit.',
    sub: 'CareStream is not another system your workers have to remember when they are back at base. It lives on their own phone and gives the right answer at the doorstep, in the moments that already happen on every round.',
    items: [
      { tag: 'Alone on a visit', body: 'A worker is alone with a client who is refusing their medication. Rather than wait on hold to the office, they ask CareStream and get your exact steps on refusals and recording, drawn from your own medication policy, in seconds. They act correctly and report it through the right channel.' },
      { tag: 'A new worker on rounds', body: 'A newly started care worker is not yet sure how your service handles a missed or late visit. Instead of guessing in the client’s home, they ask the hub and receive your approved procedure every time, so their practice matches the rest of the team from their very first round.' },
      { tag: 'Moving and handling on the doorstep', body: 'A worker arriving for a transfer is unsure whether the client’s mobility has changed since the care plan was written. They check your moving-and-handling policy in the hub before they begin, see the answer with the source, and keep both themselves and the client safe.' },
      { tag: 'When a relative asks a question', body: 'A family member at the home asks about your approach to a safeguarding concern or to end-of-life care. The worker can check the relevant policy on their phone and answer clearly and consistently, rather than promising to find out and ring back later.' },
      { tag: 'In a language they are confident in', body: 'A worker whose first language is Romanian asks an infection-prevention question by voice, in Romanian, and listens to the answer read back. The guidance is exactly the same as an English-speaking colleague would receive.' },
      { tag: 'Getting ready for inspection', body: 'Before an inspection, the registered manager sends CQC practice questions to workers out in the field, reviews who has answered, and checks the regulation coverage report to see where a policy needs strengthening, all before the inspector arrives.' },
    ],
  },
  deepDive: {
    label: 'Approved Answers, Wherever Your Staff Are',
    h2: 'Your care procedures, answered in the home, on the worker’s own phone.',
    para1: 'A lone worker asks a question in plain language and gets the answer from your own care policy, with the source and version shown. No hunting through a folder left at base, no waiting on hold to the office, and no guessing on the doorstep.',
    para2: 'Because the hub installs on their own phone and every answer is grounded in your documents and cites them, dispersed workers act on the same approved guidance, in every client’s home, every time.',
    chips: ['Lone working', 'Medication in the home', 'Moving and handling', 'Safeguarding', 'Missed and late visits', 'Infection prevention', 'End-of-life care at home', 'The client’s care plan'],
    panelH3: 'In the language your team thinks in.',
    panelBody: 'Your policies stay in English. A worker can ask in Polish, Tagalog, Romanian or any of over 60 languages, by typing or speaking, and hear the answer read back in the same language. Nobody is held back by a written procedure they find hard to follow alone, at speed, in a client’s home.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for every worker on every round'],
  },
  outcomes: {
    h2: 'Safer visits, a confident lone workforce, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'mapPin', title: 'Answers in every client’s home', body: 'Workers get approved guidance at the doorstep, on any round, without waiting on hold to the office.' },
      { iconKey: 'users', title: 'Consistent practice across the team', body: 'Every care worker acts on the same procedures, so practice is consistent across dozens of separate homes.' },
      { iconKey: 'globe', title: 'A workforce supported in its own language', body: 'Every worker understands your procedures, whatever language they are most confident in, even when alone.' },
      { iconKey: 'graduation', title: 'Mandatory training kept current', body: 'Training built from your own policies, delivered on the phone, with automatic renewal reminders and a live compliance dashboard.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, day-to-day policy use in the field.' },
      { iconKey: 'clock', title: 'New workers up to speed fast', body: 'A new starter can ask your exact procedures from their first round, instead of relying on whoever they can reach.' },
    ],
  },
  cqc: {
    h2: 'Built around the areas inspectors look at most.',
    intro: 'Domiciliary care is assessed on whether safe, consistent practice reaches every client’s home, even though no manager is there to see it. CareStream gives you evidence that your policies are live and in use across your dispersed team, prepares your workers for inspector conversations, and shows you where your policies leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of policy use', body: 'Every policy query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Staff ready to be asked', body: 'Inspector-style questions across the five key questions, answered by workers in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your policies and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Can lone workers use it out in clients’ homes, away from the office?', answer: 'Yes. The hub installs on each worker’s own phone like an app, with a one-tap passwordless sign-in. They can ask a question and get an answer from your own policies in any client’s home, with the source and version shown so they can check it, without needing to ring the office or return to base.' },
    { question: 'Does it replace the office, the on-call line or professional judgement?', answer: 'No. CareStream points workers to your own approved procedures and guidance, and tells them when to report or escalate through your usual channels. It supports professional judgement and your on-call arrangements, it does not replace them, and every answer cites the policy it came from.' },
    { question: 'Our workers speak many languages. Does it help?', answer: 'Yes. Workers can ask in over 60 languages and get the answer back in the same language, while your policies stay in English. This is a real help for the international care workforce in most domiciliary services, especially when working alone.' },
    { question: 'How does it help with mandatory training and renewals?', answer: 'CareStream can build training modules from your own policies, deliver them in the hub on the worker’s phone, and send automatic renewal reminders at 90, 30 and 7 days, with a live compliance dashboard so you can see exactly who is current and who is due, however spread out your team is.' },
    { question: 'Is client and care information kept private and secure?', answer: 'Yes. Your library is stored in an isolated environment for your service alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, and every query is logged for your audit trail.' },
    { question: 'How quickly can a domiciliary care service get started?', answer: 'Most services are up and running the same day. You upload your policies, invite your workers with a one-tap sign-in link they open on their own phone, and they can begin asking questions out on their rounds straight away.' },
  ],
  cta: {
    heading: 'Give every lone worker the right answer, in every client’s home.',
    sub: 'See how CareStream works for your domiciliary care service.',
  },
}
