import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'gp-practices',
  label: 'GP Practices and Primary Care',
  settingNoun: 'practice',
  navDescription: 'One place for the whole practice team to find the current policy, from reception to the consulting room.',
  iconKey: 'stethoscope',
  meta: {
    title: 'CareStream for GP Practices and Primary Care',
    description: 'CareStream gives the whole practice team instant access to your policies and protocols, training, audits and CQC tools, in any language, between patients, with every query logged for inspection.',
    ogDescription: 'Instant access to practice policies, protocols, training and CQC tools for clinical, nursing, reception and admin staff, in any language.',
  },
  hero: {
    h1: 'The right answer between patients, for the whole practice team, in every language they speak.',
    subtitle: 'GP practices are small busy teams with a large set of policies and protocols, where the practice manager often wears many hats and clinical, nursing, reception and admin staff all need quick answers. CareStream gives everyone instant access to your current policies, training and CQC tools, grounded in your own documents.',
  },
  mockup: {
    orgName: 'Elm Tree Surgery',
    badge: 'Morning clinic',
    tabs: ['Policies', 'Protocols', 'Training', 'CQC'],
    question: 'What is our chaperone policy for intimate examinations?',
    policyName: 'From your Chaperone Policy',
    answer: 'Offer a chaperone to every patient for an intimate examination and record whether one was accepted or declined, and who acted as chaperone. Do not proceed if a patient wants a chaperone and one is not available.',
    citation: 'Chaperone Policy v1.2 · Section 1',
    followups: ['Where do I record this?', 'Who can act as a chaperone?'],
  },
  challenge: {
    h2: 'Small busy teams, a large policy set, and a regulator that looks closely.',
    para1: 'A GP needs to confirm your chaperone policy without leaving the consulting room. A healthcare assistant is unsure of your infection prevention and control protocol. A receptionist is asked about a complaint or a significant event and is not sure of the process. The practice manager, who often has no dedicated compliance support, cannot answer every question in person.',
    para2: 'Primary care is inspected closely on safety, governance and how staff apply your policies in practice. CareStream closes the gap between the protocol on file and what happens at the front desk or in the clinic, for every member of the team, between one patient and the next.',
    items: [
      { iconKey: 'clock', title: 'Answers between patients', body: 'People need the right answer in the few minutes between appointments, without leaving the room or the desk.' },
      { iconKey: 'users', title: 'A mixed clinical and admin team', body: 'GPs, practice nurses, healthcare assistants, reception and admin staff all need consistent answers from the same current policies.' },
      { iconKey: 'policies', title: 'A large set of policies and protocols', body: 'Practices carry a big library covering clinical, infection control, governance and employment, often with no spare capacity to manage it.' },
      { iconKey: 'shield', title: 'Close CQC scrutiny', body: 'Inspectors look hard at safety, infection prevention, safeguarding, significant events and information governance.' },
    ],
  },
  servicesH2: 'One platform for policies, protocols, training, audits and CQC.',
  serviceDescriptions: {
    policies: 'Clinical policies and practice protocols answerable between patients, in any language, with the source policy and version cited.',
    hr: 'Your staff handbook on demand for clinical, nursing, reception and admin staff. Leave, pay and employment questions answered any time.',
    training: 'Modules built from your own policies and protocols, delivered in the hub, with renewal reminders for mandatory training.',
    audits: 'Guided audits for infection prevention and control, significant events and prescribing, scored as you go and inspection-ready.',
    cqc: 'Evidence that builds itself, plus regulation coverage showing where your policies leave a gap.',
    staffq: 'Prepare your clinical, nursing, reception and admin staff for the conversations inspectors have around the practice.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own policies.',
    continuity: 'Make your continuity information instantly reachable by every member of the practice team.',
  },
  scenarios: {
    h2: 'How your practice uses CareStream, day to day.',
    sub: 'CareStream is not another system your team has to remember to use. It fits the moments that already happen across a busy practice day, and gives the right answer at the moment it matters.',
    items: [
      { tag: 'In the consulting room', body: 'A GP is about to carry out an intimate examination and wants to confirm the chaperone process and where to record it. Rather than step out or guess, they ask CareStream and get your exact policy, with the source shown, in seconds, and document it correctly.' },
      { tag: 'At the front desk', body: 'A receptionist is asked how to raise a complaint, or notices something that may be a significant event. Instead of promising to find out, they check the hub and follow your approved process straight away, so nothing is missed.' },
      { tag: 'During a treatment room session', body: 'A healthcare assistant is unsure of your infection prevention and control steps for a procedure. They check the protocol in the hub at the point of care, see the answer with the source, and carry it out correctly.' },
      { tag: 'A new starter settling in', body: 'A new practice nurse is not yet sure of your local processes. Instead of interrupting colleagues, they ask the hub and receive your approved protocol every time, so their practice matches the rest of the team from their first day.' },
      { tag: 'In a language they are confident in', body: 'A cleaner or admin assistant whose first language is not English asks an infection control or safeguarding question by voice, in their own language, and listens to the answer read back. The guidance is exactly the same an English-speaking colleague would receive.' },
      { tag: 'Getting ready for inspection', body: 'Before an inspection, the practice manager sends CQC practice questions to the team, reviews who has answered, and checks the regulation coverage report to see where a policy needs strengthening, all before the inspector arrives.' },
    ],
  },
  deepDive: {
    label: 'Answers For The Whole Practice Team',
    h2: 'Your policies and protocols, answered the moment they are needed.',
    para1: 'Clinical, nursing, reception and admin staff ask a question in plain language and get the answer from your own current policy, with the source and version shown. No hunting through a shared drive, no waiting to ask the practice manager, and no guessing.',
    para2: 'Because every answer is grounded in your documents and cites them, everyone from the GP to the front desk acts on the same approved guidance, every time.',
    chips: ['Infection prevention and control', 'Chaperoning', 'Safeguarding', 'Significant event reporting', 'Medicines and prescribing', 'Consent and capacity', 'Complaints', 'Health and safety'],
    panelH3: 'In the language your team thinks in.',
    panelBody: 'Your policies stay in English. Any member of the team, clinical, reception, admin or cleaning, whose first language is not English can ask in their own language, by typing or speaking, and hear the answer read back. Nobody is held back by a written protocol they find hard to follow at speed.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for every member of the team'],
  },
  outcomes: {
    h2: 'A confident team, less on the practice manager, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'stethoscope', title: 'Answers between patients', body: 'Staff get approved guidance at the point of care or the front desk, without leaving the room or waiting to ask.' },
      { iconKey: 'users', title: 'Consistent practice across the team', body: 'Clinical, nursing, reception and admin staff act on the same current policies, so practice is consistent whoever is asked.' },
      { iconKey: 'heart', title: 'Less pressure on the practice manager', body: 'The team self-serves the right answer from your own documents, so the practice manager is not the single point of every query.' },
      { iconKey: 'graduation', title: 'Mandatory training kept current', body: 'Training built from your own policies, with automatic renewal reminders and a live compliance dashboard.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, day-to-day policy use.' },
      { iconKey: 'globe', title: 'A workforce supported in its own language', body: 'Every member of the team understands your protocols, whatever language they are most confident in.' },
    ],
  },
  cqc: {
    h2: 'Built around the areas inspectors look at most.',
    intro: 'Practices are assessed closely on safety, governance and how staff apply your policies. CareStream gives you evidence that your policies are live and in use, prepares your team for inspector conversations, and shows you where your policies leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of policy use', body: 'Every policy query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Staff ready to be asked', body: 'Inspector-style questions across the five key questions, answered by staff in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your policies and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Can it answer protocol questions, not just admin policies?', answer: 'Yes. CareStream answers from the documents you upload, including your clinical protocols and practice procedures. A clinician can ask about chaperoning, infection control, prescribing or safeguarding and get an answer drawn from your own policy, with the source and version shown so they can check it.' },
    { question: 'Does it replace clinical judgement or training?', answer: 'No. CareStream points staff to your own approved policies and protocols. It supports professional judgement and your training, it does not replace them, and every answer cites the policy it came from.' },
    { question: 'Our team includes staff whose first language is not English. Does it help?', answer: 'Yes. Any member of the team, clinical, reception, admin or cleaning, can ask in over 60 languages and get the answer back in the same language, while your policies stay in English. It means everyone follows the same guidance, whatever language they are most confident in.' },
    { question: 'How does it help with mandatory training and renewals?', answer: 'CareStream can build training modules from your own policies, deliver them in the hub, and send automatic renewal reminders at 90, 30 and 7 days, with a live compliance dashboard so you can see exactly who is current and who is due.' },
    { question: 'Is patient and practice information kept private and secure?', answer: 'Yes. Your library is stored in an isolated environment for your practice alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, and every query is logged, supporting your information governance.' },
    { question: 'How quickly can a practice get started?', answer: 'Most practices are up and running the same day. You upload your policies, invite your team with a one-tap sign-in link, and staff can begin asking questions straight away.' },
  ],
  cta: {
    heading: 'Give your whole practice team the right answer, between patients.',
    sub: 'See how CareStream works for your practice.',
  },
}
