import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'hospices',
  label: 'Hospices',
  settingNoun: 'hospice',
  navDescription: "Palliative and end-of-life answers from your own policies for adult and children's hospice teams.",
  iconKey: 'heart',
  meta: {
    title: 'CareStream for Hospices',
    description: "CareStream gives your clinical, nursing and care teams instant access to your palliative and end-of-life policies, training, audits and CQC tools, in any language, on every shift, with every query logged for inspection.",
    ogDescription: 'Palliative and end-of-life answers from your own policies, for your whole hospice team, in any language, day or night.',
  },
  hero: {
    h1: 'The exact policy in your hand, at the most sensitive moments, day or night.',
    subtitle: "Hospices carry clinical and emotional weight around the clock, with a mix of clinical, nursing and care staff and many volunteers, all supporting patients and families through some of life's hardest moments. CareStream gives every member of your team instant access to your palliative and end-of-life policies, training and CQC tools, grounded in your own documents.",
  },
  mockup: {
    orgName: "St Catherine's Hospice",
    badge: 'Night shift',
    tabs: ['Policies', 'Handbook', 'Training', 'CQC'],
    question: 'How do I set up a syringe driver for this patient?',
    policyName: 'From your Syringe Driver and Anticipatory Medicines Policy',
    answer: "Set up the syringe driver following your policy and the patient's prescription. Check the medicines, the rate and the site, document the start, and monitor the site and the patient's symptoms at the intervals your policy requires.",
    citation: 'Syringe Driver Policy v2.1 · Section 4',
    followups: ['How often do I check the site?', 'What do I do if it alarms?'],
  },
  challenge: {
    h2: 'Sensitive care, a mixed team and high expectations at inspection.',
    para1: "A nurse setting up a syringe driver overnight needs your exact procedure to hand, but the policy folder is in the office. A care assistant supporting a family at the moment of death is unsure what your policy asks of them next. A volunteer or a new member of staff whose first language is not English wants to be certain they are following your guidance, at a moment when getting it right matters deeply.",
    para2: 'Hospices are held to high expectations at inspection, particularly around safe symptom control, medicines and end-of-life care. CareStream closes the gap between the policy on paper and the practice at the bedside, for every member of the team, at any hour, while always pointing back to your own documents.',
    items: [
      { iconKey: 'clock', title: 'Sensitive moments at any hour', body: 'Questions about anticipatory medicines, symptom control and verification of death arise overnight, not only during the day.' },
      { iconKey: 'users', title: 'A mixed team and many volunteers', body: 'Clinical, nursing and care staff, alongside volunteers, all need consistent answers from the same approved policies.' },
      { iconKey: 'heart', title: 'Emotionally demanding work', body: 'Staff support patients and families through end-of-life care and bereavement, and need clear guidance at hard moments.' },
      { iconKey: 'shield', title: 'High expectations at inspection', body: 'Inspectors look closely at symptom control, medicines and how staff apply your policies in practice.' },
    ],
  },
  servicesH2: 'One platform for palliative answers, training, audits and CQC.',
  serviceDescriptions: {
    policies: 'Palliative and end-of-life procedures answerable at the bedside, in any language, with the source policy and version cited.',
    hr: 'Your staff handbook on demand for your clinical, nursing and care team. Leave, pay and employment questions answered 24/7.',
    training: 'Modules built from your own palliative policies, delivered in the hub, with renewal reminders for mandatory training.',
    audits: 'Guided audits for medicines, syringe drivers, infection control and end-of-life care, scored as you go and inspection-ready.',
    cqc: 'Evidence that builds itself, plus regulation coverage showing where your policies leave a gap.',
    staffq: 'Prepare your nurses, carers and volunteers for the conversations inspectors have on the floor.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own policies.',
    continuity: 'Make your continuity information instantly reachable by every member of staff, on any shift.',
  },
  scenarios: {
    h2: 'How your hospice uses CareStream, day to day.',
    sub: 'CareStream is not another system your team has to remember to use. It fits the moments that already happen on every shift, and gives the right answer, from your own policy, at the moment it matters most.',
    items: [
      { tag: 'On a night shift', body: "A nurse needs to set up a syringe driver and wants to be certain of every step. Rather than wait until morning or hunt through a folder, they ask CareStream and get your exact procedure, drawn from your own policy, in seconds. They act with confidence and follow your policy and the patient's prescription throughout." },
      { tag: 'At the moment of death', body: 'A care assistant is with a patient as they die and is unsure what your policy asks of them next, including verification of death and how to support the family present. They check the hub quietly and follow your approved steps, calmly and consistently.' },
      { tag: 'During a symptom-control review', body: 'A nurse is unsure how a particular anticipatory medicine should be handled, or how your policy guides escalating pain. They check the relevant policy in the hub at the bedside, see the answer with the source, and record it correctly.' },
      { tag: 'Supporting a family', body: "A family member asks about advance care plans, or about your approach to spiritual and bereavement support. Any member of staff can check the relevant policy and answer clearly and consistently, rather than promising to find out and get back to them at a difficult time." },
      { tag: 'In a language they are confident in', body: 'A carer or volunteer whose first language is Portuguese asks a question by voice, in Portuguese, and listens to the answer read back. The guidance is exactly the same as an English-speaking colleague would receive, drawn from the same policy.' },
      { tag: 'Getting ready for inspection', body: 'Before an inspection, the registered manager sends CQC practice questions to the team, reviews who has answered, and checks the regulation coverage report to see where a policy needs strengthening, all before the inspector arrives.' },
    ],
  },
  deepDive: {
    label: 'Palliative Care, Supported At Every Moment',
    h2: 'Your end-of-life policies, there at the most sensitive and urgent moments.',
    para1: 'Staff ask a question in plain language and get the answer from your own palliative policy, with the source and version shown. No hunting through a folder, no waiting until morning, and no guessing, at exactly the moments when certainty matters most.',
    para2: "Because every answer is grounded in your documents and cites them, your nurses, carers and volunteers follow the same approved guidance, every time. CareStream supports your team to follow your policies and the patient's plan, it does not give clinical advice of its own.",
    chips: ['Anticipatory medicines', 'Syringe drivers', 'Symptom control', 'Verification of death', 'Advance care plans', 'Family and bereavement support', "Children's palliative care", 'Spiritual care'],
    panelH3: 'In the language your team and volunteers think in.',
    panelBody: 'Your policies stay in English. A nurse, carer or volunteer can ask in Polish, Tagalog, Portuguese or any of over 60 languages, by typing or speaking, and hear the answer read back in the same language. Nobody on a multilingual workforce is held back by a written procedure they find hard to follow at a sensitive moment.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for staff and volunteers alike'],
  },
  outcomes: {
    h2: 'Calmer practice, a confident team, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'heart', title: 'The right policy at sensitive moments', body: 'Staff get your approved guidance at the bedside, day or night, including verification of death and family support.' },
      { iconKey: 'users', title: 'Consistent practice across the team', body: 'Nurses, carers and volunteers act on the same procedures, so practice is consistent regardless of who is on shift.' },
      { iconKey: 'globe', title: 'A workforce supported in its own language', body: 'Every member of the team understands your procedures, whatever language they are most confident in.' },
      { iconKey: 'graduation', title: 'Mandatory training kept current', body: 'Training built from your own palliative policies, with automatic renewal reminders and a live compliance dashboard.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, day-to-day policy use.' },
      { iconKey: 'clock', title: 'New staff and volunteers up to speed fast', body: 'A new starter can ask your exact procedures from day one, instead of relying on whoever is nearby.' },
    ],
  },
  cqc: {
    h2: 'Built around the areas inspectors look at most.',
    intro: 'Hospices are assessed closely on safe symptom control, medicines and end-of-life care. CareStream gives you evidence that your policies are live and in use, prepares your team for inspector conversations, and shows you where your policies leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of policy use', body: 'Every policy query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Staff ready to be asked', body: 'Inspector-style questions across the five key questions, answered by staff in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your policies and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Can it answer palliative and end-of-life procedure questions, not just admin policies?', answer: 'Yes. CareStream answers from the documents you upload, including your clinical and palliative procedures. A nurse can ask about a syringe driver, anticipatory medicines, symptom control or verification of death and get an answer drawn from your own policy, with the source and version shown so they can check it.' },
    { question: 'Does it give clinical advice or replace professional judgement?', answer: "No. CareStream points staff to your own approved procedures and to what your policy and the patient's plan require. It supports professional judgement and your training, it does not give clinical advice of its own, and every answer cites the policy it came from." },
    { question: "Does it work for both adult and children's hospices?", answer: "Yes. CareStream answers from whichever policies you upload, so it supports adult and children's palliative and end-of-life care equally. Your guidance for children's palliative care, family support and bereavement is answerable in the same way as the rest of your library." },
    { question: 'Our team and volunteers speak many languages. Does it help?', answer: 'Yes. Staff and volunteers can ask in over 60 languages and get the answer back in the same language, while your policies stay in English. This is a real help for a mixed workforce and the many volunteers a hospice relies on.' },
    { question: 'How does it help with mandatory training and renewals?', answer: 'CareStream can build training modules from your own policies, deliver them in the hub, and send automatic renewal reminders at 90, 30 and 7 days, with a live compliance dashboard so you can see exactly who is current and who is due.' },
    { question: 'Is patient and clinical information kept private and secure?', answer: 'Yes. Your library is stored in an isolated environment for your hospice alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, and every query is logged for your audit trail.' },
  ],
  cta: {
    heading: 'Give your whole hospice team the right answer, at the moments that matter most.',
    sub: 'See how CareStream works for your hospice.',
  },
}
