import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'independent-hospitals',
  label: 'Independent Hospitals and Private Clinics',
  settingNoun: 'hospital or clinic',
  navDescription: 'Clinical governance, consent and infection control made accessible to every clinician and agency worker.',
  iconKey: 'building',
  meta: {
    title: 'CareStream for Independent Hospitals and Private Clinics',
    description: 'CareStream gives clinicians and clinical staff instant access to your governance, consent, infection prevention and CQC procedures, in any language, with every query grounded in your own policies and logged for inspection.',
    ogDescription: 'Instant access to clinical governance, consent and infection control for every clinician, including agency and locum staff, in any language.',
  },
  hero: {
    h1: 'Clinical governance at every clinician’s fingertips, including your agency and locum staff.',
    subtitle: 'Independent hospitals and private clinics run a mixed clinical workforce, often with agency and locum staff who need to find the local way of doing things fast. CareStream gives every clinician instant access to your consent, infection control, medicines and governance procedures, grounded in your own documents and answered in plain language.',
  },
  mockup: {
    orgName: 'Parkview Private Hospital',
    badge: 'Pre-op',
    tabs: ['Policies', 'Governance', 'Training', 'CQC'],
    question: 'What is our consent process before a procedure?',
    policyName: 'From your Consent to Treatment Policy',
    answer: 'Confirm the patient has capacity, has been given the information they need, and has consented voluntarily. Check the signed consent form, confirm the procedure and the site, and escalate to the responsible clinician if anything is unclear before proceeding.',
    citation: 'Consent Policy v3.0 · Section 2',
    followups: ['What if the patient lacks capacity?', 'Where is consent recorded?'],
  },
  challenge: {
    h2: 'A mixed clinical workforce, strong governance expectations, and a regulator that looks closely.',
    para1: 'A locum surgeon arriving for a theatre list needs your exact consent and surgical safety steps, but the governance lead is in a meeting and the policy folder is in the office. An agency nurse on a ward is unsure of your local infection prevention and control practice. A clinician whose first language is not English struggles to follow a written procedure quickly before a procedure begins.',
    para2: 'Independent hospitals and private clinics face strong clinical governance expectations at inspection, particularly around consent, infection prevention, surgical and procedural safety, medicines, and incident reporting with duty of candour. CareStream closes the gap between the procedure on paper and the practice on the floor, for every clinician, including those who only join you for a single list or shift.',
    items: [
      { iconKey: 'users', title: 'A mixed clinical workforce', body: 'Substantive, agency and locum clinicians all need consistent answers from the same approved procedures.' },
      { iconKey: 'shield', title: 'Strong governance expectations', body: 'Consent, infection prevention and procedural safety are scrutinised closely, and staff must apply your current policy.' },
      { iconKey: 'clock', title: 'New staff need to find the local way fast', body: 'Agency and locum staff need the local way of doing things quickly, often before a list or shift begins.' },
      { iconKey: 'globe', title: 'A multilingual workforce', body: 'A large part of the clinical workforce speaks English as a second language and needs to follow procedures with confidence.' },
    ],
  },
  servicesH2: 'One platform for governance answers, training, audits and CQC.',
  serviceDescriptions: {
    policies: 'Consent, infection control, medicines and surgical safety procedures answerable on the spot, in any language, with the source policy and version cited.',
    hr: 'Your staff handbook on demand for your clinical and support teams. Leave, pay and employment questions answered 24/7.',
    training: 'Modules built from your own governance policies, delivered in the hub, with renewal reminders for mandatory training.',
    audits: 'Guided audits for consent, infection prevention, surgical safety and medicines, scored as you go, with a printable PDF.',
    cqc: 'A Readiness Report that builds itself, plus regulation coverage showing where your policies leave a gap.',
    staffq: 'Prepare your clinicians and clinical staff for the conversations inspectors have on the floor.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own policies.',
    continuity: 'Make your continuity information instantly reachable by every member of staff, on any shift.',
  },
  scenarios: {
    h2: 'How your hospital or clinic uses CareStream, day to day.',
    sub: 'CareStream is not another system your team has to remember to use. It fits the moments that already happen on every list and every shift, and gives the right answer at the moment it matters.',
    items: [
      { tag: 'Before a procedure', body: 'A clinician preparing a patient for theatre wants to be sure of your consent and surgical safety steps. Rather than wait for the governance lead, they ask CareStream and get your exact process, drawn from your own policy, in seconds. The site is confirmed, the consent form is checked, and the list runs on time.' },
      { tag: 'An agency nurse on a ward', body: 'An agency nurse covering a shift is not yet sure of your local infection prevention and control practice. Instead of guessing or interrupting colleagues, they ask the hub and receive your approved procedure every time, so their practice matches the substantive team from their very first hour.' },
      { tag: 'During a medicines task', body: 'A clinician is unsure how a controlled drug should be checked and recorded, or how a particular medicine is handled here. They check the medicines policy in the hub at the point of care, see the answer with the source, and record it correctly.' },
      { tag: 'After an incident', body: 'Following a patient safety incident, a member of staff needs to know your reporting steps and how duty of candour applies. They ask CareStream, see your exact escalation and reporting process with the source policy, and act promptly rather than waiting to ask in the morning.' },
      { tag: 'In a language they are confident in', body: 'A clinician whose first language is Spanish asks an infection control question by voice, in Spanish, and listens to the answer read back. The guidance is exactly the same as an English-speaking colleague would receive.' },
      { tag: 'Getting ready for inspection', body: 'Before an inspection, the registered manager sends CQC practice questions to clinicians, reviews who has answered, and checks the regulation coverage report to see where a policy needs strengthening, all before the inspector arrives.' },
    ],
  },
  deepDive: {
    label: 'Clinical Governance, Accessible To Every Clinician',
    h2: 'Your current policies and procedures at every clinician’s fingertips.',
    para1: 'A clinician asks a question in plain language and gets the answer from your own current policy, with the source and version shown. No hunting through a folder, no waiting for the governance lead, and no guessing, even for an agency or locum clinician on their first day.',
    para2: 'Because every answer is grounded in your documents and cites them, your substantive, agency and locum clinicians all act on the same approved guidance, every time.',
    chips: ['Consent', 'Infection prevention and control', 'Medicines management', 'Surgical safety checks', 'Safeguarding', 'Incident reporting and duty of candour', 'Resuscitation', 'Patient identification'],
    panelH3: 'In the language your team thinks in.',
    panelBody: 'Your policies stay in English. A clinician can ask in Spanish, Tagalog, Romanian or any of over 60 languages, by typing or speaking, and hear the answer read back in the same language. Nobody is held back by a written procedure they find hard to follow at speed before a list or procedure.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for every clinician'],
  },
  outcomes: {
    h2: 'Safer practice, a confident clinical team, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'shield', title: 'Governance answers at the point of care', body: 'Clinicians get approved guidance on consent, infection control and safety at the moment it is needed, without waiting for the governance lead.' },
      { iconKey: 'users', title: 'Consistent practice across the team', body: 'Substantive, agency and locum clinicians act on the same procedures, so practice is consistent regardless of who is on the list.' },
      { iconKey: 'clock', title: 'Agency and locum staff up to speed fast', body: 'A new agency or locum clinician can ask your exact local procedures from their first hour, instead of relying on whoever is nearby.' },
      { iconKey: 'globe', title: 'A workforce supported in its own language', body: 'Every clinician understands your procedures, whatever language they are most confident in.' },
      { iconKey: 'graduation', title: 'Mandatory training kept current', body: 'Training built from your own governance policies, with automatic renewal reminders and a live compliance dashboard.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, day-to-day policy use.' },
    ],
  },
  cqc: {
    h2: 'Built around the areas inspectors look at most.',
    intro: 'Independent hospitals and private clinics are assessed closely on clinical governance, consent, infection prevention and procedural safety. CareStream gives you evidence that your policies are live and in use, prepares your clinicians for inspector conversations, and shows you where your policies leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of policy use', body: 'Every policy query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Staff ready to be asked', body: 'Inspector-style questions across the five key questions, answered by clinicians in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your policies and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Can it answer clinical governance and procedure questions, not just admin policies?', answer: 'Yes. CareStream answers from the documents you upload, including your consent, infection control, medicines and surgical safety procedures. A clinician can ask about a consent process, a surgical safety check or your incident reporting steps and get an answer drawn from your own policy, with the source and version shown so they can check it.' },
    { question: 'How does it help agency and locum staff find the local way of doing things?', answer: 'An agency or locum clinician can ask the hub from their first hour and get your exact local procedure, grounded in your own documents and cited. They do not have to track down the governance lead or rely on whoever is nearby to learn how you do things here.' },
    { question: 'Does it replace clinical judgement or training?', answer: 'No. CareStream points clinicians to your own approved procedures and guidance. It supports professional judgement and your training, it does not replace them, and every answer cites the policy it came from.' },
    { question: 'Our clinicians speak many languages. Does it help?', answer: 'Yes. Staff can ask in over 60 languages and get the answer back in the same language, while your policies stay in English. This is a real help for a mixed clinical workforce that includes staff who speak English as a second language.' },
    { question: 'How does it help with mandatory training and renewals?', answer: 'CareStream can build training modules from your own governance policies, deliver them in the hub, and send automatic renewal reminders at 90, 30 and 7 days, with a live compliance dashboard so you can see exactly who is current and who is due.' },
    { question: 'Is patient and clinical information kept private and secure?', answer: 'Yes. Your library is stored in an isolated environment for your hospital or clinic alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, every query is logged for your audit trail, and it supports your information governance.' },
  ],
  cta: {
    heading: 'Give every clinician the right answer, including your agency and locum staff.',
    sub: 'See how CareStream works for your independent hospital or clinic.',
  },
}
