import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'live-in-care',
  label: 'Live-in Care Providers',
  settingNoun: 'live-in care service',
  navDescription: 'A constant source of approved answers for carers living and working alone in a client’s home.',
  iconKey: 'home',
  meta: {
    title: 'CareStream for Live-in Care Providers',
    description: 'CareStream gives your live-in carers instant access to your policies, the client’s care plan, training and CQC tools from their own phone, in any language, at any hour, even when they are the only carer in the home.',
    ogDescription: 'Instant, approved answers for live-in carers working alone in a client’s home, in any language, at any hour of the day or night.',
  },
  hero: {
    h1: 'A colleague in their pocket, for the carer who is working alone.',
    subtitle: 'A live-in carer often lives and works alone in a client’s home, with no colleague nearby to ask, on placements that run day and night. CareStream puts your policies, the client’s care plan, training and CQC tools on the carer’s phone, grounded in your own documents, so a confident answer is always within reach.',
  },
  mockup: {
    orgName: 'Hartwell Live-in Care',
    badge: 'Overnight',
    tabs: ['Policies', 'Handbook', 'Training', 'CQC'],
    question: 'My client seems confused and more breathless than usual tonight',
    policyName: 'From your Deteriorating Health Policy',
    answer: 'Reassure your client and check for signs that need urgent help. Contact the on-call manager. If you are worried about their breathing or they are seriously unwell, call 999 and follow the escalation steps.',
    citation: 'Deterioration Policy v1.3 · Section 2',
    followups: ['When should I call 999?', 'Who is on call tonight?'],
  },
  challenge: {
    h2: 'One carer, alone in a client’s home, with no colleague to turn to.',
    para1: 'A live-in carer is often the only person in the home. At two in the morning their client becomes confused and breathless, and there is nobody in the next room to ask. A carer on a long placement is unsure whether a medication can be given, or how to record a concern, and the office is closed. A carer whose first language is not English struggles to follow a written procedure under pressure.',
    para2: 'Live-in care is delivered out of sight of colleagues and managers, yet the care manager is still accountable for it and the CQC still inspects it. CareStream closes the gap between the procedure on paper and the carer on their own in the home, at any hour, in the language they are most confident in.',
    items: [
      { iconKey: 'home', title: 'Working alone in the home', body: 'A live-in carer is frequently the only carer present, with no colleague nearby to check a procedure with.' },
      { iconKey: 'clock', title: 'Long placements, day and night', body: 'Questions about deterioration, medication and emergencies come up overnight and at weekends, not only in office hours.' },
      { iconKey: 'globe', title: 'A multilingual carer workforce', body: 'Many live-in carers speak English as a second language and find a written procedure hard to follow at speed.' },
      { iconKey: 'shield', title: 'Care delivered out of sight', body: 'Care happens inside a private home, so the manager needs confidence that approved guidance is always to hand.' },
    ],
  },
  servicesH2: 'One platform for approved answers, the care plan, training and CQC.',
  serviceDescriptions: {
    policies: 'Your care procedures answerable in the home, in any language, with the source policy and version cited so the carer can check it.',
    hr: 'Your staff handbook on demand. Questions about placements, breaks, pay and time off answered 24/7, wherever the carer is.',
    training: 'Modules built from your own policies, delivered in the hub, with renewal reminders so mandatory training never lapses on a long placement.',
    audits: 'Guided audits for medication, the care environment and record keeping, scored as you go and ready to print.',
    cqc: 'Evidence that builds itself from real carer questions, plus regulation coverage showing where your policies leave a gap.',
    staffq: 'Prepare your live-in carers for the conversations inspectors have, even when they work out in clients’ homes.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own policies.',
    continuity: 'Make your continuity information instantly reachable by a carer working alone, whatever happens in the home.',
  },
  scenarios: {
    h2: 'How your live-in carers use CareStream, day to day.',
    sub: 'CareStream is not another system a carer has to remember to open. It lives on their phone and fits the moments that already happen on a placement, giving the right answer at the moment it matters, even with nobody else in the home.',
    items: [
      { tag: 'Alone overnight', body: 'A carer notices their client is more confused and breathless than usual in the early hours. With no colleague to ask, they put the question to CareStream and get your exact deterioration and escalation steps, drawn from your own policy, in seconds. They reassure the client, contact the on-call manager, and know when to call 999.' },
      { tag: 'During a medication round', body: 'A carer is unsure whether a PRN medicine applies, or how to handle a missed dose. They check the medication policy in the hub at the client’s side, see the answer with the source and version, and record it correctly.' },
      { tag: 'A new carer on their first placement', body: 'A carer new to your service is not yet sure of your local processes. Instead of guessing or waiting until the office opens, they ask the hub and receive your approved procedure every time, so their practice matches the rest of the team from day one.' },
      { tag: 'When a safeguarding worry arises', body: 'A carer becomes concerned about a visitor to the home, or about their client’s wellbeing. They ask the hub how to raise a safeguarding concern and follow your reporting steps clearly, rather than sitting on a worry until someone is reachable.' },
      { tag: 'In a language they are confident in', body: 'A carer whose first language is Romanian asks a moving-and-handling question by voice, in Romanian, and listens to the answer read back. The guidance is exactly the same as an English-speaking colleague would receive.' },
      { tag: 'Looking after their own wellbeing', body: 'A carer on a long placement wants to know their entitlement to breaks and rest, or how to ask for support. They check the staff handbook in the hub and get a clear answer, so working alone does not mean facing things alone.' },
    ],
  },
  deepDive: {
    label: 'Support For A Carer Working Alone',
    h2: 'Approved answers for the carer who has nobody to ask.',
    para1: 'A live-in carer is often the only person in the home, so there is no colleague in the next room to check a procedure with. They ask a question in plain language and get the answer from your own policy, with the source and version shown. No hunting through a folder, no waiting until the office opens, and no guessing.',
    para2: 'Because every answer is grounded in your documents and cites them, a carer working entirely alone acts on the same approved guidance as the rest of your team, every time, at any hour of the night.',
    chips: ['Deterioration and escalation', 'Medication', 'Moving and handling', 'Safeguarding', 'The client’s care plan', 'Emergencies', 'Your own wellbeing and breaks', 'Reporting concerns'],
    panelH3: 'In the language your carers think in.',
    panelBody: 'Your policies stay in English. A carer can ask in Polish, Tagalog, Romanian or any of over 60 languages, by typing or speaking, and hear the answer read back in the same language. A carer working alone is never held back by a written procedure they find hard to follow at speed.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for every carer, in every home'],
  },
  outcomes: {
    h2: 'A confident carer, safer placements, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'home', title: 'A colleague always within reach', body: 'A carer working alone gets approved guidance on their phone, day or night, without waiting for the office to open.' },
      { iconKey: 'users', title: 'Consistent practice across every home', body: 'Carers in different homes act on the same procedures, so practice is consistent wherever your service delivers care.' },
      { iconKey: 'globe', title: 'A workforce supported in its own language', body: 'Every carer understands your procedures, whatever language they are most confident in.' },
      { iconKey: 'heart', title: 'Carer wellbeing taken seriously', body: 'A carer on a long placement can check their entitlement to breaks and support, so working alone never means coping alone.' },
      { iconKey: 'graduation', title: 'Mandatory training kept current', body: 'Training built from your own policies, with automatic renewal reminders so nothing lapses while a carer is away on a placement.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, day-to-day policy use out in clients’ homes.' },
    ],
  },
  cqc: {
    h2: 'Built for care that is delivered out in clients’ homes.',
    intro: 'Live-in care is delivered away from the office, often by a lone carer, yet it is inspected just as closely. CareStream gives you evidence that your policies are live and in use, prepares your carers for inspector conversations, and shows you where your policies leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of policy use', body: 'Every policy query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Carers ready to be asked', body: 'Inspector-style questions across the five key questions, answered by carers in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your policies and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Does it work when the carer is the only person in the home?', answer: 'Yes. That is exactly what CareStream is for. The hub lives on the carer’s own phone, so even with no colleague nearby and the office closed, they can ask a question and get an answer drawn from your own policy, with the source and version shown so they can check it.' },
    { question: 'Can it answer questions at any hour, including overnight?', answer: 'Yes. There are no office hours. A carer on a long placement can ask about deterioration, medication, safeguarding or an emergency at two in the morning and get your approved guidance straight away, the same as they would in the day.' },
    { question: 'Does it replace the on-call manager or the carer’s judgement?', answer: 'No. CareStream points the carer to your own approved procedures and escalation steps, including when to contact the on-call manager or call 999. It supports professional judgement and your on-call arrangements, it does not replace them, and every answer cites the policy it came from.' },
    { question: 'Our carers speak many languages. Does it help?', answer: 'Yes. Carers can ask in over 60 languages and get the answer back in the same language, by typing or by voice, while your policies stay in English. This is a real help for the international workforce that delivers much of live-in care.' },
    { question: 'How does it help with mandatory training and renewals?', answer: 'CareStream can build training modules from your own policies, deliver them in the hub, and send automatic renewal reminders at 90, 30 and 7 days, with a manager digest, so a carer’s training never quietly lapses while they are away on a placement.' },
    { question: 'Is client and care information kept private and secure?', answer: 'Yes. Your library is stored in an isolated environment for your service alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, and every query is logged for your audit trail.' },
  ],
  cta: {
    heading: 'Give every carer working alone the right answer, at any hour.',
    sub: 'See how CareStream works for your live-in care service.',
  },
}
