import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'nursing-homes',
  label: 'Nursing Homes',
  settingNoun: 'nursing home',
  navDescription: 'Clinical answers at the bedside for your mixed nursing and care team, in any language, on every shift.',
  iconKey: 'stethoscope',
  meta: {
    title: 'CareStream for Nursing Homes',
    description: 'CareStream gives nursing and care teams instant access to your clinical and care policies, training, audits and CQC tools, in any language, on every shift, with every query logged for inspection.',
    ogDescription: 'Instant access to clinical procedures, training and CQC tools for your whole nursing team, in any language, on every shift.',
  },
  hero: {
    h1: 'Clinical answers at the bedside, on every shift, in every language your team speaks.',
    subtitle: 'Nursing homes carry clinical risk around the clock, with a mixed team of registered nurses and care assistants and a workforce that often speaks many languages. CareStream gives every member of your team instant access to your clinical and care policies, training and CQC tools, grounded in your own documents.',
  },
  mockup: {
    orgName: 'Crossways Nursing Home',
    badge: 'Night shift',
    tabs: ['Policies', 'Handbook', 'Training', 'CQC'],
    question: 'What are the early warning signs of sepsis I should escalate?',
    policyName: 'From your Sepsis and Deteriorating Resident Policy',
    answer: 'Escalate immediately for a new high NEWS2 score, raised respiratory rate, low blood pressure, new confusion or mottled skin. Inform the nurse in charge and follow the escalation pathway.',
    citation: 'Sepsis Policy v2.4 · Section 3',
    followups: ['What is the NEWS2 threshold?', 'Who do I call overnight?'],
  },
  challenge: {
    h2: 'Clinical complexity, a mixed team, and a regulator that looks closely.',
    para1: 'A care assistant on a night shift needs a clear answer about a deteriorating resident, but the nurse in charge is busy and the policy folder is in the office. A new registered nurse is unsure of your exact escalation pathway. A staff member whose first language is not English struggles to follow a written procedure under pressure.',
    para2: 'Nursing homes face the most clinical scrutiny at inspection, particularly under the Safe and Effective key questions. CareStream closes the gap between the procedure on paper and the practice on the floor, for every member of the team, at any hour.',
    items: [
      { iconKey: 'clock', title: 'Around-the-clock clinical risk', body: 'Questions about medicines, deterioration and end-of-life care come up at 3am, not only during the day.' },
      { iconKey: 'users', title: 'A mixed nursing and care team', body: 'Registered nurses and care assistants need consistent answers from the same approved procedures.' },
      { iconKey: 'globe', title: 'A multilingual workforce', body: 'A large part of the nursing and care workforce speaks English as a second language.' },
      { iconKey: 'shield', title: 'Close CQC scrutiny', body: 'Inspectors look hard at clinical safety, medicines and how staff apply your policies in practice.' },
    ],
  },
  servicesH2: 'One platform for clinical answers, training, audits and CQC.',
  serviceDescriptions: {
    policies: 'Clinical and care procedures answerable at the bedside, in any language, with the source policy and version cited.',
    hr: 'Your staff handbook on demand for your nursing and care team. Leave, pay and employment questions answered 24/7.',
    training: 'Modules built from your own clinical policies, delivered in the hub, with renewal reminders for mandatory training.',
    audits: 'Guided audits for medicines, infection control, falls and pressure care, scored as you go and inspection-ready.',
    cqc: 'Evidence that builds itself, plus regulation coverage showing where your policies leave a gap.',
    staffq: 'Prepare your registered nurses and carers for the conversations inspectors have on the floor.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own policies.',
    continuity: 'Make your continuity information instantly reachable by every member of staff, on any shift.',
  },
  scenarios: {
    h2: 'How your nursing home uses CareStream, day to day.',
    sub: 'CareStream is not another system your team has to remember to use. It fits the moments that already happen on every shift, and gives the right answer at the moment it matters.',
    items: [
      { tag: 'On a night shift', body: 'A care assistant notices a resident becoming drowsy and harder to rouse. Rather than wait for the nurse in charge to be free, they ask CareStream and get your exact deterioration and escalation steps, drawn from your own policy, in seconds. They act with confidence and the resident is reviewed sooner.' },
      { tag: 'A new nurse settling in', body: 'A newly registered nurse is not yet sure of your local processes. Instead of interrupting colleagues or guessing, they ask the hub and receive your approved procedure every time, so their practice matches the rest of the team from their very first shift.' },
      { tag: 'During the medicines round', body: 'A senior carer is unsure whether a PRN protocol applies, or how a covert medication should be handled. They check the medicines policy in the hub at the trolley, see the answer with the source, and record it correctly.' },
      { tag: 'When a relative asks a question', body: 'A family member asks about visiting during an outbreak, or about your approach to end-of-life care. Any member of staff can check the relevant policy and answer clearly and consistently, rather than promising to find out and get back to them.' },
      { tag: 'In a language they are confident in', body: 'A carer whose first language is Romanian asks a moving-and-handling question by voice, in Romanian, and listens to the answer read back. The guidance is exactly the same as an English-speaking colleague would receive.' },
      { tag: 'Getting ready for inspection', body: 'Before an inspection, the registered manager sends CQC practice questions to the team, reviews who has answered, and checks the regulation coverage report to see where a policy needs strengthening, all before the inspector arrives.' },
    ],
  },
  deepDive: {
    label: 'At the Point of Care',
    h2: 'Your clinical procedures, answered the moment they are needed.',
    para1: 'Staff ask a question in plain language and get the answer from your own clinical policy, with the source and version shown. No hunting through a folder, no waiting until morning, and no guessing.',
    para2: 'Because every answer is grounded in your documents and cites them, your registered nurses and care assistants act on the same approved guidance, every time.',
    chips: ['Medicines and MAR charts', 'Sepsis and NEWS2 escalation', 'Wound and pressure care', 'Syringe drivers', 'Catheter care', 'Falls management', 'PEG feeding', 'End-of-life and anticipatory medicines'],
    panelH3: 'In the language your team thinks in.',
    panelBody: 'Your policies stay in English. A nurse or carer can ask in Polish, Tagalog, Romanian or any of over 60 languages, by typing or speaking, and hear the answer read back in the same language. Nobody is held back by a written procedure they find hard to follow at speed.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for every member of the team'],
  },
  outcomes: {
    h2: 'Safer practice, a confident team, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'stethoscope', title: 'Clinical answers on every shift', body: 'Staff get approved guidance at the point of care, day or night, without waiting for the nurse in charge.' },
      { iconKey: 'users', title: 'Consistent practice across the team', body: 'Registered nurses and care assistants act on the same procedures, so practice is consistent regardless of who is on shift.' },
      { iconKey: 'globe', title: 'A workforce supported in its own language', body: 'Every member of the team understands your procedures, whatever language they are most confident in.' },
      { iconKey: 'graduation', title: 'Mandatory training kept current', body: 'Training built from your own policies, with automatic renewal reminders and a live compliance dashboard.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, day-to-day policy use.' },
      { iconKey: 'clock', title: 'New and agency nurses up to speed fast', body: 'A new starter can ask your exact procedures from day one, instead of relying on whoever is nearby.' },
    ],
  },
  cqc: {
    h2: 'Built around the areas inspectors look at most.',
    intro: 'Nursing homes are assessed closely on clinical safety and effectiveness. CareStream gives you evidence that your policies are live and in use, prepares your team for inspector conversations, and shows you where your policies leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of policy use', body: 'Every policy query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Staff ready to be asked', body: 'Inspector-style questions across the five key questions, answered by staff in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your policies and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Can it answer clinical procedure questions, not just admin policies?', answer: 'Yes. CareStream answers from the documents you upload, including your clinical and care procedures. A nurse can ask about wound care, a syringe driver, catheter care or your sepsis pathway and get an answer drawn from your own policy, with the source and version shown so they can check it.' },
    { question: 'Does it replace clinical judgement or training?', answer: 'No. CareStream points staff to your own approved procedures and guidance. It supports professional judgement and your training, it does not replace them, and every answer cites the policy it came from.' },
    { question: 'Our team speaks many languages. Does it help?', answer: 'Yes. Staff can ask in over 60 languages and get the answer back in the same language, while your policies stay in English. This is a real help for the international nursing and care workforce in most homes.' },
    { question: 'How does it help with mandatory training and renewals?', answer: 'CareStream can build training modules from your own policies, deliver them in the hub, and send automatic renewal reminders at 90, 30 and 7 days, with a live compliance dashboard so you can see exactly who is current and who is due.' },
    { question: 'Is resident and clinical information kept private and secure?', answer: 'Yes. Your library is stored in an isolated environment for your home alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, and every query is logged for your audit trail.' },
    { question: 'How quickly can a nursing home get started?', answer: 'Most homes are up and running the same day. You upload your policies, invite your team with a one-tap sign-in link, and staff can begin asking questions straight away.' },
  ],
  cta: {
    heading: 'Give your whole nursing team the right answer, on every shift.',
    sub: 'See how CareStream works for your nursing home.',
  },
}
