import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'residential-care',
  label: 'Residential Care Homes',
  settingNoun: 'residential care home',
  navDescription: '24/7 policy access for care assistants and seniors, in any language, with CQC evidence that builds itself.',
  iconKey: 'home',
  meta: {
    title: 'CareStream for Residential Care Homes',
    description: 'CareStream gives care assistants and senior carers instant access to your care and HR policies, training, audits and CQC tools, in any language, on every shift, with every query logged for inspection.',
    ogDescription: 'Instant access to your care policies, training and CQC tools for care assistants and seniors, in any language, on every shift.',
  },
  hero: {
    h1: 'The right answer for your care team, on every shift, in every language they speak.',
    subtitle: 'Residential homes deliver personal care around the clock, often with a high turnover of staff, regular agency cover and a workforce that speaks many languages. CareStream gives every care assistant and senior carer instant access to your care and HR policies, training and CQC tools, grounded in your own documents.',
  },
  mockup: {
    orgName: 'Oakfield Residential Home',
    badge: 'Night shift',
    tabs: ['Policies', 'Handbook', 'Training', 'CQC'],
    question: 'A resident has had a fall, what do I need to do?',
    policyName: 'From your Falls Management Policy',
    answer: 'Do not move the resident if a serious injury is suspected. Reassure them, check for injury, call the senior on shift, and complete a body map and an incident form.',
    citation: 'Falls Policy v3.1 · Section 2',
    followups: ['When do I call 999?', 'Where do I record this?'],
  },
  challenge: {
    h2: 'Personal care around the clock, a changing team, and a watchful regulator.',
    para1: 'A care assistant on a night shift, with no manager on site, needs a clear answer about a resident who has had a fall. A new starter is unsure how to support a resident with dementia who is distressed. A staff member whose first language is not English struggles to follow a written procedure while a call bell is ringing.',
    para2: 'Residential homes deliver personal care to vulnerable people every hour of the day, and CQC looks closely at how staff keep residents safe, caring and well-led. CareStream closes the gap between the procedure on paper and the practice on the floor, for every member of the team, at any hour.',
    items: [
      { iconKey: 'clock', title: 'Care needed around the clock', body: 'Questions about falls, medication support and safeguarding come up at 3am, when there is no manager on site to ask.' },
      { iconKey: 'refresh', title: 'High turnover and agency cover', body: 'New starters and agency carers need consistent answers from the same approved procedures, from their very first shift.' },
      { iconKey: 'globe', title: 'A multilingual workforce', body: 'A large part of the care workforce speaks English as a second language and needs guidance they can follow under pressure.' },
      { iconKey: 'shield', title: 'Close CQC scrutiny', body: 'Inspectors look hard at how staff keep residents safe, deliver caring support and follow your policies in practice.' },
    ],
  },
  servicesH2: 'One platform for everyday answers, training, audits and CQC.',
  serviceDescriptions: {
    policies: 'Personal care procedures answerable at the point of care, in any language, with the source policy and version cited.',
    hr: 'Your staff handbook on demand for your care team. Leave, pay and employment questions answered 24/7.',
    training: 'Modules built from your own care policies, delivered in the hub, with renewal reminders for mandatory training.',
    audits: 'Guided audits for medication support, infection control, falls and care planning, scored as you go and inspection-ready.',
    cqc: 'Evidence that builds itself, plus regulation coverage showing where your policies leave a gap.',
    staffq: 'Prepare your care assistants and seniors for the conversations inspectors have on the floor.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own policies.',
    continuity: 'Make your continuity information instantly reachable by every member of staff, on any shift.',
  },
  scenarios: {
    h2: 'How your residential home uses CareStream, day to day.',
    sub: 'CareStream is not another system your team has to remember to use. It fits the moments that already happen on every shift, and gives the right answer at the moment it matters.',
    items: [
      { tag: 'On a night shift', body: 'A care assistant finds a resident on the floor after a fall, with no manager on site. Rather than guess, they ask CareStream and get your exact falls steps, drawn from your own policy, in seconds. They reassure the resident, complete a body map and an incident form, and escalate correctly.' },
      { tag: 'A new starter finding their feet', body: 'A care assistant on their first week is not yet sure of your local processes. Instead of interrupting the senior or guessing, they ask the hub and receive your approved procedure every time, so their practice matches the rest of the team from their very first shift.' },
      { tag: 'During a medication round', body: 'A senior carer is unsure whether a resident can have a PRN painkiller, or how to record a refused dose. They check the medication support policy in the hub at the trolley, see the answer with the source, and complete the MAR chart correctly.' },
      { tag: 'When a resident is distressed', body: 'A resident with dementia becomes anxious and resistant to personal care in the evening. A carer checks your approach to behaviour that challenges and dementia care, and responds calmly and consistently, the same way every member of the team would.' },
      { tag: 'In a language they are confident in', body: 'A carer whose first language is Romanian asks a moving-and-handling question by voice, in Romanian, and listens to the answer read back. The guidance is exactly the same as an English-speaking colleague would receive.' },
      { tag: 'Getting ready for inspection', body: 'Before an inspection, the registered manager sends CQC practice questions to the team, reviews who has answered, and checks the regulation coverage report to see where a policy needs strengthening, all before the inspector arrives.' },
    ],
  },
  deepDive: {
    label: 'Personal Care, On Demand',
    h2: 'Your everyday care procedures, answered the moment they are needed.',
    para1: 'Staff ask a question in plain language and get the answer from your own care policy, with the source and version shown. No hunting through a folder, no waiting for the senior to be free, and no guessing while a call bell rings.',
    para2: 'Because every answer is grounded in your documents and cites them, your care assistants and senior carers act on the same approved guidance, every time, whoever is on shift.',
    chips: ['Moving and handling', 'Falls management', 'Safeguarding', 'Medication support and MAR charts', 'Nutrition and hydration', 'Continence care', 'Dementia and behaviour that challenges', 'End-of-life care'],
    panelH3: 'In the language your team thinks in.',
    panelBody: 'Your policies stay in English. A care assistant can ask in Polish, Tagalog, Romanian or any of over 60 languages, by typing or speaking, and hear the answer read back in the same language. Nobody is held back by a written procedure they find hard to follow at speed.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for every member of the team'],
  },
  outcomes: {
    h2: 'Safer care, a confident team, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'home', title: 'Answers on every shift', body: 'Staff get approved guidance at the point of care, day or night, even when no manager is on site.' },
      { iconKey: 'users', title: 'Consistent care across the team', body: 'Care assistants and senior carers act on the same procedures, so residents get consistent care regardless of who is on shift.' },
      { iconKey: 'globe', title: 'A workforce supported in its own language', body: 'Every member of the team understands your procedures, whatever language they are most confident in.' },
      { iconKey: 'graduation', title: 'Mandatory training kept current', body: 'Training built from your own policies, with automatic renewal reminders and a live compliance dashboard.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, day-to-day policy use.' },
      { iconKey: 'refresh', title: 'New and agency staff up to speed fast', body: 'A new starter can ask your exact procedures from day one, instead of relying on whoever is nearby.' },
    ],
  },
  cqc: {
    h2: 'Built around the areas inspectors look at most.',
    intro: 'Residential homes are assessed closely on whether residents are safe, well cared for and well-led. CareStream gives you evidence that your policies are live and in use, prepares your team for inspector conversations, and shows you where your policies leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of policy use', body: 'Every policy query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Staff ready to be asked', body: 'Inspector-style questions across the five key questions, answered by staff in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your policies and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Can it answer everyday care questions, not just admin policies?', answer: 'Yes. CareStream answers from the documents you upload, including your care procedures. A care assistant can ask about a fall, moving and handling, continence care or your safeguarding steps and get an answer drawn from your own policy, with the source and version shown so they can check it.' },
    { question: 'We use a lot of agency and new staff. Does it help?', answer: 'Yes. A new starter or an agency carer can ask your exact procedures from their first shift, in plain language, and get the approved answer every time. This means consistent care across the team, even with a workforce that changes often.' },
    { question: 'Our team speaks many languages. Does it help?', answer: 'Yes. Staff can ask in over 60 languages and get the answer back in the same language, while your policies stay in English. This is a real help for the international care workforce in most homes.' },
    { question: 'How does it help with mandatory training and renewals?', answer: 'CareStream can build training modules from your own policies, deliver them in the hub, and send automatic renewal reminders at 90, 30 and 7 days, with a live compliance dashboard so you can see exactly who is current and who is due.' },
    { question: 'Is resident information kept private and secure?', answer: 'Yes. Your library is stored in an isolated environment for your home alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, and every query is logged for your audit trail.' },
    { question: 'How quickly can a residential home get started?', answer: 'Most homes are up and running the same day. You upload your policies, invite your team with a one-tap sign-in link, and staff can begin asking questions straight away.' },
  ],
  cta: {
    heading: 'Give your whole care team the right answer, on every shift.',
    sub: 'See how CareStream works for your residential care home.',
  },
}
