import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'shared-lives',
  label: 'Shared Lives Schemes',
  settingNoun: 'Shared Lives scheme',
  navDescription: 'Consistent guidance for Shared Lives carers supporting an adult in their own family home.',
  iconKey: 'heart',
  meta: {
    title: 'CareStream for Shared Lives Schemes',
    description: 'CareStream gives Shared Lives carers and scheme staff instant access to your scheme policies and the person they support, in any language, in the carer’s own home, with every query logged for inspection.',
    ogDescription: 'Consistent scheme guidance for dispersed Shared Lives carers, in any language, in their own home, with every query logged.',
  },
  hero: {
    h1: 'The same scheme guidance for every carer, in their own home, in every language.',
    subtitle: 'Shared Lives carers support an adult in the carer’s own family home, often far from the scheme office, and they are not clinical staff. CareStream gives every carer instant access to your scheme policies and the person’s support plan, grounded in your own documents.',
  },
  mockup: {
    orgName: 'Town and Country Shared Lives',
    badge: 'At home',
    tabs: ['Policies', 'Support plan', 'Training', 'CQC'],
    question: 'I think the person I support may be being financially exploited by a relative, what do I do?',
    policyName: 'From your Safeguarding Policy',
    answer: 'Keep the person safe and do not confront the relative. Record exactly what you have seen or heard, and report your concern to the scheme straight away so it can be raised through the safeguarding process.',
    citation: 'Safeguarding Policy v2.2 · Section 4',
    followups: ['Who do I report to?', 'What should I write down?'],
  },
  challenge: {
    h2: 'Dispersed carers, no office nearby, and a regulator that still inspects the scheme.',
    para1: 'A Shared Lives carer supporting an adult in their own home has a question about consent, or notices a possible safeguarding concern, but the scheme office is miles away and the policy folder is somewhere in a drawer. A new carer is unsure how to handle the person’s money safely. A carer whose first language is not English struggles to follow a written procedure on their own.',
    para2: 'Shared Lives schemes are CQC regulated, yet the support happens in many separate family homes rather than one building. CareStream closes the gap between the scheme’s policies and what happens in each carer’s home, so every carer gets the same answer wherever they are.',
    items: [
      { iconKey: 'home', title: 'Support in many separate homes', body: 'Carers are based in their own family homes and are very dispersed, with no shared office to walk into for an answer.' },
      { iconKey: 'users', title: 'Carers who are not clinical staff', body: 'Carers support adults with learning disabilities, autism, mental health needs or older people, and need clear, plain guidance.' },
      { iconKey: 'globe', title: 'Carers in their own language', body: 'Carers come from many backgrounds, and a written scheme procedure can be hard to follow alone and under pressure.' },
      { iconKey: 'shield', title: 'A CQC regulated scheme', body: 'Inspectors look at safeguarding, consent and how carers across the scheme actually apply your policies.' },
    ],
  },
  servicesH2: 'One platform for scheme guidance, the support plan, training, audits and CQC.',
  serviceDescriptions: {
    policies: 'Scheme policies answerable in the carer’s own home, in any language, with the source policy and version cited.',
    hr: 'Your carer handbook and scheme agreement on demand. Approval, payment and arrangement questions answered 24/7.',
    training: 'Modules built from your own scheme policies, delivered in the hub, with renewal reminders for required training.',
    audits: 'Guided audits for safeguarding, medication and monitoring visits, scored as you go and inspection-ready.',
    cqc: 'Evidence that builds itself, plus regulation coverage showing where your scheme policies leave a gap.',
    staffq: 'Prepare your carers and scheme workers for the conversations inspectors have during a visit.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own scheme policies.',
    continuity: 'Make your continuity information instantly reachable by every carer, in every home.',
  },
  scenarios: {
    h2: 'How your scheme uses CareStream, day to day.',
    sub: 'CareStream is not another system carers have to remember to use. It fits the moments that already happen in each home, and gives the right answer at the moment it matters.',
    items: [
      { tag: 'A possible safeguarding concern', body: 'A carer becomes worried that a relative may be taking money from the person they support. Rather than guess or wait, they ask CareStream and get your exact safeguarding and reporting steps, drawn from your own policy, in seconds. They keep the person safe and report it correctly straight away.' },
      { tag: 'A new carer settling in', body: 'A newly approved carer is not yet sure how your scheme handles the person’s money or how to record an arrangement. Instead of phoning the office for every question, they ask the hub and receive your approved guidance every time, so they get it right from the start.' },
      { tag: 'Around medication', body: 'A carer is unsure whether they should be prompting or administering a medicine, or how to record it. They check the medication policy in the hub at home, see the answer with the source, and record it the way your scheme expects.' },
      { tag: 'A question about consent', body: 'A carer is not sure whether the person they support can make a particular decision themselves. They ask the hub and get your scheme’s guidance on mental capacity and consent, so they support the person to decide rather than deciding for them.' },
      { tag: 'In a language they are confident in', body: 'A carer whose first language is Portuguese asks a finance question by voice, in Portuguese, and listens to the answer read back. The guidance is exactly the same as an English-speaking carer would receive.' },
      { tag: 'On a monitoring visit', body: 'A scheme worker carrying out a monitoring visit checks a point about the support plan or a recording standard in the hub, and gives the carer a consistent answer drawn from the scheme’s own policy, rather than promising to check and come back.' },
    ],
  },
  deepDive: {
    label: 'Consistent Guidance For Carers In Their Own Homes',
    h2: 'Your scheme policies and the support plan, answered the moment they are needed.',
    para1: 'A carer asks a question in plain language and gets the answer from your own scheme policy, with the source and version shown. No hunting through a folder, no waiting until the office opens, and no guessing on their own at home.',
    para2: 'Because every answer is grounded in your documents and cites them, dispersed carers across many separate homes act on the same scheme guidance and the same support plan, every time.',
    chips: ['Safeguarding', 'The person’s support plan', 'Medication', 'Mental capacity and consent', 'Managing finances', 'Reporting concerns', 'Scheme policies', 'Emergencies'],
    panelH3: 'In the language your carers and scheme staff think in.',
    panelBody: 'Your policies stay in English. A carer or scheme worker can ask in Polish, Portuguese, Romanian or any of over 60 languages, by typing or speaking, and hear the answer read back in the same language. Nobody is left alone with a written procedure they find hard to follow.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for every carer in the scheme'],
  },
  outcomes: {
    h2: 'Safer support, confident carers, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'home', title: 'Answers in every home', body: 'Carers get approved guidance where they actually support someone, without waiting for the scheme office to be free.' },
      { iconKey: 'users', title: 'Consistent practice across the scheme', body: 'Every carer acts on the same scheme policies and the same support plan, so practice is consistent across many separate homes.' },
      { iconKey: 'globe', title: 'Carers supported in their own language', body: 'Every carer understands your scheme guidance, whatever language they are most confident in.' },
      { iconKey: 'graduation', title: 'Required training kept current', body: 'Training built from your own scheme policies, with automatic renewal reminders and a live compliance dashboard.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, day-to-day use across the scheme.' },
      { iconKey: 'shield', title: 'Concerns reported the right way', body: 'When something worries a carer, they get your safeguarding and reporting steps at once, so concerns reach the scheme quickly.' },
    ],
  },
  cqc: {
    h2: 'Built around the areas inspectors look at most.',
    intro: 'Shared Lives schemes are assessed on safeguarding, consent and how consistently carers apply your policies across many homes. CareStream gives you evidence that your policies are live and in use, prepares your carers and scheme workers for inspector conversations, and shows you where your policies leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of policy use', body: 'Every policy query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Carers ready to be asked', body: 'Inspector-style questions across the five key questions, answered by carers and scheme staff in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your scheme policies and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Can carers use it in their own home, away from the office?', answer: 'Yes. CareStream installs on a carer’s phone like an app, with a one-tap sign-in and no password to remember. Wherever a carer is supporting someone, they can ask a question and get an answer from your own scheme policies, with the source and version shown so they can check it.' },
    { question: 'Does it replace the support plan or the scheme’s judgement?', answer: 'No. CareStream points carers to your own approved policies and the information you have given it. It supports the person’s support plan and the scheme’s decisions, it does not replace them, and every answer cites the document it came from.' },
    { question: 'Our carers come from many backgrounds. Does it help?', answer: 'Yes. Carers can ask in over 60 languages and get the answer back in the same language, while your policies stay in English. This helps every carer follow the same scheme guidance, whatever language they are most confident in.' },
    { question: 'How does it help with required training and renewals?', answer: 'CareStream can build training modules from your own scheme policies, deliver them in the hub, and send automatic renewal reminders at 90, 30 and 7 days, with a live compliance dashboard so you can see exactly which carers are current and who is due.' },
    { question: 'Is the person’s information kept private and secure?', answer: 'Yes. Your library is stored in an isolated environment for your scheme alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, and every query is logged for your audit trail.' },
    { question: 'How quickly can a Shared Lives scheme get started?', answer: 'Most schemes are up and running the same day. You upload your scheme policies, invite your carers and scheme workers with a one-tap sign-in link, and they can begin asking questions straight away.' },
  ],
  cta: {
    heading: 'Give every Shared Lives carer the same answer, in every home.',
    sub: 'See how CareStream works for your Shared Lives scheme.',
  },
}
