import type { SettingPageConfig } from '@/components/marketing/setting-page'

export const config: SettingPageConfig = {
  slug: 'substance-misuse',
  label: 'Substance Misuse and Rehabilitation',
  settingNoun: 'rehabilitation service',
  navDescription: 'Fast, clear answers from your own protocols for residential detox and rehabilitation teams.',
  iconKey: 'pill',
  meta: {
    title: 'CareStream for Substance Misuse and Rehabilitation',
    description: 'CareStream gives residential detox and rehabilitation teams instant access to your own clinical and treatment protocols, training, audits and CQC tools, in any language, on every shift, with every query logged for inspection.',
    ogDescription: 'Fast, exact answers from your own protocols for residential detox and rehab teams, in any language, on every shift.',
  },
  hero: {
    h1: 'Fast, exact answers from your own protocols, for the moments that matter most.',
    subtitle: 'Residential detox and rehabilitation carry real clinical risk, with a mixed workforce of nurses and recovery workers and a population at risk of overdose and withdrawal. CareStream gives every member of your team instant access to your own emergency and treatment protocols, training and CQC tools, grounded in your own documents.',
  },
  mockup: {
    orgName: 'Riverside Recovery',
    badge: 'On shift',
    tabs: ['Policies', 'Protocols', 'Training', 'CQC'],
    question: 'A resident appears to have overdosed, what do I do?',
    policyName: 'From your Overdose and Emergency Response Policy',
    answer: 'Call 999 immediately. Check breathing and response, place them in the recovery position, and administer naloxone if it is available and you are trained to do so. Stay with them and follow your emergency protocol until help arrives.',
    citation: 'Overdose Policy v1.4 · Section 1',
    followups: ['Where is the naloxone kept?', 'How do I record this?'],
  },
  challenge: {
    h2: 'High clinical risk, a mixed workforce, and a regulator that looks closely.',
    para1: 'A recovery worker on shift notices a resident becoming unresponsive and needs to know exactly what to do, but the nurse is with someone else and the policy folder is in the office. A new staff member is unsure how your withdrawal scoring or medication-assisted treatment protocol works. A staff member whose first language is not English struggles to follow a written procedure when seconds count.',
    para2: 'Residential detox and rehab face close scrutiny at inspection, particularly around medicines, risk and safeguarding. CareStream closes the gap between the protocol on paper and the practice on the floor, for every member of the team, on every shift, with consistent answers whoever is on duty.',
    items: [
      { iconKey: 'clock', title: 'Overdose and withdrawal risk', body: 'Questions about overdose, withdrawal and naloxone come up at any hour, not only when a nurse is free.' },
      { iconKey: 'users', title: 'A mixed clinical and recovery workforce', body: 'Nurses and recovery workers need consistent answers from the same approved protocols.' },
      { iconKey: 'globe', title: 'A multilingual workforce', body: 'A large part of the workforce speaks English as a second language and needs answers in their own.' },
      { iconKey: 'shield', title: 'Close CQC scrutiny', body: 'Inspectors look hard at medicines, risk, safeguarding and how staff apply your protocols in practice.' },
    ],
  },
  servicesH2: 'One platform for protocol answers, training, audits and CQC.',
  serviceDescriptions: {
    policies: 'Emergency and treatment protocols answerable on shift, in any language, with the source protocol and version cited.',
    hr: 'Your staff handbook on demand for your clinical and recovery team. Leave, pay and employment questions answered 24/7.',
    training: 'Modules built from your own protocols, delivered in the hub, with renewal reminders for mandatory training.',
    audits: 'Guided audits for medicines, naloxone, risk and safeguarding, scored as you go and inspection-ready.',
    cqc: 'Evidence that builds itself, plus regulation coverage showing where your protocols leave a gap.',
    staffq: 'Prepare your nurses and recovery workers for the conversations inspectors have on the floor.',
    reportchat: 'Upload your inspection report and chat with it, cross-referenced against your own protocols.',
    continuity: 'Make your continuity information instantly reachable by every member of staff, on any shift.',
  },
  scenarios: {
    h2: 'How your service uses CareStream, day to day.',
    sub: 'CareStream is not another system your team has to remember to use. It fits the moments that already happen on every shift, and gives the right answer at the moment it matters.',
    items: [
      { tag: 'In an emergency', body: 'A recovery worker finds a resident unresponsive and suspects an overdose. Rather than wait for the nurse to be free, they ask CareStream and get your exact emergency steps, drawn from your own protocol, in seconds. CareStream points them straight to calling 999 and following your overdose response, so they act with confidence while help is on the way.' },
      { tag: 'A new starter settling in', body: 'A new recovery worker is not yet sure of your local processes. Instead of interrupting colleagues or guessing, they ask the hub and receive your approved protocol every time, so their practice matches the rest of the team from their very first shift.' },
      { tag: 'During the medication round', body: 'A nurse is checking how a medication-assisted treatment protocol applies, or how a missed dose should be handled. They check the medicines protocol in the hub at the trolley, see the answer with the source, and record it correctly.' },
      { tag: 'Managing withdrawal', body: 'A staff member is unsure how to act on a rising withdrawal score, or when to escalate. They ask the hub, see your detox and escalation steps from your own protocol, and know exactly who to inform and when.' },
      { tag: 'In a language they are confident in', body: 'A recovery worker whose first language is Polish asks a safeguarding question by voice, in Polish, and listens to the answer read back. The guidance is exactly the same as an English-speaking colleague would receive.' },
      { tag: 'Getting ready for inspection', body: 'Before an inspection, the registered manager sends CQC practice questions to the team, reviews who has answered, and checks the regulation coverage report to see where a protocol needs strengthening, all before the inspector arrives.' },
    ],
  },
  deepDive: {
    label: 'Clear Answers When Minutes Matter',
    h2: 'Your emergency and treatment protocols, answered the moment they are needed.',
    para1: 'Staff ask a question in plain language and get the answer from your own protocol, with the source and version shown. No hunting through a folder, no waiting for the nurse to be free, and no guessing when seconds count.',
    para2: 'Because every answer is grounded in your documents and cites them, your nurses and recovery workers act on the same approved guidance, every time, whoever is on shift.',
    chips: ['Overdose and naloxone', 'Withdrawal and detox', 'Medication-assisted treatment', 'Safeguarding', 'Blood-borne viruses', 'Mental health and risk', 'Searches and contraband', 'Discharge planning'],
    panelH3: 'In the language your team thinks in.',
    panelBody: 'Your protocols stay in English. A nurse or recovery worker can ask in Polish, Romanian, Portuguese or any of over 60 languages, by typing or speaking, and hear the answer read back in the same language. Nobody is held back by a written procedure they find hard to follow at speed.',
    points: ['Over 60 languages, detected automatically', 'Speak the question and listen to the answer', 'The same accurate guidance for every member of the team'],
  },
  outcomes: {
    h2: 'Safer practice, a confident team, and inspection evidence that builds itself.',
    items: [
      { iconKey: 'pill', title: 'Protocol answers on every shift', body: 'Staff get approved guidance on shift, day or night, without waiting for the nurse to be free.' },
      { iconKey: 'users', title: 'Consistent practice across the team', body: 'Nurses and recovery workers act on the same protocols, so practice is consistent regardless of who is on shift.' },
      { iconKey: 'globe', title: 'A workforce supported in its own language', body: 'Every member of the team understands your protocols, whatever language they are most confident in.' },
      { iconKey: 'graduation', title: 'Mandatory training kept current', body: 'Training built from your own protocols, with automatic renewal reminders and a live compliance dashboard.' },
      { iconKey: 'chart', title: 'Inspection evidence on tap', body: 'Every query is logged, and your CQC readiness builds itself from real, day-to-day protocol use.' },
      { iconKey: 'clock', title: 'New and bank staff up to speed fast', body: 'A new starter can ask your exact protocols from day one, instead of relying on whoever is nearby.' },
    ],
  },
  cqc: {
    h2: 'Built around the areas inspectors look at most.',
    intro: 'Residential detox and rehab are assessed closely on medicines, risk and safeguarding. CareStream gives you evidence that your protocols are live and in use, prepares your team for inspector conversations, and shows you where your protocols leave a gap before an inspection finds it.',
    cards: [
      { iconKey: 'chart', title: 'Evidence of protocol use', body: 'Every protocol query is logged by role, language and date, building a CQC Readiness Report you can download as a PDF.' },
      { iconKey: 'staffq', title: 'Staff ready to be asked', body: 'Inspector-style questions across the five key questions, answered by staff in their own words and scored by AI, with review and retry.' },
      { iconKey: 'shield', title: 'Regulation coverage', body: 'CareStream reads the content of your protocols and shows which regulations are covered, partly covered, or a gap.' },
    ],
  },
  faqs: [
    { question: 'Can it give the right steps in an emergency like an overdose?', answer: 'CareStream answers from the documents you upload, including your overdose and emergency response protocols. It points staff to your own approved steps, with the source and version shown, so they can act fast and check it. It supports your protocols, it does not give clinical advice of its own, so in any emergency staff should always call 999 and follow your protocol.' },
    { question: 'Does it replace clinical judgement or training?', answer: 'No. CareStream points staff to your own approved protocols and guidance. It supports professional judgement and your training, it does not replace them, and it does not give medical advice of its own. Every answer cites the protocol it came from.' },
    { question: 'Our team speaks many languages. Does it help?', answer: 'Yes. Staff can ask in over 60 languages and get the answer back in the same language, while your protocols stay in English. This is a real help for the mixed clinical and recovery workforce in most services.' },
    { question: 'How does it help with mandatory training and renewals?', answer: 'CareStream can build training modules from your own protocols, deliver them in the hub, and send automatic renewal reminders at 90, 30 and 7 days, with a live compliance dashboard so you can see exactly who is current and who is due.' },
    { question: 'Is resident and clinical information kept private and secure?', answer: 'Yes. Your library is stored in an isolated environment for your service alone, is never used to train AI models, and is never shared with other organisations. Data is encrypted at rest and in transit, and every query is logged for your audit trail.' },
    { question: 'How quickly can a rehabilitation service get started?', answer: 'Most services are up and running the same day. You upload your protocols, invite your team with a one-tap sign-in link, and staff can begin asking questions straight away.' },
  ],
  cta: {
    heading: 'Give your whole team the right answer, when minutes matter.',
    sub: 'See how CareStream works for your detox and rehabilitation service.',
  },
}
