// Regenerates apps/api/src/assets/carestream-logo.ts from the web app's logo.
//
// The mark is embedded rather than read from disk because apps/web/public is a different
// Vercel project from the API: that path exists in the repo and not in the deployed
// function. A filesystem read finds it locally, passes every test, and quietly produces an
// unbranded PDF in production, which is exactly how the pdfkit font metrics failed.
//
//   node scripts/embed-logo.js
const sharp = require('sharp')
const fs = require('fs')
const path = require('path')

const SRC = path.resolve(__dirname, '../apps/web/public/logo-color.png')
const OUT = path.resolve(__dirname, '../apps/api/src/assets/carestream-logo.ts')

;(async () => {
  const raw = fs.readFileSync(SRC)
  const at = async w =>
    (await sharp(raw).resize({ width: w, withoutEnlargement: true }).png({ compressionLevel: 9 }).toBuffer())
      .toString('base64')
  const header = await at(420)
  const footer = await at(200)
  const wrap = s => s.match(/.{1,110}/g).map(l => '  ' + JSON.stringify(l)).join(' +\n')

  fs.writeFileSync(OUT, [
    '// GENERATED by scripts/embed-logo.js — do not edit by hand.',
    '//',
    '// The CareStream mark, embedded rather than read from disk. apps/web/public is a',
    '// different Vercel project from this API, so that path exists in the repo and not in the',
    '// deployed function: a filesystem read would find it locally, pass every test, and quietly',
    '// produce an unbranded PDF in production.',
    '//',
    '// Pre-sized at build. Two fixed sizes are all this document uses, and 48KB of base64 in',
    '// the bundle beats a sharp resize on every request.',
    '',
    '/** 420px wide, for the header. */',
    'const HEADER_B64 =',
    wrap(header),
    '',
    '/** 200px wide, for the footer of every page. */',
    'const FOOTER_B64 =',
    wrap(footer),
    '',
    "export const LOGO_HEADER = Buffer.from(HEADER_B64, 'base64')",
    "export const LOGO_FOOTER = Buffer.from(FOOTER_B64, 'base64')",
    '',
  ].join('\n'))
  console.log('written', OUT, (fs.statSync(OUT).size / 1024).toFixed(1), 'KB')
})()
