// GENERATED by carestream-theme-preview/gen_about_cards.py — do not edit by hand.
//
// The six platform cards on /about: where each links, and the icon it carries. NOT copy, so
// not in ABOUT_V2_SLOTS: the hrefs are site structure and the icons are shapes. The titles and
// bodies are slots, and these line up with them in order.
//
// The two colours are the theme's own per-card tints, which is why they are values here rather
// than classes: there is no class for them in the stylesheet.

import type { IconShape } from '@/components/marketing/setting-page-v2'

export const ABOUT_CARDS: { href: string; bg: string; fg: string; shapes: IconShape[] }[] = [
  {
    "href": "/care-policies",
    "bg": "#F1E9FA",
    "fg": "#6F35B0",
    "shapes": [
      {
        "tag": "path",
        "d": "M6 3.5h9l4 4v13H6z"
      },
      {
        "tag": "path",
        "d": "M9 12h7M9 16h5"
      }
    ]
  },
  {
    "href": "/staff-training",
    "bg": "#E6F4EC",
    "fg": "#15764F",
    "shapes": [
      {
        "tag": "path",
        "d": "M12 5 21 9.5 12 14 3 9.5z"
      },
      {
        "tag": "path",
        "d": "M6.8 11.8V16c0 1.6 2.3 2.9 5.2 2.9s5.2-1.3 5.2-2.9v-4.2"
      }
    ]
  },
  {
    "href": "/care-audits",
    "bg": "#DDF2EF",
    "fg": "#0A736C",
    "shapes": [
      {
        "tag": "path",
        "d": "M9 4.5h6v2H9z"
      },
      {
        "tag": "path",
        "d": "M7 5.5H5.5v15h13v-15H17"
      },
      {
        "tag": "path",
        "d": "M9 12l2 2 4-4"
      }
    ]
  },
  {
    "href": "/cqc-compliance",
    "bg": "#FCF0DC",
    "fg": "#9E6709",
    "shapes": [
      {
        "tag": "path",
        "d": "M12 3.5 20 7v5.5c0 4.4-3.4 7.4-8 8.6-4.6-1.2-8-4.2-8-8.6V7z"
      },
      {
        "tag": "path",
        "d": "M8.8 12.2 11 14.5l4.2-4.6"
      }
    ]
  },
  {
    "href": "/how-it-works",
    "bg": "#E5EEFC",
    "fg": "#2760BC",
    "shapes": [
      {
        "tag": "rect",
        "x": "7",
        "y": "2.8",
        "width": "10",
        "height": "18.4",
        "rx": "2.4"
      },
      {
        "tag": "path",
        "d": "M11 18.4h2"
      }
    ]
  },
  {
    "href": "/hr-policies",
    "bg": "#FAE7E3",
    "fg": "#A94331",
    "shapes": [
      {
        "tag": "circle",
        "cx": "9.2",
        "cy": "8.4",
        "r": "3.3"
      },
      {
        "tag": "path",
        "d": "M3.5 19c.7-3.3 2.9-5 5.7-5s5 1.7 5.7 5"
      },
      {
        "tag": "path",
        "d": "M16 5.6a3.2 3.2 0 0 1 0 5.6M17.5 14.4c1.7.8 2.8 2.4 3 4.6"
      }
    ]
  }
]
