// GENERATED by carestream-theme-preview/gen_erkb_diagrams.py — do not edit by hand.
//
// The four diagrams on /features/external-regulatory-knowledge-base, the one feature page the
// theme illustrates with diagrams rather than screenshots: a good/bad comparison in the hero,
// then a sources rail, a timeline and a flow, one after each "how it works" step.
//
// Not in the slot set and not in the feature_pages record: their shape IS the design, and
// there is nothing here to edit without also changing the diagram.

export interface ErkbHeroCol {
  tone: 'bad' | 'good'
  tag: string
  box: string
  boxNote: string
  fuzzy: boolean
  out: string
  outTone: 'warn' | 'ok'
}

export type ErkbSection =
  | { kind: 'rail'; sources: string[]; base: string }
  | { kind: 'time'; items: { title: string; note: string; live: boolean }[] }
  | { kind: 'flow'; steps: { title: string; note: string; tone: string }[] }

export const ERKB_DIAGRAMS: { hero: ErkbHeroCol[]; sections: ErkbSection[] } = {
  "hero": [
    {
      "tone": "bad",
      "tag": "Without grounding",
      "box": "A model's memory",
      "boxNote": "Frozen at its training date",
      "fuzzy": true,
      "out": "Confident, unsourced, possibly out of date",
      "outTone": "warn"
    },
    {
      "tone": "good",
      "tag": "CareStream",
      "box": "Maintained knowledge base",
      "boxNote": "Regulations · standards · statutory guidance",
      "fuzzy": false,
      "out": "Grounded in current sector rules",
      "outTone": "ok"
    }
  ],
  "sections": [
    {
      "kind": "rail",
      "sources": [
        "Health and Social Care Act 2008 Regulations",
        "CQC Fundamental Standards",
        "Care Act 2014",
        "Mental Capacity Act 2005",
        "NICE guidance"
      ],
      "base": "The knowledge base"
    },
    {
      "kind": "time",
      "items": [
        {
          "title": "Sector rule changes",
          "note": "Guidance is reissued",
          "live": false
        },
        {
          "title": "The base is refreshed",
          "note": "The superseded version is retired",
          "live": false
        },
        {
          "title": "Analysis moves with it",
          "note": "Recommendations reflect the current rule",
          "live": true
        }
      ]
    },
    {
      "kind": "flow",
      "steps": [
        {
          "title": "Your policy",
          "note": "Submitted for analysis",
          "tone": ""
        },
        {
          "title": "The knowledge base is consulted",
          "note": "Not the model's recollection",
          "tone": "mid"
        },
        {
          "title": "A recommendation, tied to a rule",
          "note": "Traceable back to the source",
          "tone": "out"
        }
      ]
    }
  ]
}
