// GENERATED by carestream-theme-preview/gen_hero_images.py — do not edit by hand.
//
// The hero image of each marketing page, used as its social sharing image. The chain in
// pageMetadata() is: og_image_url set in the Pages tab, then this, then the branded
// CareStream card. So an editor can still override any single page, but nobody has to fill
// in several hundred of them to get a real image on a shared link.
//
// ONLY pages whose hero is actually present in apps/web/public are listed. An og:image
// pointing at a file the app does not serve renders NO preview at all, which is worse
// than the branded card, so the map stays behind the assets rather than ahead of them.
// It is empty until the port starts copying theme images across, and grows with them.
//
// Regenerate after a theme rebuild or an image batch: python3 gen_hero_images.py
export const HERO_IMAGES: Record<string, string> = {
}

/** The hero for a path, if the page has one. Trailing slashes are tolerated. */
export function heroImageFor(path: string): string | undefined {
  return HERO_IMAGES[path] ?? HERO_IMAGES[path.replace(/\/$/, '')]
}
