// Generated by cpd-keyword-tool/scripts/gdpr_plan.py: one version of the Data Protection and GDPR
// Policy page per Google Ads Final URL and sitelink (?intent=<key>). Edit the copy there and
// regenerate, so the keyword tool and the page say the same thing.
import type { PolicyIntent } from './policy-cro'

export const GDPR_POLICY_INTENTS: Record<string, PolicyIntent> = {
  "gdpr-ch": { tag: "For care homes", headline: "A GDPR policy written for your care home", sub: "Covers residents’ records, families’ requests, CCTV and data breaches, checked against UK GDPR and what CQC looks for.", moment: 0 },
  "gdpr-ch-dp": { tag: "For care homes", headline: "A data protection policy written for your care home", sub: "Checked against UK GDPR and the Data Protection Act 2018, read by a person, and delivered in 2 working days.", moment: 0 },
  "gdpr-in-ch": { tag: "GDPR in care homes", headline: "GDPR in care homes: what your policy must cover", sub: "Residents’ records, families’ requests, CCTV, breaches and CQC: the data protection your home needs, in one policy written for you.", moment: 0 },
  "gdpr-template-ch": { tag: "Care home GDPR template", headline: "Looking for a care home GDPR policy template? Get one written for your home", sub: "Personalised to the way your home works, read by a person before it carries your name, and updated for a year.", moment: 0 },
  "gdpr-residential": { tag: "For residential care", headline: "A GDPR policy for your residential care home", sub: "Residents’ records, family and Lasting Power of Attorney requests, CCTV and breaches, all set out for your home.", moment: 2 },
  "gdpr-nh": { tag: "For nursing homes", headline: "A GDPR policy written for your nursing home", sub: "Covers residents’ health records, families’ requests and data breaches, under UK GDPR and the Caldicott Principles.", moment: 0 },
  "gdpr-hc": { tag: "For home care", headline: "A GDPR policy for home care and domiciliary services", sub: "Covers carers handling information in people’s homes and in care apps, and breaches reported out of hours.", moment: 1 },
  "gdpr-agency": { tag: "For care agencies", headline: "A GDPR policy written for your care agency", sub: "Sets out how your carers handle clients’ information on every visit, and who reports a breach out of hours.", moment: 1 },
  "gdpr-livein": { tag: "For live in care", headline: "A GDPR policy for live in care", sub: "How live in carers keep a client’s information safe in their home, and what to do if something goes wrong.", moment: 1 },
  "gdpr-sl": { tag: "For supported living", headline: "A GDPR policy for supported living services", sub: "Consent, capacity and Lasting Power of Attorney, access requests and breaches, written for the way your service works.", moment: 2 },
  "gdpr-ld": { tag: "For learning disability services", headline: "A GDPR policy for learning disability services", sub: "Covers consent and capacity, who can act for someone, and how requests for their records are handled.", moment: 2 },
  "gdpr-providers": { tag: "For care providers", headline: "A GDPR policy written for care providers", sub: "UK GDPR, the Data Protection Act 2018 and the Caldicott Principles, written for your service and read by a person.", moment: 0 },
  "gdpr-socialcare": { tag: "For social care", headline: "A data protection policy for health and social care services", sub: "Checked against UK GDPR, the Data Protection Act 2018 and the Caldicott Principles, and ready for CQC.", moment: 0 },
  "gdpr-cqc": { tag: "CQC", headline: "A GDPR policy ready for your CQC inspection", sub: "Inspectors check how you handle people’s information. Every required element is checked before a person signs your policy off.", moment: 0 },
  "gdpr-workers": { tag: "For care workers", headline: "The GDPR policy your care workers follow", sub: "What every carer must do with personal information, and what to do if something goes wrong.", moment: 1 },
  "gdpr-procedures": { tag: "Policies and procedures", headline: "GDPR policy and procedures for your care service", sub: "Breaches, access requests, consent and new systems: what your team does, step by step.", moment: 1 },
  "gdpr-breach": { tag: "Data breaches", headline: "A GDPR policy that tells your team what to do after a data breach", sub: "Reporting to the ICO within 72 hours, and who can report it out of hours when the manager is not there.", moment: 1 },
  "gdpr-sar": { tag: "Access requests", headline: "Handle subject access requests and family requests the right way", sub: "Capacity, consent and Lasting Power of Attorney, with replies within one calendar month.", moment: 2 },
  "gdpr-cctv": { tag: "CCTV and new software", headline: "Adding CCTV or new care software? Your GDPR policy covers it", sub: "A data protection impact assessment first, and the right data processing clauses with your suppliers.", moment: 3 },
  "gdpr-capacity": { tag: "Consent and capacity", headline: "GDPR, consent and mental capacity in your service", sub: "When someone cannot consent, who can act for them, and how Lasting Power of Attorney requests are handled.", moment: 2 },
  "gdpr-ch-residents": { tag: "Residents’ information", headline: "How your care home handles residents’ personal information", sub: "Records, consent and capacity, and requests from families and attorneys, all set out in your policy.", moment: 2 },
  "gdpr-hc-visits": { tag: "Information on visits", headline: "Keeping people’s information safe on every home care visit", sub: "Care notes, phones and care apps: your policy sets out how carers handle information in people’s homes.", moment: 3 },
  "gdpr-written": { tag: "Written for you", headline: "A GDPR policy written for your service, not a template", sub: "Answer a few questions about your service; we write it, a person reads it, and you have it in 2 working days.", moment: 0 },
  "gdpr-law": { tag: "The law", headline: "A GDPR policy covering UK GDPR, the Data Protection Act 2018 and the Caldicott Principles", sub: "Checked line by line against the law, and updated when it changes.", moment: 0 },
  "gdpr-updates": { tag: "Kept up to date", headline: "A GDPR policy that stays up to date", sub: "The first year of updates is included, so your policy changes when the law or guidance does.", moment: 0 },
  "gdpr-refund": { tag: "Our guarantee", headline: "A GDPR policy with a 14 day refund guarantee", sub: "If it is not right for your service, tell us within 14 days and we refund it in full.", moment: 0 },
  "gdpr-template-vs": { tag: "Not a template", headline: "Why a GDPR template is not enough for a care service", sub: "Templates are generic and go out of date. Yours is written for the way your service works and checked against the law.", moment: 0 },
  "gdpr-cqc-requirements": { tag: "CQC requirements", headline: "What CQC expects from your GDPR policy", sub: "Inspectors look at how you keep, share and protect people’s information. Your policy covers each part.", moment: 0 },
}
