// GENERATED by carestream-theme-preview/gen_pricing_data.py — do not edit by hand.
//
// The three plans, the forty-five-row comparison table and the pricing FAQs, taken from the
// approved theme. Generated rather than retyped: a hand-copied comparison table is how a tick
// ends up in the wrong column on the page that decides whether someone buys.
//
// Prices here are £85 / £230 / £385, which match the agreed tiers.

export interface PricingPlan {
  name: string
  price: string
  annual: string
  line: string
  badge: string
  badgeQuiet: boolean
  features: { text: string; more: boolean }[]
  ctaHref: string
  ctaLabel: string
  highlight: boolean
}

/** true = included, false = not included, a string = the limit ("Up to 25", "500 per month"). */
export type PricingValue = boolean | string

export interface PricingGroup {
  group: string
  rows: { label: string; values: PricingValue[] }[]
}

export const PRICING: {
  plans: PricingPlan[]
  groups: PricingGroup[]
  faqs: { q: string; a: string }[]
} = {
  "plans": [
    {
      "name": "Starter",
      "line": "For a single service getting its policies and staff answers in order.",
      "price": "£85 per month",
      "annual": "£850 a year if you pay annually",
      "badge": "",
      "badgeQuiet": false,
      "features": [
        {
          "text": "10 annual training allocations a month",
          "more": false
        },
        {
          "text": "Up to 25 policies, 1 handbook, 10 staff users",
          "more": false
        },
        {
          "text": "500 questions a month",
          "more": false
        },
        {
          "text": "Chat, email and voice access",
          "more": false
        },
        {
          "text": "Basic analytics and the regulatory knowledge base",
          "more": false
        }
      ],
      "ctaHref": "/register",
      "ctaLabel": "Start free trial",
      "highlight": false
    },
    {
      "name": "Professional",
      "line": "For services that need the policy intelligence and the training evidence.",
      "price": "£230 per month",
      "annual": "£2,300 a year if you pay annually",
      "badge": "Most popular",
      "badgeQuiet": false,
      "features": [
        {
          "text": "30 annual training allocations a month",
          "more": false
        },
        {
          "text": "Unlimited policies, handbooks and staff users",
          "more": false
        },
        {
          "text": "5,000 questions a month",
          "more": false
        },
        {
          "text": "Policy gap detection and CQC wording alignment",
          "more": false
        },
        {
          "text": "Face to face training and the full matrix",
          "more": false
        },
        {
          "text": "CQC evidence pack and training payroll report",
          "more": false
        },
        {
          "text": "Advanced analytics and the CQC readiness report",
          "more": false
        }
      ],
      "ctaHref": "/register",
      "ctaLabel": "Start free trial",
      "highlight": true
    },
    {
      "name": "Enterprise",
      "line": "For groups running several services, with audits and workforce records.",
      "price": "£385 per month",
      "annual": "£3,850 a year if you pay annually",
      "badge": "Everything included",
      "badgeQuiet": true,
      "features": [
        {
          "text": "Unlimited annual training allocations",
          "more": false
        },
        {
          "text": "Everything in Professional, plus:",
          "more": true
        },
        {
          "text": "Build your own audits, linked to training",
          "more": false
        },
        {
          "text": "Effectiveness of training and training impact",
          "more": false
        },
        {
          "text": "Multi site group console and benchmarking",
          "more": false
        },
        {
          "text": "Workforce compliance register and expiry alerts",
          "more": false
        },
        {
          "text": "Priority support and a dedicated manager",
          "more": false
        }
      ],
      "ctaHref": "/register",
      "ctaLabel": "Start free trial",
      "highlight": false
    }
  ],
  "groups": [
    {
      "group": "Plans and limits",
      "rows": [
        {
          "label": "Annual training allocations",
          "values": [
            "10 per month",
            "30 per month",
            "Unlimited"
          ]
        },
        {
          "label": "Policies stored",
          "values": [
            "Up to 25",
            "Unlimited",
            "Unlimited"
          ]
        },
        {
          "label": "Staff handbooks",
          "values": [
            "1",
            "Unlimited",
            "Unlimited"
          ]
        },
        {
          "label": "Staff users",
          "values": [
            "Up to 10",
            "Unlimited",
            "Unlimited"
          ]
        },
        {
          "label": "Questions answered",
          "values": [
            "500 per month",
            "5,000 per month",
            "Unlimited"
          ]
        },
        {
          "label": "Languages in the staff hub",
          "values": [
            "60+",
            "60+",
            "60+"
          ]
        }
      ]
    },
    {
      "group": "Staff hub and access",
      "rows": [
        {
          "label": "Web chat interface",
          "values": [
            true,
            true,
            true
          ]
        },
        {
          "label": "Email interface",
          "values": [
            true,
            true,
            true
          ]
        },
        {
          "label": "Voice input",
          "values": [
            true,
            true,
            true
          ]
        },
        {
          "label": "Your own knowledge base, built automatically",
          "values": [
            true,
            true,
            true
          ]
        },
        {
          "label": "Your own knowledge base, manual entries",
          "values": [
            "Up to 50",
            "Unlimited",
            "Unlimited"
          ]
        },
        {
          "label": "External regulatory knowledge base",
          "values": [
            true,
            true,
            true
          ]
        }
      ]
    },
    {
      "group": "Policies and approvals",
      "rows": [
        {
          "label": "Document version history",
          "values": [
            true,
            true,
            true
          ]
        },
        {
          "label": "Adopt a gap fix with tracked changes",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Role holder names merged into policies",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Print ready policy with letterhead and sign off",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Admin approval with full version history",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Care manager approval step, optional",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Care manager policies hub",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "External approval by one off link",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Approval trail and automatic republish to staff",
          "values": [
            false,
            true,
            true
          ]
        }
      ]
    },
    {
      "group": "Policy gap detection",
      "rows": [
        {
          "label": "Regulation coverage analysis",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "What to add, with example wording",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Where to add it, by target policy",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Legal basis and source on each recommendation",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Applicability by care setting and service profile",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Out of date content detection",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Cross policy consistency checking",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Regulation change tracking and alerts",
          "values": [
            false,
            true,
            true
          ]
        }
      ]
    },
    {
      "group": "CQC wording alignment",
      "rows": [
        {
          "label": "Wording aligned to the CQC quality statements",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Person centred rewording, in your policy voice",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Suggestions numbered and highlighted in the policy",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Adopt into your policy through review and approval",
          "values": [
            false,
            true,
            true
          ]
        }
      ]
    },
    {
      "group": "Training",
      "rows": [
        {
          "label": "Mandatory training by role",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Face to face training and matrix",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Training matrix with renewals and gaps",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Training generated from a policy update",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "CQC evidence pack, sign in sheets and certificates",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Training payroll report, PDF and CSV with costs",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "Effectiveness of training",
          "values": [
            false,
            false,
            true
          ]
        },
        {
          "label": "Training impact",
          "values": [
            false,
            false,
            true
          ]
        }
      ]
    },
    {
      "group": "Audits",
      "rows": [
        {
          "label": "Build your own audits",
          "values": [
            false,
            false,
            true
          ]
        },
        {
          "label": "Audits linked to training",
          "values": [
            false,
            false,
            true
          ]
        }
      ]
    },
    {
      "group": "Analytics and CQC readiness",
      "rows": [
        {
          "label": "Basic analytics",
          "values": [
            true,
            true,
            true
          ]
        },
        {
          "label": "Advanced analytics",
          "values": [
            false,
            true,
            true
          ]
        },
        {
          "label": "CQC readiness report",
          "values": [
            false,
            true,
            true
          ]
        }
      ]
    },
    {
      "group": "Workforce and multi site",
      "rows": [
        {
          "label": "Supervisions and appraisals tracking",
          "values": [
            true,
            true,
            true
          ]
        },
        {
          "label": "Workforce compliance register, DBS, right to work, registration, references",
          "values": [
            false,
            false,
            true
          ]
        },
        {
          "label": "Credential uploads and expiry alerts",
          "values": [
            false,
            false,
            true
          ]
        },
        {
          "label": "Multi site group console and benchmarking",
          "values": [
            false,
            false,
            true
          ]
        }
      ]
    },
    {
      "group": "Support and trial",
      "rows": [
        {
          "label": "Support",
          "values": [
            "Email",
            "Priority email and phone",
            "Priority and a dedicated manager"
          ]
        },
        {
          "label": "Free trial",
          "values": [
            "14 days",
            "14 days",
            "14 days"
          ]
        }
      ]
    }
  ],
  "faqs": [
    {
      "q": "Can we change plan later?",
      "a": "Yes, at any point. Moving up takes effect immediately and moving down takes effect at your next renewal."
    },
    {
      "q": "What counts as an annual training allocation?",
      "a": "One module assigned to one staff member for the year. A Starter plan can assign ten a month, which is a hundred and twenty across a year."
    },
    {
      "q": "Is there a setup fee?",
      "a": "No. Every plan includes a fourteen day free trial and you are not charged until day fifteen."
    },
    {
      "q": "What happens at the end of the trial?",
      "a": "Nothing automatic. You choose a plan to carry on, and if you do not, the account pauses rather than deleting anything."
    },
    {
      "q": "Do you charge per staff member?",
      "a": "No. Professional and Enterprise include unlimited staff users, and Starter includes ten."
    },
    {
      "q": "We run several homes. Which plan?",
      "a": "Enterprise, which includes the group console and benchmarking across sites. Talk to us about group pricing if you run more than three services."
    },
    {
      "q": "Can we pay annually?",
      "a": "Yes, and it saves two months against the monthly price on every plan."
    },
    {
      "q": "Do you offer a discount for charities?",
      "a": "Talk to us. We look at these case by case rather than publishing a blanket rate."
    }
  ]
}
