// GENERATED by carestream-theme-preview/gen_page_icons.py — do not edit by hand.
//
//   python3 gen_page_icons.py rag src/lib/rag-icons.ts RAG_ICONS 6
//
// The icons on /rag, in document order. They are not copy, so they are not in the slot set.
// Re-run the generator if the design changes.
//
// Shapes, not markup: the template builds real <path>/<circle>/<rect> elements from these.
// Colour and size come from the stylesheet, so nothing here carries a style.

import type { IconShape } from '@/components/marketing/setting-page-v2'

export const RAG_ICONS: IconShape[][] = [
  [
    {
      "tag": "path",
      "d": "M12 3l7 3v6c0 4.4-3 7.6-7 9-4-1.4-7-4.6-7-9V6z"
    },
    {
      "tag": "path",
      "d": "M9 12l2 2 4-4"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z"
    },
    {
      "tag": "path",
      "d": "M14 3v5h5M9 13h6M9 17h4"
    }
  ],
  [
    {
      "tag": "circle",
      "cx": "11",
      "cy": "11",
      "r": "7"
    },
    {
      "tag": "path",
      "d": "m20 20-3.5-3.5"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M4 7h16M4 12h16M4 17h10"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M22 10 12 5 2 10l10 5z"
    },
    {
      "tag": "path",
      "d": "M6 12v5c3 2 9 2 12 0v-5"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"
    },
    {
      "tag": "circle",
      "cx": "9",
      "cy": "7",
      "r": "4"
    },
    {
      "tag": "path",
      "d": "M22 21v-2a4 4 0 0 0-3-3.9"
    }
  ]
]
