// GENERATED by carestream-theme-preview/gen_page_icons.py — do not edit by hand.
//
//   python3 gen_page_icons.py regulatory-knowledge src/lib/regulatory-knowledge-icons.ts REGULATORY_KNOWLEDGE_ICONS 6
//
// The icons on /regulatory-knowledge, in document order. They are not copy, so they are not in the slot set.
// Re-run the generator if the design changes.
//
// Shapes, not markup: the template builds real <path>/<circle>/<rect> elements from these.
// Colour and size come from the stylesheet, so nothing here carries a style.

import type { IconShape } from '@/components/marketing/setting-page-v2'

export const REGULATORY_KNOWLEDGE_ICONS: IconShape[][] = [
  [
    {
      "tag": "rect",
      "x": "4",
      "y": "10",
      "width": "16",
      "height": "11",
      "rx": "2"
    },
    {
      "tag": "path",
      "d": "M8 10V7a4 4 0 0 1 8 0v3"
    }
  ],
  [
    {
      "tag": "rect",
      "x": "5",
      "y": "3",
      "width": "14",
      "height": "18",
      "rx": "2"
    },
    {
      "tag": "path",
      "d": "M9 8h6"
    },
    {
      "tag": "path",
      "d": "M9 12h6"
    },
    {
      "tag": "path",
      "d": "M9 16h4"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"
    },
    {
      "tag": "path",
      "d": "m9 12 2 2 4-4"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M3 12h3l2-5 3 10 2.5-7 2 4h5.5"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M12 3v18"
    },
    {
      "tag": "path",
      "d": "M6 7 3 13h6z"
    },
    {
      "tag": "path",
      "d": "M18 7l-3 6h6z"
    },
    {
      "tag": "path",
      "d": "M5 7h14"
    },
    {
      "tag": "path",
      "d": "M8 21h8"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M4 19.5V5a2 2 0 0 1 2-2h13v18H6a2 2 0 0 1-2-2z"
    },
    {
      "tag": "path",
      "d": "M19 17H6a2 2 0 0 0-2 2"
    },
    {
      "tag": "path",
      "d": "M9 7h6"
    }
  ]
]
