// GENERATED by carestream-theme-preview/gen_page_icons.py — do not edit by hand.
//
//   python3 gen_page_icons.py training-platform src/lib/training-platform-icons.ts TRAINING_PLATFORM_ICONS 12
//
// The icons on /training-platform, in document order. They are not copy, so they are not in the slot set.
// Re-run the generator if the design changes.
//
// Shapes, not markup: the template builds real <path>/<circle>/<rect> elements from these.
// Colour and size come from the stylesheet, so nothing here carries a style.

import type { IconShape } from '@/components/marketing/setting-page-v2'

export const TRAINING_PLATFORM_ICONS: IconShape[][] = [
  [
    {
      "tag": "path",
      "d": "M12 3v4M12 17v4M3 12h4M17 12h4"
    },
    {
      "tag": "circle",
      "cx": "12",
      "cy": "12",
      "r": "3"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M20 6 9 17l-5-5"
    }
  ],
  [
    {
      "tag": "circle",
      "cx": "12",
      "cy": "12",
      "r": "9"
    },
    {
      "tag": "path",
      "d": "M3 12h18M12 3c2.5 3 2.5 15 0 18M12 3c-2.5 3-2.5 15 0 18"
    }
  ],
  [
    {
      "tag": "rect",
      "x": "3",
      "y": "5",
      "width": "18",
      "height": "16",
      "rx": "2"
    },
    {
      "tag": "path",
      "d": "M3 10h18M8 3v4M16 3v4"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M18 8a6 6 0 0 0-12 0c0 7-3 8-3 8h18s-3-1-3-8M13.7 21a2 2 0 0 1-3.4 0"
    }
  ],
  [
    {
      "tag": "rect",
      "x": "2",
      "y": "6",
      "width": "20",
      "height": "12",
      "rx": "2"
    },
    {
      "tag": "circle",
      "cx": "12",
      "cy": "12",
      "r": "2.5"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M4 20V10M10 20V4M16 20v-7M22 20H2"
    }
  ],
  [
    {
      "tag": "circle",
      "cx": "12",
      "cy": "12",
      "r": "9"
    },
    {
      "tag": "path",
      "d": "M12 7v5l3 2"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z"
    },
    {
      "tag": "path",
      "d": "M14 3v5h5M9 14l2 2 4-4"
    }
  ],
  [
    {
      "tag": "rect",
      "x": "3",
      "y": "3",
      "width": "7",
      "height": "7",
      "rx": "1"
    },
    {
      "tag": "rect",
      "x": "14",
      "y": "3",
      "width": "7",
      "height": "7",
      "rx": "1"
    },
    {
      "tag": "rect",
      "x": "3",
      "y": "14",
      "width": "7",
      "height": "7",
      "rx": "1"
    },
    {
      "tag": "rect",
      "x": "14",
      "y": "14",
      "width": "7",
      "height": "7",
      "rx": "1"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M4 7h16M4 12h16M4 17h10"
    }
  ],
  [
    {
      "tag": "circle",
      "cx": "12",
      "cy": "12",
      "r": "9"
    },
    {
      "tag": "path",
      "d": "M12 8v4l3 2"
    }
  ]
]
