// GENERATED by carestream-theme-preview/gen_page_icons.py — do not edit by hand.
//
//   python3 gen_page_icons.py trust src/lib/trust-icons.ts TRUST_ICONS 9
//
// The icons on /trust, in document order. They are not copy, so they are not in the slot set.
// Re-run the generator if the design changes.
//
// Shapes, not markup: the template builds real <path>/<circle>/<rect> elements from these.
// Colour and size come from the stylesheet, so nothing here carries a style.

import type { IconShape } from '@/components/marketing/setting-page-v2'

export const TRUST_ICONS: IconShape[][] = [
  [
    {
      "tag": "path",
      "d": "M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"
    },
    {
      "tag": "circle",
      "cx": "12",
      "cy": "7",
      "r": "4"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"
    },
    {
      "tag": "path",
      "d": "M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 1 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.6 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 1 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.6a1.65 1.65 0 0 0 1-1.51V3a2 2 0 1 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 1 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M12 3v18"
    },
    {
      "tag": "path",
      "d": "m3 8 9-5 9 5"
    },
    {
      "tag": "path",
      "d": "M3 8v1a4 4 0 0 0 8 0V8"
    },
    {
      "tag": "path",
      "d": "M13 8v1a4 4 0 0 0 8 0V8"
    },
    {
      "tag": "path",
      "d": "M5 21h14"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"
    },
    {
      "tag": "path",
      "d": "M14 2v6h6"
    },
    {
      "tag": "path",
      "d": "M9 15h6"
    },
    {
      "tag": "path",
      "d": "M9 11h6"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M12 3v18"
    },
    {
      "tag": "path",
      "d": "m3 8 9-5 9 5"
    },
    {
      "tag": "path",
      "d": "M3 8v1a4 4 0 0 0 8 0V8"
    },
    {
      "tag": "path",
      "d": "M13 8v1a4 4 0 0 0 8 0V8"
    },
    {
      "tag": "path",
      "d": "M5 21h14"
    }
  ],
  [
    {
      "tag": "circle",
      "cx": "12",
      "cy": "12",
      "r": "9"
    },
    {
      "tag": "circle",
      "cx": "9.5",
      "cy": "9.5",
      "r": "1"
    },
    {
      "tag": "circle",
      "cx": "14.5",
      "cy": "13.5",
      "r": "1"
    },
    {
      "tag": "circle",
      "cx": "9",
      "cy": "15",
      "r": "1"
    }
  ],
  [
    {
      "tag": "circle",
      "cx": "11",
      "cy": "11",
      "r": "7"
    },
    {
      "tag": "path",
      "d": "m21 21-4.3-4.3"
    }
  ],
  [
    {
      "tag": "path",
      "d": "M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"
    },
    {
      "tag": "rect",
      "x": "8",
      "y": "2",
      "width": "8",
      "height": "4",
      "rx": "1"
    },
    {
      "tag": "path",
      "d": "m9 14 2 2 4-4"
    }
  ]
]
