// GENERATED by carestream-theme-preview/gen_who_its_for.py — do not edit by hand.
//
// The twenty-two setting panels on /who-its-for, plus the four shared cards and the role rows.
// A hundred and forty paragraphs, generated rather than carried across by hand.
//
// NOTE the twenty-two: this page covers the fuller list of registered settings, not the eleven
// that have pages of their own under SETTINGS_LIST. The two are deliberately different and
// should not be reconciled without a decision.

export interface WhoPanel {
  id: string
  num: string
  title: string
  tag: string
  desc: string
  points: string[]
  topicsLabel: string
  topics: string[]
  exBadge: string
  exLabel: string
  question: string
  sourcesLabel: string
  sources: string[]
  coversLabel: string
  covers: string[]
  mapsLabel: string
  maps: { ref: string; body: string }[]
}

export const WHO_ITS_FOR: {
  sections: { label: string; heading: string; paras: string[] }[]
  panels: WhoPanel[]
  cards: { title: string; body: string }[]
  pills: { href: string; label: string }[]
  roles: { role: string; body: string; points: string[] }[]
  note: { title: string; paras: string[] }
} = {
  "sections": [
    {
      "label": "",
      "heading": "Built for every registered care provider.",
      "paras": [
        "If your organisation has internal policies and a team that needs to follow them, CareStreamAI turns those policies into a 24-hour knowledge resource for every member of staff."
      ]
    },
    {
      "label": "Care settings",
      "heading": "Find your setting.",
      "paras": [
        "Every registered setting has its own pressures. Pick yours to see the questions staff ask, the policy areas they ask about, and what it maps to."
      ]
    },
    {
      "label": "Across every setting",
      "heading": "The same four things, whatever you run.",
      "paras": [
        "Chat, email, and voice. Staff access policies whichever way suits their role and environment.",
        "Every staff member gets the same quality of policy access regardless of their first language.",
        "Every query is logged. Your CQC Readiness Report is generated automatically, not assembled under pressure.",
        "Upload a new policy version and CareStreamAI answers from it immediately. Staff never read superseded guidance."
      ]
    },
    {
      "label": "By role",
      "heading": "What it changes, depending on your job.",
      "paras": []
    },
    {
      "label": "",
      "heading": "",
      "paras": [
        "CareStreamAI does not provide professional, legal, clinical, or regulatory advice of any kind. The system retrieves and presents accurate information drawn directly from your organisation's own approved policies, procedures, and handbooks, and from publicly available external regulations and guidance. All responses reflect the content of those documents as uploaded and maintained by your organisation.",
        "Staff should always exercise their own professional judgement and, where required, seek guidance from a registered manager, clinician, or qualified professional. CareStreamAI is an information access tool. It does not replace supervision, professional registration, clinical decision-making, or the duty of care that rests with your organisation and its staff."
      ]
    },
    {
      "label": "",
      "heading": "See it against your own policies.",
      "paras": [
        "Whatever you run, upload what you already have and see it working inside a fortnight."
      ]
    }
  ],
  "pills": [
    {
      "href": "#residential-care-homes",
      "label": "Residential Care Homes"
    },
    {
      "href": "#nursing-homes",
      "label": "Nursing Homes"
    },
    {
      "href": "#home-care",
      "label": "Home Care and Domiciliary Care"
    },
    {
      "href": "#supported-living",
      "label": "Supported Living"
    },
    {
      "href": "#extra-care",
      "label": "Extra Care and Assisted Living"
    },
    {
      "href": "#hospices",
      "label": "Hospices and Palliative Care"
    },
    {
      "href": "#day-services",
      "label": "Day Services and Respite Care"
    },
    {
      "href": "#mental-health",
      "label": "Mental Health Residential Services"
    },
    {
      "href": "#learning-disability",
      "label": "Learning Disability Services"
    },
    {
      "href": "#reablement",
      "label": "Reablement and Intermediate Care"
    },
    {
      "href": "#community-care",
      "label": "Community Care and Outreach"
    },
    {
      "href": "#live-in-care",
      "label": "Live-in Care"
    },
    {
      "href": "#complex-care",
      "label": "Complex Care"
    },
    {
      "href": "#shared-lives",
      "label": "Shared Lives Schemes"
    },
    {
      "href": "#substance-misuse",
      "label": "Substance Misuse and Rehabilitation"
    },
    {
      "href": "#independent-hospitals",
      "label": "Independent Hospitals and Clinics"
    },
    {
      "href": "#gp-practices",
      "label": "GP Practices and Primary Care"
    },
    {
      "href": "#dental-practices",
      "label": "Dental Practices"
    },
    {
      "href": "#nursing-agencies",
      "label": "Nursing and Care Staffing Agencies"
    },
    {
      "href": "#mental-health-hospitals",
      "label": "Independent Mental Health Hospitals"
    },
    {
      "href": "#neuro-rehabilitation",
      "label": "Neuro-rehabilitation and Brain Injury"
    },
    {
      "href": "#prison-healthcare",
      "label": "Prison and Secure Healthcare"
    }
  ],
  "panels": [
    {
      "id": "residential-care-homes",
      "num": "01",
      "title": "Residential Care Homes",
      "tag": "Policy support for every shift, not just office hours.",
      "desc": "Residential care homes rely on confident, consistent practice around the clock. CareStreamAI gives night staff, international carers, and new starters the same immediate access to your approved policies as your most experienced team member.",
      "points": [
        "Night staff access the correct care and medication procedures instantly, without calling the manager out of hours.",
        "International and multilingual carers ask questions in their own language and receive answers drawn directly from your policy library.",
        "CQC inspection evidence is built automatically from every query, replacing the manual process of assembling compliance records under pressure.",
        "Policy gap detection highlights what your library is missing before an inspector does."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Falls Management",
        "Medication Administration",
        "Infection Control",
        "Safeguarding Adults",
        "End of Life Care",
        "Moving and Handling"
      ],
      "exBadge": "Voice",
      "exLabel": "A real question from this setting",
      "question": "A resident has just had a fall. It is 3am. What observations do I need to carry out and how often?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Falls and Post-Fall Management Policy",
        "CQC Regulation 12, Safe Care and Treatment",
        "NICE CG161, Falls in Older People"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "Your home's post-fall observation checklist and exact timing intervals",
        "When to escalate to the on-call GP or out-of-hours service",
        "Mandatory incident form requirements before end of shift",
        "How your policy aligns with CQC Reg 12 and NICE guidance"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Covers medication management, falls prevention, and infection control obligations across all shifts."
        },
        {
          "ref": "CQC Regulation 13, Safeguarding",
          "body": "Requires robust safeguarding procedures that every staff member can access and act on immediately."
        },
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "Mandates accurate, complete records and documented evidence of policy engagement."
        }
      ]
    },
    {
      "id": "nursing-homes",
      "num": "02",
      "title": "Nursing Homes",
      "tag": "Clinical procedures at the point of care, not at the end of a corridor.",
      "desc": "Nursing homes carry a higher level of clinical complexity than any other registered care setting. CareStreamAI ensures your clinical and care staff find the right procedure exactly when they need it, regardless of the hour or their first language.",
      "points": [
        "Clinical staff access infection control, wound care, medication management, and end of life procedures in seconds.",
        "Voice notes mean staff can ask a procedure question hands-free in a clinical situation, without leaving a resident.",
        "Every query is logged with the staff member, time, and policy referenced, providing automatic CQC evidence of staff procedure engagement.",
        "Policy gap detection identifies missing clinical protocols before a CQC inspection or clinical audit."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Catheter Care",
        "Wound Management",
        "Infection Control",
        "Medication Administration",
        "Pressure Area Care",
        "End of Life Care"
      ],
      "exBadge": "Voice",
      "exLabel": "A real question from this setting",
      "question": "A resident has a urinary catheter. They have not passed urine in six hours and the catheter bag is empty. What does the catheter care policy say I should do?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Catheter Care and Management Policy",
        "CQC Regulation 12, Safe Care and Treatment",
        "NICE NG113, Urinary Tract Infection in Adults"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "Step-by-step catheter patency check, including kinking, positioning, and bladder palpation",
        "Your policy threshold for contacting the on-call GP or district nurse",
        "Signs of urinary tract infection or catheter-associated complications requiring urgent escalation",
        "Mandatory fluid balance and catheter record entries before handing over to the next shift"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Clinical procedures must be accessible and applied consistently across day and night shifts."
        },
        {
          "ref": "NICE NG113, Urinary Tract Infection in Adults",
          "body": "Provides clinical guidance on catheter care and infection prevention in nursing settings."
        },
        {
          "ref": "CQC Regulation 11, Need for Consent",
          "body": "Informed consent must be sought and documented before every clinical intervention."
        }
      ]
    },
    {
      "id": "home-care",
      "num": "03",
      "title": "Home Care and Domiciliary Care",
      "tag": "Policy access for a workforce that is never in one place.",
      "desc": "Domiciliary care staff work alone, often in challenging environments, without a colleague or manager nearby. CareStreamAI gives your dispersed workforce instant access to your procedures via the hub or voice, wherever they are.",
      "points": [
        "Field-based carers get immediate policy answers in the hub or by voice note while travelling between visits.",
        "Lone workers check safeguarding, consent, and incident procedures without travelling to the office or waiting for a callback.",
        "Managers see query patterns across the entire dispersed workforce from one dashboard, revealing where guidance or retraining is needed.",
        "All queries are logged by staff member and location, supporting lone working audits and CQC inspection evidence."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Lone Working",
        "Safeguarding Adults",
        "Medication Administration",
        "Missed Visit Procedures",
        "Manual Handling",
        "Infection Control"
      ],
      "exBadge": "Voice",
      "exLabel": "A real question from this setting",
      "question": "I have arrived at a service user's home and they are not answering the door. The lights are on and I can see them through the window but they are not responding. What is the procedure?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Lone Working and Missed Visit Policy",
        "Safeguarding Adults Policy",
        "CQC Regulation 13, Safeguarding Service Users"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "Exact steps to take before calling emergency services, including contacting the office and next of kin",
        "When your policy requires you to call 999 and request a welfare check without delay",
        "What to record on the missed visit log and how to notify your manager immediately",
        "How this interaction is captured as a safeguarding concern and the referral threshold"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 13, Safeguarding Service Users",
          "body": "Safeguarding procedures must be accessible to lone workers in any location at any time."
        },
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Safe medication and infection control procedures apply in every home environment visited."
        },
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "Every visit, missed contact, and incident must be recorded accurately in real time."
        }
      ]
    },
    {
      "id": "supported-living",
      "num": "04",
      "title": "Supported Living",
      "tag": "Consistent, person-centred practice across every house.",
      "desc": "Supported living services operate across multiple dispersed properties with varying support needs. CareStreamAI gives support workers in every house access to the same approved procedures and individual care guidance, at any time.",
      "points": [
        "Support workers in dispersed houses access behaviour support plans, safeguarding procedures, and risk management guidance in seconds.",
        "Staff in every property work from the same centrally approved policy library, eliminating inconsistent practice between houses.",
        "All query and access data is visible to managers across all sites from a single dashboard.",
        "Multilingual staff access procedures in their own language from day one, supporting rapid onboarding in high-turnover services."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Positive Behaviour Support",
        "Safeguarding Adults",
        "Mental Capacity",
        "Risk Management",
        "Restrictive Practice",
        "Community Access Safety"
      ],
      "exBadge": "Chat",
      "exLabel": "A real question from this setting",
      "question": "A resident is becoming very distressed and is showing early warning signs listed in their behaviour support plan. Their key worker is not on shift. What should I do right now?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Positive Behaviour Support Policy",
        "Individual Behaviour Support Plan",
        "NICE NG11, Challenging Behaviour and Learning Disabilities"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "The proactive and reactive strategies from the resident's individual PBS plan, in the correct sequence",
        "Environmental adjustments your policy requires before any other intervention",
        "Your escalation threshold and who to contact if early strategies do not reduce distress",
        "Recording requirements, including the time, triggers, and strategies used, before end of shift"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 11, Need for Consent",
          "body": "All support must be delivered with valid consent or a documented best interests decision."
        },
        {
          "ref": "CQC Regulation 13, Safeguarding",
          "body": "Safeguarding procedures must be embedded and accessible across every dispersed property."
        },
        {
          "ref": "NICE NG11, Challenging Behaviour and Learning Disabilities",
          "body": "PBS approaches underpin safe, person-centred support and guide all restrictive practice decisions."
        }
      ]
    },
    {
      "id": "extra-care",
      "num": "05",
      "title": "Extra Care and Assisted Living",
      "tag": "Balancing housing and care regulation in one policy library.",
      "desc": "Extra care and assisted living settings navigate both housing and care regulation. CareStreamAI holds your full policy library, giving staff covering multiple flats or wings the right answer from the right document every time.",
      "points": [
        "Staff covering multiple properties access the correct care and tenancy procedures quickly, without searching through separate document stores.",
        "Managers maintain housing and care policy libraries in one place, with version control ensuring staff always access current procedures.",
        "CQC and housing regulation compliance evidence is captured automatically across all interactions.",
        "International staff from diverse backgrounds engage with your full policy library in their own language from their first shift."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Mental Capacity and Consent",
        "Medication Administration",
        "Falls Prevention",
        "Tenancy and Care Procedures",
        "Safeguarding Adults",
        "Moving and Handling"
      ],
      "exBadge": "Email",
      "exLabel": "A real question from this setting",
      "question": "A resident is refusing their medication this morning and saying they do not want it today. How do I carry out a capacity assessment and what do I need to record?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Mental Capacity and Consent Policy",
        "Medication Administration Policy",
        "Mental Capacity Act 2005, Sections 2 and 3"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "The two-stage Mental Capacity Act test your policy requires, applied to this specific decision",
        "How to record the capacity assessment in the medication administration record",
        "Who to notify if you assess the resident as lacking capacity for this decision",
        "Your policy's best interests process, including family involvement and GP notification"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "Mental Capacity Act 2005, Sections 2 and 3",
          "body": "Staff must apply the two-stage capacity test before any decision is made on a resident's behalf."
        },
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Safe care obligations cover both the care and housing elements of the service."
        },
        {
          "ref": "CQC Regulation 10, Dignity and Respect",
          "body": "Residents' rights as tenants and care recipients must be upheld in every interaction."
        }
      ]
    },
    {
      "id": "hospices",
      "num": "06",
      "title": "Hospices and Palliative Care",
      "tag": "The right procedure when it matters most.",
      "desc": "In hospice and palliative care, staff face some of the most emotionally and clinically complex situations in the sector. CareStreamAI ensures your full clinical and care procedure library is available to every staff member, at any hour.",
      "points": [
        "Clinical and care staff access complex symptom management, pain management, and end of life care protocols at any time, day or night.",
        "Bereavement support, family communication, and spiritual care procedures are always available without delay.",
        "CQC inspection evidence demonstrating dignity and person-centred care practice is built from every query and policy interaction.",
        "Staff working across inpatient and community palliative care access the same approved procedure library from any channel."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Syringe Driver Management",
        "Breakthrough Pain Protocol",
        "DNACPR Procedures",
        "Bereavement Support",
        "Controlled Drug Administration",
        "End of Life Care Planning"
      ],
      "exBadge": "Voice",
      "exLabel": "A real question from this setting",
      "question": "A patient on a syringe driver appears to be in breakthrough pain two hours after the driver was set up. What does the palliative pain management policy say I should check and when do I escalate?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Syringe Driver and Subcutaneous Infusion Policy",
        "Palliative Pain Management Protocol",
        "CQC Regulation 12, Safe Care and Treatment"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "Syringe driver site assessment checklist and what to look for at the infusion site",
        "Authorised breakthrough medication doses and the conditions under which you can administer them",
        "When your policy requires you to call the on-call palliative care team or prescriber",
        "Mandatory documentation in the controlled drug register and the patient's care record"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Clinical symptom management protocols must be accessible and followed correctly at all hours."
        },
        {
          "ref": "NICE NG31, Care of Dying Adults in the Last Days of Life",
          "body": "Provides nationally recognised guidance on comfort, dignity, and communication at end of life."
        },
        {
          "ref": "CQC Regulation 11, Need for Consent",
          "body": "Advance decisions and DNACPR documentation must be accessible and acted on correctly."
        }
      ]
    },
    {
      "id": "day-services",
      "num": "07",
      "title": "Day Services and Respite Care",
      "tag": "Policy access that moves with your team throughout the day.",
      "desc": "Day services and respite care staff often move between multiple service users and environments without a fixed base. CareStreamAI gives your team instant procedure access wherever the working day takes them.",
      "points": [
        "Staff moving between service users throughout the day access procedures via the hub or voice note hands-free, without pausing the activity.",
        "Safeguarding, incident, and emergency procedures are always available, including off-site and community visits.",
        "Respite coordinators can log and review every procedure query from their team from a single dashboard.",
        "Quick query logging reduces the administrative burden on staff during a busy, activity-led day."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Epilepsy and Seizure Management",
        "First Aid and Emergencies",
        "Safeguarding Adults",
        "Community Access Risk",
        "Medication Administration",
        "Incident Reporting"
      ],
      "exBadge": "Chat",
      "exLabel": "A real question from this setting",
      "question": "A service user has had a tonic-clonic seizure during an activity session. The seizure has stopped after two minutes. What does the epilepsy management policy say I need to do right now?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Epilepsy and Seizure Management Policy",
        "First Aid and Emergency Procedures Policy",
        "CQC Regulation 12, Safe Care and Treatment"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "Immediate post-seizure observations and the recovery position guidance from your policy",
        "Your policy's threshold for calling 999, including seizure duration and the five-minute rule",
        "Who to notify, including parents, carers, and the registered manager, and within what timeframe",
        "Incident form requirements, including seizure log entries, before the end of the session"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Emergency procedures and medical management plans must be accessible during all activities and outings."
        },
        {
          "ref": "CQC Regulation 13, Safeguarding",
          "body": "Safeguarding procedures apply in day service environments and during all community visits."
        },
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "All incidents, near misses, and emergency responses must be recorded on the day they occur."
        }
      ]
    },
    {
      "id": "mental-health",
      "num": "08",
      "title": "Mental Health Residential Services",
      "tag": "Crisis procedures, de-escalation, and risk guidance when your team needs them.",
      "desc": "Mental health residential services require staff to access complex risk, medication, and de-escalation procedures under pressure. CareStreamAI gives your whole team immediate procedure access around the clock.",
      "points": [
        "Risk assessment, de-escalation, and medication procedures are available instantly, including during active crisis situations.",
        "Voice note access means staff can ask a procedure question without breaking focus or leaving a service user unattended.",
        "Every procedure query is logged with staff member, time, and context, supporting post-incident reviews and CQC evidence.",
        "Policy updates reach the whole team immediately, with access tracked so managers know when a change has landed."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "De-escalation and Restraint",
        "Self-Harm Risk Management",
        "Observation Levels",
        "Medication Management",
        "Mental Health Act Procedures",
        "Post-Incident Debrief"
      ],
      "exBadge": "Voice",
      "exLabel": "A real question from this setting",
      "question": "A resident is becoming increasingly agitated, is refusing to engage, and has a documented history of self-harm. What does the de-escalation policy say I should do and at what point do I call for support?",
      "sourcesLabel": "Answered from",
      "sources": [
        "De-escalation and Positive Engagement Policy",
        "Self-Harm Risk Management Policy",
        "CQC Regulation 17, Good Governance"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "The staged de-escalation approach from your policy, including verbal and environmental strategies in sequence",
        "Your threshold for a two-person response and the circumstances that require an immediate manager call",
        "Observations your policy requires following a self-harm risk episode, and who records them",
        "Post-incident debrief requirements and what must be entered in the risk management record"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "Post-incident reviews and accurate risk documentation are core compliance requirements."
        },
        {
          "ref": "Mental Health Act 1983, Sections 2 and 3",
          "body": "Detention, consent to treatment, and leave procedures must be followed precisely and documented."
        },
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Risk management and medication procedures must be accessible and consistently applied around the clock."
        }
      ]
    },
    {
      "id": "learning-disability",
      "num": "09",
      "title": "Learning Disability Services",
      "tag": "Plain language procedure access for every member of your team.",
      "desc": "Learning disability and autism services rely on highly consistent, person-centred practice across residential, community, and day settings. CareStreamAI makes your full procedure library accessible to every staff member, in clear language, at any time.",
      "points": [
        "Support workers access positive behaviour support plans, safeguarding procedures, and individual care guidance in seconds.",
        "Multilingual staff access procedures in their own language, supporting a diverse workforce with varying English confidence.",
        "Managers track policy engagement across all registered services from a single dashboard, identifying where support or retraining is needed.",
        "Consistent procedure access across all service types reduces variation in support quality between different settings and teams."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Positive Behaviour Support",
        "Restrictive Practice",
        "Safeguarding Adults",
        "Mental Capacity and Best Interests",
        "Communication Support Plans",
        "Community Safety"
      ],
      "exBadge": "Email",
      "exLabel": "A real question from this setting",
      "question": "A service user has started repeatedly hitting themselves and it is escalating. What does the restrictive practice policy say about physical intervention and who has to authorise it?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Restrictive Practice and Physical Intervention Policy",
        "Positive Behaviour Support Policy",
        "NICE NG11, Challenging Behaviour and Learning Disabilities"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "The PBS-guided de-escalation steps your policy requires before any physical intervention is considered",
        "Which specific physical interventions are permitted under your policy and which are prohibited",
        "The authorisation requirement, including who must be notified and within what timeframe",
        "Post-incident recording obligations, including body map completion and the debrief process"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "NICE NG11, Challenging Behaviour and Learning Disabilities",
          "body": "PBS must be the primary framework for any behaviour that challenges, before restriction is considered."
        },
        {
          "ref": "CQC Regulation 13, Safeguarding",
          "body": "Safeguarding procedures must be accessible to all staff across residential, community, and day settings."
        },
        {
          "ref": "Mental Capacity Act 2005",
          "body": "Every decision made on a person's behalf must follow a documented best interests process."
        }
      ]
    },
    {
      "id": "reablement",
      "num": "10",
      "title": "Reablement and Intermediate Care",
      "tag": "Rapid onboarding and consistent practice during short, intensive care episodes.",
      "desc": "Reablement services are time-limited and intensely goal-focused, with staff often joining at short notice. CareStreamAI ensures your full procedure library is available to every team member from their very first shift.",
      "points": [
        "New staff access your full procedure library from day one, without waiting for a formal induction session.",
        "Clinical reablement procedures are available to therapy and care staff in the field via the hub or voice note.",
        "Every procedure query is logged throughout the reablement episode, providing automatic CQC evidence of consistent practice.",
        "Managers see which procedures are being queried most during the reablement period, informing team briefings and clinical supervision."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Falls Prevention and Management",
        "Reablement Goal Setting",
        "Moving and Handling",
        "Infection Control",
        "Medication Administration",
        "Discharge Planning"
      ],
      "exBadge": "Chat",
      "exLabel": "A real question from this setting",
      "question": "A service user attempted to stand from the chair without prompting and lost balance. They were not injured but are now unsettled. What is the falls protocol during a reablement episode and do I adjust today's goal?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Falls Prevention and Management Policy",
        "Reablement Goal Management Protocol",
        "CQC Regulation 12, Safe Care and Treatment"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "Post-incident checks your policy requires, including pain assessment and neurological observations",
        "Your protocol for pausing or modifying a reablement goal following a near-miss incident",
        "Who to notify, including the allocated occupational therapist or physiotherapist, and within what timeframe",
        "Incident recording requirements and what must be flagged in the next handover"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Falls management and manual handling procedures must be accessible to all reablement staff in the field."
        },
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "Goal progress, incidents, and care decisions must be recorded throughout the reablement episode."
        },
        {
          "ref": "NICE NG27, Rehabilitation After Critical Illness",
          "body": "Rehabilitation goals must be person-centred, time-limited, and reviewed regularly with the clinical team."
        }
      ]
    },
    {
      "id": "community-care",
      "num": "11",
      "title": "Community Care and Outreach",
      "tag": "Procedure access for staff who are never at a desk.",
      "desc": "Community care and outreach workers operate entirely in the field, often without access to an office, a desktop, or a colleague nearby. CareStreamAI gives them full procedure access via the channels they already use.",
      "points": [
        "Lone workers check safeguarding, consent, capacity, and incident procedures via the hub or voice note in any community setting.",
        "Policy updates reach the entire community workforce instantly, with access tracked so managers know the change has arrived.",
        "All three channels (chat, email, and voice) suit staff without regular access to a desk or an office computer.",
        "Every interaction is logged, supporting lone working safeguards and providing automatic evidence for CQC and commissioning audits."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Lone Working and Personal Safety",
        "Safeguarding Adults",
        "Financial Abuse and Exploitation",
        "Mental Capacity and Consent",
        "Medication Administration",
        "Infection Control"
      ],
      "exBadge": "Voice",
      "exLabel": "A real question from this setting",
      "question": "A service user has told me that their family member has been taking money from them without permission. What is the safeguarding procedure I need to follow right now, while I am still at the address?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Safeguarding Adults Policy",
        "Financial Abuse and Exploitation Procedure",
        "CQC Regulation 13, Safeguarding Service Users"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "Immediate steps your policy requires, including not investigating yourself or confronting the alleged perpetrator",
        "How to make a safeguarding referral to the local authority while still at the address",
        "Your policy's confidentiality and disclosure rules, including when you can share information without consent",
        "What to record today, including the exact words used by the service user, before leaving the visit"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 13, Safeguarding Service Users",
          "body": "Staff must recognise, report, and document safeguarding concerns in any community setting."
        },
        {
          "ref": "Care Act 2014, Section 42",
          "body": "Safeguarding enquiries must be initiated when abuse or neglect is suspected, regardless of location."
        },
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Lone workers must have access to safe care procedures during every community visit."
        }
      ]
    },
    {
      "id": "live-in-care",
      "num": "12",
      "title": "Live-in Care",
      "tag": "One carer, one home, and nobody in the next room to ask.",
      "desc": "Live-in carers work and sleep in a client's home, often for weeks at a time, with no colleague nearby and the office closed for most of their working day. CareStreamAI puts your policies, the client's care plan and your escalation routes on the carer's own phone, in the language they think in.",
      "points": [
        "A carer alone in a client’s home gets your approved answer at three in the morning, without waiting for the office to open.",
        "International carers ask in their own language and receive exactly the same guidance as an English-speaking colleague.",
        "Escalation routes, including the on-call manager and when to call 999, are one question away rather than pinned to a noticeboard somewhere else.",
        "Every query is logged, so care delivered out of sight of the office is still evidenced for inspection."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Deterioration and Escalation",
        "Medication",
        "Moving and Handling",
        "Safeguarding Adults",
        "Lone Working",
        "End of Life Care"
      ],
      "exBadge": "Voice",
      "exLabel": "A real question from this setting",
      "question": "My client is more confused and more breathless than usual and it is two in the morning. I am on my own. What am I supposed to do?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Deteriorating Health Policy",
        "Your On-Call and Escalation Procedure",
        "CQC Regulation 12, Safe Care and Treatment"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "The checks your policy asks you to carry out before escalating",
        "When to contact the on-call manager and when to call 999",
        "How to reassure and position your client while you wait",
        "What has to be recorded before the end of your shift"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Applies in full to care delivered by a single carer in a private home, with no colleague present."
        },
        {
          "ref": "CQC Regulation 13, Safeguarding",
          "body": "Requires every carer to recognise and raise concerns immediately, including from inside a client’s home."
        },
        {
          "ref": "CQC Regulation 18, Staffing",
          "body": "Requires staff to be competent and supported, including on long placements away from the rest of the team."
        }
      ]
    },
    {
      "id": "complex-care",
      "num": "13",
      "title": "Complex Care",
      "tag": "Clinical protocols, followed exactly, in somebody’s living room.",
      "desc": "Complex care packages put ventilators, tracheostomies, enteral feeding and seizure protocols into a family home, delivered by a small team on long shifts. CareStreamAI gives every member of that team your protocols and the client's plan, cited and current, at the moment they are needed.",
      "points": [
        "Nurses and carers check the current protocol at the bedside instead of relying on what was said at handover.",
        "Night staff on a long shift get your escalation route immediately when a client’s condition changes.",
        "New team members joining an established package start from your written protocol rather than from local habit.",
        "Every query is logged, evidencing that clinical guidance is live and in use inside the client’s home."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Tracheostomy Care",
        "Ventilation",
        "Enteral Feeding",
        "Seizure Management",
        "Medication",
        "Emergency Escalation"
      ],
      "exBadge": "Chat",
      "exLabel": "A real question from this setting",
      "question": "His oxygen saturations have dropped and suction is not clearing it. What does his protocol say I do next?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Tracheostomy and Suction Protocol",
        "The client's individual care plan",
        "CQC Regulation 12, Safe Care and Treatment"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "The escalation steps in the order your protocol sets them out",
        "When to call the clinical lead and when to call 999",
        "What must be recorded and who has to be informed",
        "The equipment checks to complete before the next shift starts"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Covers clinical protocols delivered away from any clinical setting, by a small team working alone."
        },
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "Requires accurate records and evidence that the protocol being followed is the current one."
        },
        {
          "ref": "CQC Regulation 18, Staffing",
          "body": "Requires staff to be competent for the specific clinical tasks in each package, and supported in them."
        }
      ]
    },
    {
      "id": "shared-lives",
      "num": "14",
      "title": "Shared Lives Schemes",
      "tag": "A carer supporting somebody in their own family home.",
      "desc": "Shared Lives carers are not on a rota and not in a building the scheme manages. They support an adult in their own home, usually alone, and their questions arrive in the evenings and at weekends. CareStreamAI gives them the scheme’s approved answers wherever they are.",
      "points": [
        "Carers get the scheme’s guidance without waiting for a supervising officer to be free.",
        "Consistent answers across every arrangement, so practice does not vary from household to household.",
        "Safeguarding thresholds and reporting routes are one question away, at the moment a concern arises.",
        "Every query is logged, giving the scheme evidence of how carers are supported between visits."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Safeguarding Adults",
        "Medication Support",
        "Money and Finances",
        "Consent and Capacity",
        "Breaks and Respite",
        "Recording and Reporting"
      ],
      "exBadge": "Voice",
      "exLabel": "A real question from this setting",
      "question": "The person I support wants to manage all of his own money from now on. What am I allowed to do and what do I have to record?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Shared Lives Carer Handbook",
        "Your Personal Money and Finances Policy",
        "CQC Regulation 9, Person-centred Care"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "What the scheme expects you to support rather than take over",
        "The records you keep, and where they go",
        "When to involve the supervising officer before anything changes",
        "How to raise a concern if you think somebody is at risk"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 9, Person-centred Care",
          "body": "Support has to fit the person and their household rather than a scheme-wide routine."
        },
        {
          "ref": "CQC Regulation 13, Safeguarding",
          "body": "Carers working in their own homes need the scheme’s threshold and referral route immediately to hand."
        },
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "The scheme must be able to show how carers are supported and how records are kept across every arrangement."
        }
      ]
    },
    {
      "id": "substance-misuse",
      "num": "15",
      "title": "Substance Misuse and Rehabilitation",
      "tag": "Detox and rehabilitation, where the right answer cannot wait until morning.",
      "desc": "Residential detox and rehabilitation services manage withdrawal, medication and risk around the clock, with a mix of clinical and recovery staff and a rota that changes often. CareStreamAI puts your protocols on every phone, in every language on the team.",
      "points": [
        "Night staff get your withdrawal and escalation protocols instantly rather than waiting for the clinical lead.",
        "Recovery workers and clinical staff work from the same written procedures, cited and current.",
        "New starters follow your protocol rather than practice learned at a previous service.",
        "Every query is logged, evidencing that your protocols are in daily use rather than filed."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Withdrawal and Detox",
        "Controlled Drugs",
        "Overdose Response",
        "Risk of Self-harm",
        "Safeguarding Adults",
        "Discharge and Aftercare"
      ],
      "exBadge": "Chat",
      "exLabel": "A real question from this setting",
      "question": "A resident has missed his medication and is showing withdrawal symptoms. It is the middle of the night. What do I do?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Medically Assisted Withdrawal Protocol",
        "Your Out of Hours Escalation Procedure",
        "CQC Regulation 12, Safe Care and Treatment"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "The observations your protocol requires, and how often to repeat them",
        "When to contact the on-call clinician and when to call 999",
        "How the missed dose is recorded and reported",
        "What to hand over at the end of the shift"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Covers medically assisted withdrawal, medicines management and emergency response at any hour."
        },
        {
          "ref": "CQC Regulation 13, Safeguarding",
          "body": "Requires staff to recognise and act on risk to a resident or from others, immediately and correctly."
        },
        {
          "ref": "CQC Regulation 18, Staffing",
          "body": "Requires competent, supported staff on every shift, including nights and weekends."
        }
      ]
    },
    {
      "id": "independent-hospitals",
      "num": "16",
      "title": "Independent Hospitals and Clinics",
      "tag": "Clinical governance that reaches the bank nurse on a Saturday.",
      "desc": "Independent hospitals and private clinics run on consultants, substantive staff and a large bank and agency workforce. CareStreamAI gives every one of them the same access to your governance, consent and infection control procedures, cited and current.",
      "points": [
        "Bank and agency clinicians reach your local procedure before they have to ask for it.",
        "Consent, surgical safety and infection control questions are answered from your documents, not from another provider’s habits.",
        "Duty of candour and incident reporting steps are available at the moment something goes wrong.",
        "Every query is logged, evidencing that governance is live rather than filed."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Consent",
        "Infection Prevention and Control",
        "Surgical Safety",
        "Medicines Management",
        "Incident Reporting",
        "Duty of Candour"
      ],
      "exBadge": "Chat",
      "exLabel": "A real question from this setting",
      "question": "The patient has changed her mind in the anaesthetic room. What does our consent policy require us to do now?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Consent Policy",
        "CQC Regulation 11, Need for Consent",
        "CQC Regulation 20, Duty of Candour"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "What must stop immediately, and who must be informed",
        "How the change of decision is documented",
        "Who speaks to the patient afterwards, and when",
        "What your policy requires before the list continues"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 11, Need for Consent",
          "body": "Consent must be valid at the point of the procedure, and staff need to know what to do when it is withdrawn."
        },
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Covers surgical safety, infection control and medicines across a workforce that changes shift to shift."
        },
        {
          "ref": "CQC Regulation 20, Duty of Candour",
          "body": "Requires a prompt, defined response when something goes wrong, which staff must be able to look up at the time."
        }
      ]
    },
    {
      "id": "gp-practices",
      "num": "17",
      "title": "GP Practices and Primary Care",
      "tag": "One answer for the whole practice team, from reception to the consulting room.",
      "desc": "A practice runs on protocols that are written once and then needed by receptionists, healthcare assistants, nurses and locums in completely different moments. CareStreamAI puts the current version in front of whoever is asking, without interrupting a clinician.",
      "points": [
        "Reception staff get your protocol for urgent symptoms, requests and complaints without pulling a clinician out of a consultation.",
        "Locums and new starters work from your practice’s own procedures from their first session.",
        "Cold chain, chaperone, safeguarding and significant event steps are answered from your own documents.",
        "Every query is logged, so the practice can see which protocols are relied on most and where they are unclear."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Chaperones",
        "Cold Chain and Vaccines",
        "Safeguarding",
        "Repeat Prescribing",
        "Significant Events",
        "Complaints"
      ],
      "exBadge": "Email",
      "exLabel": "A real question from this setting",
      "question": "A patient has phoned reception with chest pain and is refusing an ambulance. What is our protocol?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Urgent Symptoms and Triage Protocol",
        "Your Consent and Capacity Policy",
        "CQC Regulation 12, Safe Care and Treatment"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "Who in the practice must be told immediately, and how",
        "What your protocol says to do when a patient declines an ambulance",
        "What is recorded, by whom, and where",
        "When the event has to be raised as a significant event"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Covers triage of urgent symptoms, prescribing processes and vaccine handling across the whole team."
        },
        {
          "ref": "CQC Regulation 13, Safeguarding",
          "body": "Every member of the practice team, clinical or not, must know how to raise a concern."
        },
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "Requires protocols to be current, followed and evidenced, including by locums and temporary staff."
        }
      ]
    },
    {
      "id": "dental-practices",
      "num": "18",
      "title": "Dental Practices",
      "tag": "Decontamination, radiography and emergencies, answered between patients.",
      "desc": "A dental team has minutes between patients and questions that cannot wait until the end of the list. CareStreamAI answers from your own practice policies, on the surgery computer or on a phone, with the document and version shown.",
      "points": [
        "Nurses get your decontamination procedure at the point of reprocessing, rather than from memory.",
        "Radiography justification and responsibilities are answered from your own policy, in the surgery.",
        "Medical emergency and anaphylaxis steps are one tap away for every member of the team.",
        "Every query is logged, evidencing that practice policies are in daily use."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Decontamination",
        "Radiography",
        "Medical Emergencies",
        "Infection Control",
        "Consent",
        "Complaints"
      ],
      "exBadge": "Chat",
      "exLabel": "A real question from this setting",
      "question": "The autoclave has failed its test cycle this morning. Can we carry on with the list?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Decontamination Policy",
        "HTM 01-05, Decontamination in Dental Practices",
        "CQC Regulation 12, Safe Care and Treatment"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "What your policy says to do with the failed cycle and its load",
        "Whether treatment can continue, and on what basis",
        "Who is informed and what is recorded in the log",
        "The checks required before the machine is used again"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Covers decontamination, infection control and the practice’s response to a medical emergency."
        },
        {
          "ref": "HTM 01-05, Decontamination in Dental Practices",
          "body": "Sets out the reprocessing standards your local procedure is written against."
        },
        {
          "ref": "IR(ME)R 2017",
          "body": "Governs justification, authorisation and duties for every dental radiograph taken."
        }
      ]
    },
    {
      "id": "nursing-agencies",
      "num": "19",
      "title": "Nursing and Care Staffing Agencies",
      "tag": "Your workers are judged on their first hour in a building they have never entered.",
      "desc": "An agency worker signs in and is expected to practise safely in a service whose procedures they have never read. CareStreamAI puts your handbook, your client packs and your training on the worker’s phone, so a first booking looks like an experienced shift.",
      "points": [
        "Workers check your arrival and induction steps before they need to interrupt the nurse in charge.",
        "Where a client’s procedure differs from your own, the handbook says which applies on their premises.",
        "Training completion and renewals are tracked per worker, ready for a client or framework audit.",
        "Every query is logged, showing where your induction pack is unclear so you can fix it once."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Induction on Arrival",
        "Medication",
        "Incident Reporting",
        "Safeguarding",
        "Mandatory Training",
        "Conduct and Professionalism"
      ],
      "exBadge": "Chat",
      "exLabel": "A real question from this setting",
      "question": "First shift at this home tonight. Where do they keep the controlled drugs and who signs with me?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Agency Worker Handbook",
        "The client pack for this service",
        "CQC Regulation 18, Staffing"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "What to confirm with the nurse in charge before your shift starts",
        "Which procedure applies when the home’s differs from ours",
        "How to report an incident to both the home and the agency",
        "What to feed back to the office at the end of the booking"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 18, Staffing",
          "body": "Workers supplied to a service must be competent, current and properly supported for the shift they take."
        },
        {
          "ref": "CQC Regulation 19, Fit and Proper Persons Employed",
          "body": "Requires evidence of checks, qualifications and training for every worker you place."
        },
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "Your clients must be able to see that the staff you supply are trained, briefed and accounted for."
        }
      ]
    },
    {
      "id": "mental-health-hospitals",
      "num": "20",
      "title": "Independent Mental Health Hospitals",
      "tag": "Ward procedures, applied the same way on every shift.",
      "desc": "Wards run on procedures that have to be applied exactly: observation levels, restrictive interventions, leave and the rights of detained patients. CareStreamAI puts them on every nurse and support worker’s phone, so bank and agency staff practise to the same standard as your permanent team.",
      "points": [
        "Staff get your recording, reporting and debrief requirements immediately after a restrictive intervention.",
        "Questions about leave, advocacy and rights are answered consistently by everyone on the ward.",
        "Bank and agency staff work to your procedures rather than to habits carried in from another hospital.",
        "Every query is logged, evidencing how your procedures are used on nights and at weekends."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Observation Levels",
        "Restrictive Interventions",
        "Seclusion",
        "Leave and Authorisation",
        "Patients' Rights",
        "Physical Health Escalation"
      ],
      "exBadge": "Voice",
      "exLabel": "A real question from this setting",
      "question": "A detained patient is asking why he cannot leave the ward tonight. What am I allowed to tell him and what do I do next?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Mental Health Act and Leave Policy",
        "Your Patients' Rights and Advocacy Procedure",
        "CQC Regulation 17, Good Governance"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "How your policy asks you to explain leave and authorisation",
        "Who must be told, and how quickly",
        "How to offer access to an advocate",
        "What has to be recorded about the conversation"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 13, Safeguarding and Improper Treatment",
          "body": "Sets the limits on restraint and restriction, and requires them to be a last resort and properly recorded."
        },
        {
          "ref": "CQC Regulation 11, Need for Consent",
          "body": "Consent and capacity still apply alongside detention, and staff are asked about both on the ward."
        },
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "Requires accurate records of observation, intervention and leave, on every shift."
        }
      ]
    },
    {
      "id": "neuro-rehabilitation",
      "num": "21",
      "title": "Neuro-rehabilitation and Brain Injury",
      "tag": "The rehabilitation plan, followed after therapy has gone home.",
      "desc": "Progress is made in the hours between therapy sessions, by rehab assistants, nurses and night staff. CareStreamAI gives all of them your protocols and the person’s plan, cited and current, so the plan survives contact with a busy shift.",
      "points": [
        "Staff check the current dysphagia, tracheostomy or seizure protocol at the point of care, not from memory.",
        "Rehab assistants know what they can progress themselves and when therapy input is required.",
        "The agreed approach to behaviour after brain injury is available on every shift, not just when therapy is on site.",
        "Every query is logged, showing which parts of the plan staff most often need to check."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Dysphagia and IDDSI",
        "Tracheostomy Care",
        "Seizure Management",
        "Moving and Handling",
        "Behaviour After Brain Injury",
        "Goal Setting and Recording"
      ],
      "exBadge": "Chat",
      "exLabel": "A real question from this setting",
      "question": "He is coughing at every meal again this week. What am I meant to do about his diet tonight?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Dysphagia and Eating and Drinking Policy",
        "The current speech and language therapy recommendation",
        "CQC Regulation 12, Safe Care and Treatment"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "What to stop, and how to position him safely",
        "Why staff must not change diet or fluid consistency themselves",
        "Who to refer to, and by when",
        "What to record so therapy can act on it in the morning"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 9, Person-centred Care",
          "body": "Requires care and treatment to follow the individual rehabilitation plan, on every shift."
        },
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Covers swallowing, airway, seizures and skin integrity, where the protocol has to be followed exactly."
        },
        {
          "ref": "CQC Regulation 18, Staffing",
          "body": "Requires staff to be competent for the clinical tasks they carry out between therapy sessions."
        }
      ]
    },
    {
      "id": "prison-healthcare",
      "num": "22",
      "title": "Prison and Secure Healthcare",
      "tag": "Clinical procedures, delivered inside a security regime.",
      "desc": "Healthcare in a prison means working to your clinical procedures and the establishment’s regime at the same time, usually with high turnover and heavy bank cover. CareStreamAI puts your procedures on every clinician’s device, cited and current.",
      "points": [
        "Staff get your emergency response procedure, including the agreed code and who calls the ambulance, in seconds.",
        "In-possession, supervised and substitution medicines procedures are answered at the point of administration.",
        "Clinicians new to this establishment start from your written procedure rather than another site’s practice.",
        "Every query is logged, evidencing equivalence of care in a setting that makes it harder to demonstrate."
      ],
      "topicsLabel": "Policy areas staff ask about most",
      "topics": [
        "Emergency Response",
        "Medicines in Possession",
        "Substitution Therapy",
        "Reception Screening",
        "Risk of Self-harm",
        "Confidentiality"
      ],
      "exBadge": "Chat",
      "exLabel": "A real question from this setting",
      "question": "A man on the wing is unresponsive. What is our procedure and who confirms the ambulance has been called?",
      "sourcesLabel": "Answered from",
      "sources": [
        "Your Medical Emergency Response Procedure",
        "Your Escalation and Handover Procedure",
        "CQC Regulation 12, Safe Care and Treatment"
      ],
      "coversLabel": "What the answer covers",
      "covers": [
        "The code to declare so officers open the gates without delay",
        "What equipment to take and who brings the defibrillator",
        "Who confirms 999 has been called and meets the crew",
        "The times and observations to record for the incident review"
      ],
      "mapsLabel": "What this maps to",
      "maps": [
        {
          "ref": "CQC Regulation 12, Safe Care and Treatment",
          "body": "Covers medicines management and emergency response in a setting where movement is controlled by others."
        },
        {
          "ref": "CQC Regulation 13, Safeguarding",
          "body": "Healthcare has a defined role in the establishment’s safety procedures, and staff must know theirs exactly."
        },
        {
          "ref": "CQC Regulation 17, Good Governance",
          "body": "Requires accurate records and evidence that current procedures are the ones in use on every wing."
        }
      ]
    }
  ],
  "cards": [
    {
      "title": "All three channels",
      "body": "Chat, email, and voice. Staff access policies whichever way suits their role and environment."
    },
    {
      "title": "50 plus languages",
      "body": "Every staff member gets the same quality of policy access regardless of their first language."
    },
    {
      "title": "CQC evidence built in",
      "body": "Every query is logged. Your CQC Readiness Report is generated automatically, not assembled under pressure."
    },
    {
      "title": "Always up to date",
      "body": "Upload a new policy version and CareStreamAI answers from it immediately. Staff never read superseded guidance."
    }
  ],
  "roles": [
    {
      "role": "Registered Manager",
      "body": "Policy support for your team, even when you are not there.",
      "points": [
        "Staff on night shifts get instant policy answers without calling you, reducing out-of-hours interruptions and giving your team confidence to act correctly.",
        "Your CQC Readiness Report is built automatically, showing inspectors exactly how your team engages with your policies.",
        "When a policy is updated, CareStreamAI tracks whether staff accessed the new version, so you know the change actually reached your team.",
        "Policy gap detection tells you what your library is missing before a CQC inspector asks."
      ]
    },
    {
      "role": "HR Director and People Lead",
      "body": "Stop answering the same questions. Let your handbook answer them.",
      "points": [
        "Annual leave, sickness procedures, disciplinary processes: staff get instant answers from your actual handbook, 24 hours a day, without HR intervention.",
        "New starters, including international recruits, can ask questions about their employment terms in their own language from day one.",
        "Handbook access is fully logged, so you can see which sections staff query most and identify where onboarding communications need improving.",
        "Reduces repetitive HR query load, freeing your team for work that requires human judgement."
      ]
    },
    {
      "role": "Operations Director",
      "body": "One policy library. Consistent answers. Across every service.",
      "points": [
        "All services draw from the same centrally managed, approved policy library, eliminating version drift and inconsistent practice.",
        "Per-service analytics show which locations are engaged and where to focus support.",
        "When a policy is updated centrally, you can see which services accessed the new version and confirm the change reached the whole team.",
        "Group CQC Readiness Reports cover all registered services in a single export."
      ]
    },
    {
      "role": "Finance Director and Owner",
      "body": "A return on investment you can calculate in under five minutes.",
      "points": [
        "If CareStreamAI saves each manager one hour per week of policy query handling, it pays for itself in the first month.",
        "Reduces procedural risk by ensuring staff act on correct, approved guidance, with a full audit trail to demonstrate due diligence.",
        "Reduces CQC preparation time: inspection evidence is built automatically, not assembled manually under pressure.",
        "Improves staff confidence and reduces early turnover, particularly for international recruits who gain full policy access in their own language from day one."
      ]
    }
  ],
  "note": {
    "title": "Important notice",
    "paras": [
      "CareStreamAI does not provide professional, legal, clinical, or regulatory advice of any kind. The system retrieves and presents accurate information drawn directly from your organisation's own approved policies, procedures, and handbooks, and from publicly available external regulations and guidance. All responses reflect the content of those documents as uploaded and maintained by your organisation.",
      "Staff should always exercise their own professional judgement and, where required, seek guidance from a registered manager, clinician, or qualified professional. CareStreamAI is an information access tool. It does not replace supervision, professional registration, clinical decision-making, or the duty of care that rests with your organisation and its staff."
    ]
  }
}
